### PR TITLE
Return underlying error when parsing a command failed in the wallet API version 2

### LINKED ISSUE #7410: Return underlying error when parsing a command failed in the wallet API

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Close #7410

### CODE REVIEW

**Review by ze97286 — DISMISSED** [review]

**Review by wwestgarth — DISMISSED** [review]

File: wallet/api/client_sign_transaction_test.go [hunk 1]
```diff
@@ -66,7 +67,7 @@ func testSigningTransactionWithInvalidParamsFails(t *testing.T) {
 					"type": "not vega command",
 				},
 			},
-			expectedError: api.ErrTransactionIsNotValidVegaCommand,
+			expectedError: errors.New("the transaction is not a valid Vega command: unknown field \"type\" in vega.wallet.v1.SubmitTransactionRequest"),
```
Comment (candida-d) [inline wallet/api/client_sign_transaction_test.go:70]: Does this mean that someone has used a field called 'type' and it's unknown?

Comment (ValentinTrinque) [reply wallet/api/client_sign_transaction_test.go:70]: Just FYI, this a test. So I created dumb payload with a field `type`, knowing there is none for that object. When parsed as a transaction, proto is unhappy and tells me `unknown field \"type\"`. This is not a error message we have control of.

Comment (candida-d) [reply wallet/api/client_sign_transaction_test.go:70]: Oh! Sorry I missed that it was a test, that explains why it's so specific

**Review by jeremyletang — APPROVED** [review]
