### PR TITLE
fix: fix data source resolvers

### LINKED ISSUE #6655: dataSourceSpec field failure
# Problem encountered
Querying for data source information fails on stagnet1

# Observed behaviour
Given the following query
```
query {
  market(id:"93a665b27ca4a823ef9ae6fe4b92ff4a69efe584d18840ffad6b470c60bbefb4") {
    id
    tradableInstrument {
      instrument {
        product {
          ... on Future {
            dataSourceSpecForSettlementData {
              id
            }
          }
        }
      }
    }
  }
}
```

# Expected behaviour
Should be able to get the id back

# System response
Instead I get an error and null for market

```
{
  "errors": [
    {
      "message": "must not be null",
      "path": [
        "market",
        "tradableInstrument",
        "instrument",
        "product",
        "dataSourceSpecForSettlementData"
      ]
    }
  ],
  "data": {
    "market": null
  }
}
```

## Additional context
The other data source fields appear to work as expected. It just seems to be dataSourceSpecForSettlementData

### PR DESCRIPTION
**Pull request by AnExsomnis**
close: #6655 
close #6757

### CODE REVIEW

File: datanode/gateway/graphql/oracles_resolver.go [hunk 1]
```diff
@@ -67,25 +69,112 @@ func (o *oracleSpecResolver) DataConnection(ctx context.Context, obj *vegapb.Ora
...
-			for i, signer := range obj.ExternalData.Data.Signers {
-				signers[i] = &Signer{
-					Signer: signer.GetSigner().(SignerKind),
+		if obj.ExternalData != nil && obj.ExternalData.Data != nil {
+			o := obj.ExternalData.Data
+			broadcastAt := strconv.FormatInt(o.BroadcastAt, 10)
+			matchedSpecs := []string{}
+			if len(o.MatchedSpecIds) > 0 {
+				matchedSpecs = o.MatchedSpecIds
+			}
```
Comment (zale144) [inline datanode/gateway/graphql/oracles_resolver.go:83]: These are the same types. Unless you wanted to ensure that we don't get `null` in the response, but instead at least an empty string array, in which case you could do:
```suggestion
			if len(o.MatchedSpecIds) == 0 {
				o.MatchedSpecIds = []string{}
			}
```

File: datanode/gateway/graphql/oracles_resolver.go [hunk 2]
```diff
@@ -67,25 +69,112 @@ func (o *oracleSpecResolver) DataConnection(ctx context.Context, obj *vegapb.Ora
...
+
+			properties := []*v1.Property{}
+			if len(o.Data) > 0 {
+				properties = o.Data
+			}
```
Comment (zale144) [inline datanode/gateway/graphql/oracles_resolver.go:88]: same as above

File: datanode/gateway/graphql/oracles_resolver.go [hunk 3]
```diff
@@ -14,43 +14,45 @@ package gql
...
 	var specID *string
-	if obj != nil && obj.ExternalDataSourceSpec.Spec.Id != "" {
-		specID = &obj.ExternalDataSourceSpec.Spec.Id
+	if obj != nil {
+		if obj.ExternalDataSourceSpec != nil {
+			if obj.ExternalDataSourceSpec.Spec != nil {
+				specID = &obj.ExternalDataSourceSpec.Spec.Id
+			}
+		}
 	}
```
Comment (zale144) [inline datanode/gateway/graphql/oracles_resolver.go:54]: No need to check if `obj` is `nil`, it's checked in the `graphql` library:

```
case *vega.OracleSpec:
		if obj == nil {
			return graphql.Null
		}
		return ec._OracleSpec(ctx, sel, obj)
     ...
```

```suggestion
	if ed := obj.ExternalDataSourceSpec; ed != nil && ed.Spec != nil && ed.Spec.Id != "" {
		specID = &ed.Spec.Id
	}
```

File: datanode/gateway/graphql/oracles_resolver.go [hunk 4]
```diff
@@ -14,43 +14,45 @@ package gql
...
-
-			dataSourceSpec.Data = &DataSourceDefinition{
-				SourceType: obj.ExternalDataSourceSpec.Spec.Data.SourceType.(DataSourceKind),
+	if obj.ExternalDataSourceSpec != nil {
+		if obj.ExternalDataSourceSpec.Spec != nil {
+			if obj.ExternalDataSourceSpec.Spec.Data != nil {
+				dataSourceSpec = resolveDataSourceSpec(obj.ExternalDataSourceSpec.Spec)
 			}
 		}
 	}
```
Comment (zale144) [inline datanode/gateway/graphql/oracles_resolver.go:39]:
```suggestion
	if ed := obj.ExternalDataSourceSpec; ed != nil && ed.Spec != nil && ed.Spec.Data != nil {
		dataSourceSpec = resolveDataSourceSpec(ed.Spec.Data)
	}
```

File: datanode/gateway/graphql/oracles_resolver.go [hunk 5]
```diff
@@ -67,25 +69,112 @@ func (o *oracleSpecResolver) DataConnection(ctx context.Context, obj *vegapb.Ora
...
+			if pk := o.GetPubKey(); pk != nil {
+				signer.Signer = &PubKey{
+					Key: &pk.Key,
+				}
+			} else if ethAddr := o.GetEthAddress(); ethAddr != nil {
+				signer.Signer = &ETHAddress{
+					Address: &ethAddr.Address,
 				}
+			} else {
+				return nil, errors.New("invalid signer type")
```
Comment (zale144) [inline datanode/gateway/graphql/oracles_resolver.go:122]: `o.Signer` could be `nil`, so maybe just leave `signer` as is, since we don't know if the type is wrong or it's just `nil`

File: datanode/gateway/graphql/update_future_resolver.go [hunk 6]
```diff
@@ -21,23 +21,25 @@ import (
 type updateFutureProductResolver VegaResolverRoot
 
 func (r *updateFutureProductResolver) DataSourceSpecForSettlementData(ctx context.Context, obj *vega.UpdateFutureProduct) (*DataSourceDefinition, error) {
-	if obj.DataSourceSpecForSettlementData != nil {
-		return nil, nil
+	ds := &DataSourceDefinition{}
+
+	if obj != nil {
```
Comment (zale144) [inline datanode/gateway/graphql/update_future_resolver.go:26]: no need to check if `obj != nil`

File: datanode/gateway/graphql/update_future_resolver.go [hunk 7]
```diff
@@ -21,23 +21,25 @@ import (
...
-	}, nil
+	return ds, nil
 }
 
 func (r *updateFutureProductResolver) DataSourceSpecForTradingTermination(ctx context.Context, obj *vega.UpdateFutureProduct) (*DataSourceDefinition, error) {
-	if obj.DataSourceSpecForTradingTermination == nil {
-		return nil, nil
+	ds := &DataSourceDefinition{}
+
+	if obj != nil {
```
Comment (zale144) [inline datanode/gateway/graphql/update_future_resolver.go:38]: same as above

File: datanode/gateway/graphql/resolvers.go [hunk 8]
```diff
@@ -2414,18 +2414,11 @@ func (r *myCandleResolver) Volume(_ context.Context, obj *v2.Candle) (string, er
...
-		signers := make([]*Signer, len(obj.Signers))
-
-		for i, signer := range obj.Signers {
-			signers[i] = &Signer{
-				Signer: signer.GetSigner().(SignerKind),
-			}
-		}
-
-		return signers, nil
+	if obj != nil {
```
Comment (zale144) [inline datanode/gateway/graphql/resolvers.go:2417]: no need to check if `obj != nil`, it's checked in the layer above

File: datanode/gateway/graphql/future_resolver.go [hunk 9]
```diff
@@ -15,34 +15,40 @@ package gql
...
 
-func (r *myFutureResolver) DataSourceSpecForTradingTermination(ctx context.Context, obj *vega.Future) (*DataSourceSpec, error) {
-	if obj.DataSourceSpecForTradingTermination == nil {
-		return nil, nil
+func (r *myFutureResolver) DataSourceSpecForTradingTermination(ctx context.Context, obj *vegapb.Future) (*DataSourceSpec, error) {
+	ds := &DataSourceSpec{
+		Data: &DataSourceDefinition{},
+	}
+
+	if obj != nil {
```
Comment (zale144) [inline datanode/gateway/graphql/future_resolver.go:47]: no need for this nil check

File: datanode/gateway/graphql/future_resolver.go [hunk 10]
```diff
@@ -15,34 +15,40 @@ package gql
...
+func (r *myFutureResolver) DataSourceSpecForSettlementData(ctx context.Context, obj *vegapb.Future) (*DataSourceSpec, error) {
+	ds := &DataSourceSpec{
+		Data: &DataSourceDefinition{},
 	}
 
-	dataSourceSpec := obj.DataSourceSpecForSettlementData
-	return &DataSourceSpec{
-		ID: dataSourceSpec.GetId(),
-	}, nil
+	if obj != nil {
```
Comment (zale144) [inline datanode/gateway/graphql/future_resolver.go:33]: no need for this nil check

File: datanode/gateway/graphql/future_product_resolver.go [hunk 11]
```diff
@@ -15,34 +15,36 @@ package gql
...
+	return d, nil
 }
 
-func (r *myFutureProductResolver) DataSourceSpecForTradingTermination(ctx context.Context, obj *vega.FutureProduct) (*DataSourceDefinition, error) {
-	if obj.DataSourceSpecForTradingTermination == nil {
-		return nil, nil
+func (r *myFutureProductResolver) DataSourceSpecForTradingTermination(ctx context.Context, obj *vegapb.FutureProduct) (*DataSourceDefinition, error) {
+	d := &DataSourceDefinition{}
+
+	if obj != nil {
```
Comment (zale144) [inline datanode/gateway/graphql/future_product_resolver.go:43]: same as below

File: datanode/gateway/graphql/future_product_resolver.go [hunk 12]
```diff
@@ -15,34 +15,36 @@ package gql
...
 	return r.r.getAssetByID(ctx, obj.SettlementAsset)
 }
 
-func (r *myFutureProductResolver) DataSourceSpecForSettlementData(ctx context.Context, obj *vega.FutureProduct) (*DataSourceDefinition, error) {
-	if obj.DataSourceSpecForSettlementData == nil {
-		return nil, nil
+func (r *myFutureProductResolver) DataSourceSpecForSettlementData(ctx context.Context, obj *vegapb.FutureProduct) (*DataSourceDefinition, error) {
+	d := &DataSourceDefinition{}
+
+	if obj != nil {
```
Comment (zale144) [inline datanode/gateway/graphql/future_product_resolver.go:31]: as below

**Review by zale144 — COMMENTED** [review]
Nice work. Just some minor comments

**Comment by zale144** [comment]
It would be nice to add some unit tests for these changes. I've written a test for the `oracleSpecResolver_DataSourceSpec`, let me know if you would like to use it

**Review by mattrussell36 — DISMISSED** [review]

File: datanode/gateway/graphql/oracles_resolver.go [hunk 13]
```diff
@@ -67,25 +69,112 @@ func (o *oracleSpecResolver) DataConnection(ctx context.Context, obj *vegapb.Ora
...
+						},
+					},
+				}
+			}
+		} else if int := d.GetInternal(); int != nil {
+			switch int.SourceType.(type) {
+			case *vegapb.DataSourceDefinitionInternal_Time:
+				_ = int.GetTime()
+			}
 		}
```
[the remark this answers is not in the document]
Comment (AnExsomnis) [reply datanode/gateway/graphql/oracles_resolver.go]: This has been improved as suggested here https://github.com/vegaprotocol/vega/pull/6750/commits/439e167fbb5953adcc6b6d7a481ea70596b19512#diff-0cde61576df49d23ac0103aca13202a605d1c83edf31d12fdc3d5281c83005c9R116
Thanks!

File: datanode/gateway/graphql/oracles_resolver.go (hunk 1 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/oracles_resolver.go]: Yes, corrected that here https://github.com/vegaprotocol/vega/pull/6750/commits/439e167fbb5953adcc6b6d7a481ea70596b19512#diff-0cde61576df49d23ac0103aca13202a605d1c83edf31d12fdc3d5281c83005c9R79-R80
Thanks!

File: datanode/gateway/graphql/oracles_resolver.go (hunk 2 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/oracles_resolver.go]: Fixed as well here https://github.com/vegaprotocol/vega/pull/6750/commits/439e167fbb5953adcc6b6d7a481ea70596b19512#diff-0cde61576df49d23ac0103aca13202a605d1c83edf31d12fdc3d5281c83005c9R79-R80
Thanks!

File: datanode/gateway/graphql/oracles_resolver.go (hunk 3 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/oracles_resolver.go]: Corrected this  https://github.com/vegaprotocol/vega/pull/6750/commits/439e167fbb5953adcc6b6d7a481ea70596b19512#diff-0cde61576df49d23ac0103aca13202a605d1c83edf31d12fdc3d5281c83005c9R43-R44
Thanks!

File: datanode/gateway/graphql/oracles_resolver.go (hunk 4 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/oracles_resolver.go]: This has been addressed here https://github.com/vegaprotocol/vega/pull/6750/commits/439e167fbb5953adcc6b6d7a481ea70596b19512#diff-0cde61576df49d23ac0103aca13202a605d1c83edf31d12fdc3d5281c83005c9R32-R33
Thanks!

File: datanode/gateway/graphql/oracles_resolver.go (hunk 5 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/oracles_resolver.go]: Yes, corrected this as well
Thanks!

File: datanode/gateway/graphql/update_future_resolver.go (hunk 6 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/update_future_resolver.go]: This and all below are addressed as well, thanks !

File: datanode/gateway/graphql/oracles_resolver.go [hunk 14]
```diff
@@ -16,41 +16,28 @@ import (
...
-		Spec: dataSourceSpec,
-	}, nil
+	return
 }
 
 func (o *oracleSpecResolver) DataConnection(ctx context.Context, obj *vegapb.OracleSpec, pagination *v2.Pagination) (*v2.OracleDataConnection, error) {
 	var specID *string
-	if obj != nil && obj.ExternalDataSourceSpec.Spec.Id != "" {
-		specID = &obj.ExternalDataSourceSpec.Spec.Id
+	if ed := obj.ExternalDataSourceSpec; ed != nil && ed.Spec != nil && ed.Spec.Id != "" {
```
[the remark this answers is not in the document]
Comment (AnExsomnis) [reply datanode/gateway/graphql/oracles_resolver.go:37]: The object being nil is checked here
```
case *vega.OracleSpec:
		if obj == nil {
			return graphql.Null
		}
		return ec._OracleSpec(ctx, sel, obj)
     ...
```
So I decided its not needed, am I wrong?

File: datanode/utils/pointer.go [hunk 15]
```diff
@@ -0,0 +1,12 @@
...
+func ToPtr[T any](val T) *T {
+	return &val
+}
+
+func FromPtr[T any](ptr *T) (val T) {
+	if ptr != nil {
+		val = *ptr
+	}
+	return
+}
```
[the remark this answers is not in the document]
Comment (AnExsomnis) [reply datanode/utils/pointer.go]: Yes, removed that here https://github.com/vegaprotocol/vega/pull/6750/commits/22e8d363bfb9891d820087a3b61611bc2910e221
Thanks!

**Review by pscott31 — DISMISSED** [review]

**Review by jeremyletang — APPROVED** [review]
