### PR TITLE
fix: remove unions from orders views

### LINKED ISSUE #6699: Remove unions and triggers on orders views
The `orders` and `orders_current` uses a union on `orders_live` and `orders_history` table, however the `orders_history` table should now contain the data from `orders_live` also and the unions are no longer needed.

As the `orders` and `orders_current` views are queried by the API, the `union` queries take a long time to complete and therefore make the API appears as though they are not returning data.

### PR DESCRIPTION
**Pull request by guoguojin**
Closes #6699

### CODE REVIEW

File: datanode/dehistory/service_test.go [hunk 1]
```diff
@@ -262,6 +272,10 @@ func TestMain(t *testing.M) {
 }
 
 func TestRestoringFromDifferentHeightsWithFullHistory(t *testing.T) {
+	if schemaChanged {
```
Comment (ettec) [inline datanode/dehistory/service_test.go:275]: as discussed, just update the hash, no need for the schemaChanged flag

**Review by ettec — CHANGES_REQUESTED** [review]

File: datanode/dehistory/service_test.go (hunk 1 above)
Comment (guoguojin) [reply datanode/dehistory/service_test.go]: Thanks, my mistake. Fixed https://github.com/vegaprotocol/vega/pull/6702/commits/05f9ce2b83c1e6b5fa485bb137ba0bd202c05e65

**Comment by jeremyletang** [comment]
@guoguojin @ettec I removed the `drop view if exists orders;` statement here. that can't work if orders was a table and we are trying to drop it, this results into an error.

I think that ongoing we should suffix all views with `_view` or something like so just to prevent this kind of issues in future migrations.

**Review by pscott31 — APPROVED** [review]
