### PR TITLE
fix: restore stats in referral engine when loading from a snapshot

### LINKED ISSUE #9535: [Bug]: Snapshot failure on fairground pipeline
### Problem encountered

A snapshot failure has occurred on the fairground snapshot pipeline:
```
Error in validation	{"err": "wrong Block.Header.AppHash.  Expected A8303A627126AB0BB15C2882E8C34CA9DBCF960C385150A622B6CB6523D77D8C, got 77B4632DAB22057E1A2AF4E01A48F06DCE6FEBF31E929E05968BA931228306CB"}
```

https://jenkins.vega.rocks/blue/organizations/jenkins/private%2FSnapshots%2FFairground/detail/Fairground/3073/pipeline/160

### Observed behaviour

Node falls out of consensus we restoring from a snapshot.

### Expected behaviour

Node does not fall out of consensus when restoring from a snapshot.

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

v0.73.0.preview-7

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by wwestgarth**
closes #9535

### CODE REVIEW

File: core/referral/snapshot_test.go [hunk 1]
```diff
@@ -189,6 +188,21 @@ func TestTakingAndRestoringSnapshotSucceeds(t *testing.T) {
 	// Simulate restoration of the network parameter at the time of the snapshot
 	require.NoError(t, te2.engine.OnReferralProgramMaxPartyNotionalVolumeByQuantumPerEpochUpdate(ctx, maxVolumeParams))
 
+	// OnStateLoaded will recalculate referrer stats and send out all these events
+	te2.marketActivityTracker.EXPECT().NotionalTakerVolumeForParty(string(referrer1)).Return(num.UintFromUint64(100)).Times(1)
```
Comment (EVODelavega) [inline core/referral/snapshot_test.go:192]: why not `Times(2)` for referrers 1-4? Or just create a matcher type that matches all expected calls exactly once?

**Review by ze97286 — APPROVED** [review]

**Review by AnExsomnis — APPROVED** [review]
