### PR TITLE
fix: nil pointer panic

### LINKED ISSUE #10126: [Bug]: StopOrdersSubmission in batch proposal without any values crashes datanode
### Problem encountered

datanode crash when submitting batch proposal with no values e.g. `cmd.StopOrdersSubmission()`

```
goroutine 33760 [running]:
code.vegaprotocol.io/vega/core/processor.(*Gastimator).batchGastimate(0x14000cfcf60, 0x1401989a820)
	/Users/sohillpatel/Documents/GitHub/vega/core/processor/gastimator.go:215 +0x2a8
code.vegaprotocol.io/vega/core/processor.(*Gastimator).CalcGasWantedForTx(0x14000cfcf60, {0x105f9a600, 0x1401976a980})
	/Users/sohillpatel/Documents/GitHub/vega/core/processor/gastimator.go:130 +0x3e8
code.vegaprotocol.io/vega/core/processor.(*App).OnCheckTx(0x140003fca80, {0x105f71280, 0x1401982e960}, 0x0?, {0x105f9a600, 0x1401976a980})
	/Users/sohillpatel/Documents/GitHub/vega/core/processor/abci.go:1241 +0x344
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).CheckTx(0x140002b8180, {0x109974a68?, 0x30?}, 0x14019377e40)
	/Users/sohillpatel/Documents/GitHub/vega/core/blockchain/abci/abci.go:125 +0x1a0
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).CheckTx(0x14018e991f8?, {0x105f71210?, 0x14000128018?}, 0x105ac6760?)
	/Users/sohillpatel/Documents/GitHub/vega/cmd/vega/commands/node/app_wrapper.go:44 +0x30
github.com/cometbft/cometbft/abci/client.(*localClient).CheckTxAsync(0x14000fc8cc0, {0x105f71210?, 0x14000128018?}, 0x14019377e40)
	/Users/sohillpatel/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/abci/client/local_client.go:51 +0xf4
github.com/cometbft/cometbft/proxy.(*appConnMempool).CheckTxAsync(0x14000f9ed08, {0x105f71210, 0x14000128018}, 0x102103858?)
	/Users/sohillpatel/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/proxy/app_conn.go:147 +0xf0
github.com/cometbft/cometbft/mempool.(*CListMempool).CheckTx(0x1400c7cc000, {0x14014f1f900, 0x13a, 0x13a}, 0x5da2092ce2?, {0x1f60?, {0x0?, 0x102166880?}})
	/Users/sohillpatel/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/mempool/clist_mempool.go:268 +0x1cc
github.com/cometbft/cometbft/rpc/core.(*Environment).BroadcastTxSync(0x14000f06d80, 0x1400c7b3f00, {0x14014f1f900, 0x13a, 0x13a})
	/Users/sohillpatel/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/rpc/core/mempool.go:35 +0xd0
github.com/cometbft/cometbft/rpc/client/local.(*Local).BroadcastTxSync(...)
	/Users/sohillpatel/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/rpc/client/local/local.go:98
code.vegaprotocol.io/vega/core/blockchain/abci.(*LocalClient).SendTransactionSync(0x105f71280?, {0x140198a4180?, 0x14018e994d8?}, {0x14014f1f900?, 0x14018e99578?, 0x102103d04?})
	/Users/sohillpatel/Documents/GitHub/vega/core/blockchain/abci/local_client.go:54 +0x38
code.vegaprotocol.io/vega/core/blockchain.(*Client).SubmitTransactionSync(0x14000ff22c0, {0x105f71280, 0x140198a4180}, 0x30?)
	/Users/sohillpatel/Documents/GitHub/vega/core/blockchain/client.go:137 +0xdc
code.vegaprotocol.io/vega/core/api.(*coreService).SubmitTransaction(0x14000562300, {0x105f71280, 0x140198a4180}, 0x1401976a640)
	/Users/sohillpatel/Documents/GitHub/vega/core/api/core.go:157 +0x9c
code.vegaprotocol.io/vega/protos/vega/api/v1._CoreService_SubmitTransaction_Handler.func1({0x105f71280, 0x140198a4180}, {0x105bb9c20?, 0x1401976a640})
	/Users/sohillpatel/Documents/GitHub/vega/protos/vega/api/v1/core_grpc.pb.go:302 +0x74
code.vegaprotocol.io/vega/core/api.remoteAddrInterceptor.func1({0x105f71280, 0x140198a4120}, {0x105bb9c20, 0x1401976a640}, 0x14019377e20, 0x140185afed8)
	/Users/sohillpatel/Documents/GitHub/vega/core/api/grpc.go:231 +0x540
code.vegaprotocol.io/vega/protos/vega/api/v1._CoreService_SubmitTransaction_Handler({0x105e02680?, 0x14000562300}, {0x105f71280, 0x140198a4120}, 0x14018eeee00, 0x14000950040)
	/Users/sohillpatel/Documents/GitHub/vega/protos/vega/api/v1/core_grpc.pb.go:304 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0x140004401e0, {0x105f89760, 0x14000c97520}, 0x14019702240, 0x140009c38f0, 0x107fdaa00, 0x0)
	/Users/sohillpatel/go/pkg/mod/google.golang.org/grpc@v1.56.3/server.go:1335 +0xc90
google.golang.org/grpc.(*Server).handleStream(0x140004401e0, {0x105f89760, 0x14000c97520}, 0x14019702240, 0x0)
	/Users/sohillpatel/go/pkg/mod/google.golang.org/grpc@v1.56.3/server.go:1712 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/Users/sohillpatel/go/pkg/mod/google.golang.org/grpc@v1.56.3/server.go:947 +0xb4
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/sohillpatel/go/pkg/mod/google.golang.org/grpc@v1.56.3/server.go:958 +0x174
```

### Observed behaviour

datanode crash

### Expected behaviour

datanode does not crash

### Steps to reproduce

```bash
1. run system-test `test_batch_stop_order_entry` from branch test_batch_market_crash
```

### Software version

dev branch

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by EVODelavega**
Closes #10126

### CODE REVIEW

File: core/processor/gastimator.go [hunk 1]
```diff
@@ -209,9 +209,11 @@ func (g *Gastimator) batchGastimate(batch *commandspb.BatchMarketInstructions) u
...
 		}
 		var marketId string
+		// if both are nil, marketId will be empty string, yielding default gas
+		// the order is invalid, but validation is applied later.
 		if os.FallsBelow != nil {
 			marketId = os.FallsBelow.OrderSubmission.MarketId
-		} else {
+		} else if os.RisesAbove != nil {
 			marketId = os.RisesAbove.OrderSubmission.MarketId
 		}
```
Comment (jeremyletang) [inline core/processor/gastimator.go:218]: This would be safer as orderSubmission can be nil too:
```
if os.FallsBelow != nil && os.FallsBelow.OrderSubmission != nil {
```

Comment (EVODelavega) [reply core/processor/gastimator.go]: fixed

**Review by guoguojin — APPROVED** [review]
