### PR TITLE
fix: stop order proto to/from fixed

### LINKED ISSUE #11047: [Bug]: StopOrders sizeOverrideSetting and sizeOverrideValue values are different than submitted
### Problem encountered

Stop order submitted with  sizeOverrideSetting SIZE_OVERRIDE_SETTING_POSITION are returned as SIZE_OVERRIDE_SETTING_UNSPECIFIED. 
sizeOverrideValue is retuned as null

Transactions sent
image

Data returned from stopOrders graphql API
image

### Observed behaviour

wallet accepts sizeOverrideSetting sent as string or number. Transactions send both with "sizeOverrideSetting":2 and "sizeOverrideSetting":"SIZE_OVERRIDE_SETTING_POSITION" are retuned from stopOrders API with "SIZE_OVERRIDE_SETTING_UNSPECIFIED" value. 
"sizeOverrideValue" is sent as {"percentage":"1"} and returned from API as null

### Expected behaviour

Stop order should be created and returned with proper sizeOverrideSetting and sizeOverrideValue

### Steps to reproduce

```bash
Submit stop order with sizeOverrideSetting SIZE_OVERRIDE_SETTING_POSITION
Query stopOrders graphql API.
```

### Software version

v0.76.0-preview.1

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ze97286**
Closes #11047

### CODE REVIEW

File: core/types/stop_orders.go [hunk 1]
```diff
@@ -362,9 +367,11 @@ func (s *StopOrder) String() string {
 		s.Expiry.String(),
 		s.Trigger.String(),
 		s.Status,
-		s.CreatedAt,
-		s.UpdatedAt,
+		s.CreatedAt.UTC(),
```
Comment (jeremyletang) [inline core/types/stop_orders.go:370]: Why?

Comment (ze97286) [reply core/types/stop_orders.go:370]: for some reason the string was getting with GMT for the test so just forcing it to UTC to match the expectation, it shouldn't matter, it's only the string().

**Review by EVODelavega — DISMISSED** [review]

**Review by EVODelavega — APPROVED** [review]
