### PR TITLE
fix: expose live only filter to graphql orders filter

### LINKED ISSUE #8187: GraphQL orders filter does not expose live_only flag
The live_only option is available to gRPC and REST but was missed from the GraphQL API

### PR DESCRIPTION
**Pull request by guoguojin**
Closes #8187

### CODE REVIEW

**Review by pscott31 — DISMISSED** [review]

**Review by mattrussell36 — APPROVED** [review]

File: datanode/gateway/config.go [hunk 1]
```diff
@@ -52,7 +52,7 @@ type Config struct {
 	REST                     RESTGatewayServiceConfig `group:"REST" namespace:"rest"`
 	SubscriptionRetries      int                      `long:"subscription-retries" description:" "`
 	GraphQLPlaygroundEnabled encoding.Bool            `long:"graphql-playground" description:"Enables the GraphQL playground"`
-	MaxSubscriptionPerClient uint32                   `long:"max-subscription-per-client" description:"Maximum of graphql subscribption allowed per client"`
+	MaxSubscriptionPerClient uint32                   `long:"max-subscription-per-client" description:"Maximum of graphql subscriptions allowed per client"`
```
Comment (mattrussell36) [inline datanode/gateway/config.go:55]:
```suggestion
	MaxSubscriptionPerClient uint32                   `long:"max-subscription-per-client" description:"Maximum graphql subscriptions allowed per client"`
```

File: datanode/gateway/graphql/schema.graphql [hunk 2]
```diff
@@ -4161,6 +4161,8 @@ input OrderFilter {
   "Date range to retrieve orders from/to. Start and end time should be expressed as an integer value of nano-seconds past the Unix epoch"
   dateRange: DateRange
   excludeLiquidity: Boolean
+  "If true, only orders that are live will be returned."
```
Comment (mattrussell36) [inline datanode/gateway/graphql/schema.graphql:4164]: Would be good to know exactly what 'live' means. Is it just STATUS_ACTIVE, STATUS_PARKED and STATUS_PARTIALLY_FILLED?

**Review by mattrussell36 — DISMISSED** [review]

**Review by jeremyletang — APPROVED** [review]

**Review by EVODelavega — APPROVED** [review]
