### PR TITLE
fix: nil pointer in eth call engine when running with null block chain

### LINKED ISSUE #9334: [Bug]: Ethereum Client failing with nil pointer error on nullchain
### Problem encountered

When running nullchain following a recent update the core crashes with a nil pointer exception

### Observed behaviour

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13b2e07]

goroutine 181 [running]:
code.vegaprotocol.io/vega/core/client/eth.(*Client).BlockByNumber(0x0?, {0x3f58ca8?, 0xc000e9cc30?}, 0x0?)
	<autogenerated>:1 +0x27
code.vegaprotocol.io/vega/core/datasource/external/ethcall.(*Engine).Poll(0xc0002df2d0, {0x3f58ca8, 0xc000e9cc30}, {0x4927d0?, 0x4a817c800?, 0x5f615c0?})
	/jenkins/workspace/common/vega-market-sim/extern/vega/core/datasource/external/ethcall/engine.go:200 +0x74
code.vegaprotocol.io/vega/core/datasource/external/ethcall.(*Engine).Start.func1.1()
	/jenkins/workspace/common/vega-market-sim/extern/vega/core/datasource/external/ethcall/engine.go:89 +0x51
code.vegaprotocol.io/vega/core/datasource/external/ethcall.(*poller).Loop(0xc001851d40, 0xc0065edfa8)
	/jenkins/workspace/common/vega-market-sim/extern/vega/core/datasource/external/ethcall/engine.go:319 +0xa9
code.vegaprotocol.io/vega/core/datasource/external/ethcall.(*Engine).Start.func1()
	/jenkins/workspace/common/vega-market-sim/extern/vega/core/datasource/external/ethcall/engine.go:88 +0xf5
created by code.vegaprotocol.io/vega/core/datasource/external/ethcall.(*Engine).Start
	/jenkins/workspace/common/vega-market-sim/extern/vega/core/datasource/external/ethcall/engine.go:78 +0x65
```

### Expected behaviour

No error

### Steps to reproduce

```bash
Run fuzz test within Market Sim
```

### Software version

Latest develop

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #9348: [Bug]: Error in null blockchain caused by incorrect nil interface check
### Problem encountered

When running with null blockchain the node is considered a validator but does not have a valid eth client, the check in the engine fails to catch this due to the classic Go nil interface that passes nil check has a nil value 'feature' of golang.

### Observed behaviour

"

### Expected behaviour

"

### Steps to reproduce

```bash
"
```

### Software version

develop

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ettec**
closes #9334

### CODE REVIEW

File: core/datasource/external/ethcall/engine.go [hunk 1]
```diff
@@ -74,7 +75,7 @@ func NewEngine(log *logging.Logger, cfg Config, isValidator bool, client EthRead
 // Start starts the polling of the Ethereum bridges, listens to the events
 // they emit and forward it to the network.
 func (e *Engine) Start() {
-	if e.isValidator && e.client != nil {
```
Comment (ettec) [inline core/datasource/external/ethcall/engine.go:77]: Code assumes the valid passed into eth engine will always be a pointer, I think this is OK?

**Review by AnExsomnis — APPROVED** [review]
