### PR TITLE
Fix/10419 migrate old tx results

### LINKED ISSUE #10419: [Bug]: Very slow migration for the block explorer
The migration#0005 for the block explorer: https://github.com/vegaprotocol/vega/blob/develop/blockexplorer/store/migrations/0005_add_block_height_to_tx_result.sql

Takes a very long time on the stagnet1. 

At the moment We have 9 MLN rows in stagnet1 (3x less than We have on the mainnet).
The migration takes 16 hours already and the database is very very slow.

```
postgres=# SELECT pid, age(clock_timestamp(), query_start), usename, query
FROM pg_stat_activity
WHERE query != '<IDLE>' AND query NOT ILIKE '%pg_stat_activity%'
ORDER BY query_start desc;
   pid   |       age       |  usename   |                query
---------+-----------------+------------+--------------------------------------
 2200902 |                 | postgres   |
 2200899 |                 |            |
 2200901 |                 | postgres   |
 2200904 |                 | postgres   |
 2200903 |                 | postgres   |
 2200896 |                 |            |
 2200898 |                 |            |
 2200897 |                 |            |
 2202674 | 00:00:16.588972 | monitoring | SELECT * FROM pg_stat_bgwriter;
 3280199 | 16:13:54.483036 | postgres   | UPDATE tx_results                   +
         |                 |            | SET block_height=b.height           +
         |                 |            | FROM blocks b                       +
         |                 |            | WHERE b.rowid = tx_results.block_id;
```

# Expected behaviour

We should not update all the rows at the same time, We should do it in somehow in the batches. to let the service start and use users use the block explorer.

The long migration is not a problem with our testnets, but We cannot stop the service for 20 hours in the mainnet.

### PR DESCRIPTION
**Pull request by guoguojin**
Closes #10419

### CODE REVIEW

File: blockexplorer/store/migrator.go [hunk 1]
```diff
@@ -0,0 +1,245 @@
...
+	if err != nil {
+		return err
+	}
+
+	// loop through each date and migrate the data for the date
+	for _, d := range migrateDates {
+		// we're going to make use of temporary tables which are only visible to the session that created them
+		// we therefore have to use a single connection and make sure that the same connection is used for the
+		// migration process.
+		conn, err := m.pool.Acquire(context.Background())
```
Comment (EVODelavega) [inline blockexplorer/store/migrator.go:90]: Actually, I'm not sure about the use of the background index here, shouldn't we pass in/use the same context with which we call `Migrate` in `blockexplorer.go`?

**Review by EVODelavega — DISMISSED** [review]

**Review by EVODelavega — APPROVED** [review]
