### PR TITLE
fix: paid liquidity fee stats does not set epoch seq

### LINKED ISSUE #9853: Data node failing to start on stagnet 1
The data node has failed on stagnet1 when testing the market termination

Sent and voted this proposal for all of the available markets one by one:

https://github.com/vegaprotocol/devopstools/pull/87/files#diff-142f61c4af41a66863b836149039c6b5d9f029764add613c608378b8a8317141R192-R216

```
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: 2023-10-19T17:20:07.957Z        ERROR        datanode.sqlstore-broker        broker/sqlstore_broker.go:365        failed to process event id:"7005627-1759" block:"5588E439410E3B7993531B8A310D7528AF9DE0DBCFFDF1D44DFF916F4AAF0BC5" type:BUS_EVENT_TYPE_PAID_LIQUIDITY_FEES_STATS_UPDATED paid_liquidity_fees_stats:{market:"b66cd4be223dfd900a4750bb5175e17d8f678996877d262be4c749a99e22a970" asset:"177e8f6c25a955bd18475084b99b2b1d37f28f3dec393fab7755a7e69c3d8c3b" total_fees_paid:"8145" fees_paid_per_party:{party:"47007b73a6386c00ea473cc9f92e4a662d39d6beb614bec0ea9d1ea7d76f7619" amount:"0"} fees_paid_per_party:{party:"69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f" amount:"0"} fees_paid_per_party:{party:"844bf0f10d5d8c802cbc8e4e297194c46a976996faa7bd37c3a4903940323024" amount:"8145"}} version:1 chain_id:"vega-stagnet1-202307191148" tx_hash:"5588E439410E3B7993531B8A310D7528AF9DE0DBCFFDF1D44DFF916F4AAF0BC5" error:ERROR: duplicate key value violates unique constraint "paid_liquidity_fees_pkey" (SQLSTATE 23505)
Then

Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: 2023-10-19T17:20:07.986Z        ERROR        datanode.sqlstore-broker        broker/sqlstore_broker.go:365        failed to process event id:"7005627-1965" block:"5588E439410E3B7993531B8A310D7528AF9DE0DBCFFDF1D44DFF916F4AAF0BC5" type:BUS_EVENT_TYPE_MARKET_UPDATED market_updated:{id:"b66cd4be223dfd900a4750bb5175e17d8f678996877d262be4c749a99e22a970" tradable_instrument:{instrument:{code:"TSLA.QM21" name:"Tesla Quarterly (Sep 2023)" metadata:{tags:"formerly:5A86B190C384997F" tags:"quote:EURO" tags:"ticker:TSLA" tags:"class:equities/single-stock-futures" tags:"sector:tech" tags:"listing_venue:NASDAQ" tags:"country:US" tags:"auto:tsla"} future:{settlement_asset:"177e8f6c25a955bd18475084b99b2b1d37f28f3dec393fab7755a7e69c3d8c3b" quote_name:"EURO" data_source_spec_for_settlement_data:{id:"05ca5485678aa7c705aa6a683fd062714cbcfdac2d1a27641cd27b66168d9c1d" data:{external:{oracle:{signers:{pub_key:{key:"69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f"}} filters:{key:{name:"prices.TSLA.value" type:TYPE_INTEGER} conditions:{operator:OPERATOR_EQUALS value:"1"}}}}}} data_source_spec_for_trading_termination:{id:"3f5941ba047dabb3bec23f112db0a8cc8aecbbbc6b34d1366d9383ed1b0f39df" data:{external:{oracle:{signers:{pub_key:{key:"69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f"}} filters:{key:{name:"termination.TSLA.value" type:TYPE_BOOLEAN} conditions:{operator:OPERATOR_EQUALS value:"1"}}}}}} data_source_spec_binding:{settlement_data_property:"prices.TSLA.value" trading_termination_property:"termination.TSLA.value"}}} margin_calculator:{scaling_factors:{search_level:1.1 initial_margin:1.5 collateral_release:1.7}} log_normal_risk_model:{risk_aversion_parameter:0.01 tau:0.0001140771161 params:{r:0.016 sigma:0.8}}} decimal_places:5 fees:{factors:{maker_fee:"0.0002" infrastructure_fee:"0.0005" liquidity_fee:"0.0001"}} opening_auction:{duration:15} price_monitoring_settings:{parameters:{triggers:{horizon:43200 probability:"0.9999999" auction_extension:600}}} liquidity_monitoring_parameters:{target_stake_parameters:{time_window:3600 scaling_factor:10} triggering_ratio:"0.7" auction_extension:1} trading_mode:TRADING_MODE_NO_TRADING state:STATE_CLOSED market_timestamps:{proposed:1689767298132746414 pending:1689767298132746414 open:1689768325822854221 close:1697736004472648864} position_decimal_places:3 linear_slippage_factor:"0.1" quadratic_slippage_factor:"0.1" liquidity_sla_params:{price_range:"0.05" commitment_min_time_fraction:"0.95" performance_hysteresis_epochs:1 sla_competition_factor:"0.9"}} version:1 chain_id:"vega-stagnet1-202307191148" tx_hash:"5588E439410E3B7993531B8A310D7528AF9DE0DBCFFDF1D44DFF916F4AAF0BC5" error:could not insert market into database: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: updating market to SQL store failed
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: code.vegaprotocol.io/vega/datanode/sqlsubscribers.(*MarketUpdated).consume
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]:         /home/runner/work/vega/vega/datanode/sqlsubscribers/market_updated.go:71
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: code.vegaprotocol.io/vega/datanode/sqlsubscribers.(*MarketUpdated).Push
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]:         /home/runner/work/vega/vega/datanode/sqlsubscribers/market_updated.go:61
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).push
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]:         /home/runner/work/vega/vega/datanode/broker/sqlstore_broker.go:360
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).handleEvent
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]:         /home/runner/work/vega/vega/datanode/broker/sqlstore_broker.go:348
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).processBlock
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]:         /home/runner/work/vega/vega/datanode/broker/sqlstore_broker.go:306
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).Receive
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]:         /home/runner/work/vega/vega/datanode/broker/sqlstore_broker.go:146
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).runNode.func6
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]:         /home/runner/work/vega/vega/cmd/data-node/commands/start/node.go:155
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: golang.org/x/sync/errgroup.(*Group).Go.func1
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]:         /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75
Oct 19 17:20:07 n00.stagnet1.vega.rocks visor[3896532]: runtime.goexit
```

### PR DESCRIPTION
**Pull request by guoguojin**
Closes #9853 

The paid liquidity fee stats did not set the EpochSeq, this caused a duplicate key error as EpochSeq is part of the primary key.

### CODE REVIEW

File: core/execution/future/market.go [hunk 1]
```diff
@@ -357,11 +358,12 @@ func (m *Market) OnEpochEvent(ctx context.Context, epoch types.Epoch) {
 	case vegapb.EpochAction_EPOCH_ACTION_START:
 		m.liquidity.UpdateSLAParameters(m.mkt.LiquiditySLAParams)
 		m.liquidity.OnEpochStart(ctx, m.timeService.GetTimeNow(), m.markPrice, m.midPrice(), m.getTargetStake(), m.positionFactor)
+		m.epoch = epoch
```
Comment (wwestgarth) [inline core/execution/future/market.go:361]: Can you also set `m.epoch` in `OnEpochRestore()`? Its used when a node restores from a snapshot, so we can make sure this field is set back again.

File: core/liquidity/v2/snapshot.go [hunk 2]
```diff
@@ -363,7 +363,7 @@ func (e *snapshotV2) serialiseFeeStats() ([]byte, error) {
 		Data: &snapshotpb.Payload_LiquidityV2PaidFeesStats{
 			LiquidityV2PaidFeesStats: &snapshotpb.LiquidityV2PaidFeesStats{
 				MarketId: e.market,
-				Stats:    e.allocatedFeesStats.ToProto(e.market, e.asset),
+				Stats:    e.allocatedFeesStats.ToProto(e.market, e.asset, 0), // I don't think it matters what the epoch is as this is just used for snapshots
```
Comment (EVODelavega) [inline core/liquidity/v2/snapshot.go:366]: Unless the liquidity engine itself tracks the current epoch, it can't really matter. If we do track it, it probably should be included in the snapshot

File: datanode/sqlstore/paid_liquidity_fee_stats_test.go [hunk 3]
```diff
@@ -36,7 +36,7 @@ import (
 
 func TestPaidLiquidityFeesStats_Add(t *testing.T) {
 	t.Run("Should add the stats for the epoch if they do not exist", testAddPaidLiquidityFeesStatsEpochIfNotExists)
-	t.Run("Should return an error if the epoch already exists for the market/asset", testAddPaidLiquidityFeesStatsEpochExists)
+	t.Run("Should not return an error if the epoch already exists for the market/asset", testAddPaidLiquidityFeesStatsEpochExists)
```
Comment (karlem) [inline datanode/sqlstore/paid_liquidity_fee_stats_test.go:39]:
```suggestion
	t.Run("Should not return an error if the epoch already exists for the market/asset/vega time", testAddPaidLiquidityFeesStatsEpochExists)
```

File: core/liquidity/v2/snapshot.go (hunk 2 above)
Comment (guoguojin) [reply core/liquidity/v2/snapshot.go:366]: No, it doesn't track it, we only need it in data node for reporting purposes as far as I am aware.

**Review by jeremyletang — DISMISSED** [review]

**Review by karlem — APPROVED** [review]
