### PR TITLE
SLA related panic

### LINKED ISSUE #9179: [Bug]: panic when amending liquidity provisions
### Problem encountered

```
Aug 23 20:24:18 n01.devnet1.vega.rocks visor[661301]: 2023-08-23T20:24:18.595Z        ERROR        tendermint        consensus/state.go:732        CONSENSUS FAILURE!!!        {"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 761 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x4c
panic({0x30a0700, 0x5bfaed0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
code.vegaprotocol.io/vega/core/execution/common.(*MarketLiquidity).AmendLiquidityProvision(0xc001d3e2d0, {0x3eec990, 0xc00678aa50}, 0xc005ec5640, {0xc0071bba80, 0x40}, {0xc00563a840?, 0x50000c000100400?}, 0x5)
	/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/common/liquidity_provision.go:530 +0x2fe
code.vegaprotocol.io/vega/core/execution/future.(*Market).AmendLiquidityProvision(0x306d800?, {0x3eec990?, 0xc00678aa50?}, 0x40?, {0xc0071bba80?, 0x0?}, {0xc00563a840?, 0xc00581e300?})
	/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/future/liquidity_provision.go:48 +0x89
code.vegaprotocol.io/vega/core/execution.(*Engine).AmendLiquidityProvision(0xc0014e6a00, {0x3eec990, 0xc00678aa50}, 0xc005ec5640, {0xc0071bba80, 0x40}, {0xc00563a840, 0x40})
	/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/engine.go:1210 +0x60f
code.vegaprotocol.io/vega/core/processor.(*App).DeliverAmendLiquidityProvision(0xc000d4a300, {0x3eec990, 0xc00678aa50}, {0x3f0e4b0, 0xc005395240}, {0xc00563a840, 0x40})
	/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/processor/abci.go:1770 +0x256
code.vegaprotocol.io/vega/core/processor.addDeterministicID.func1({0x3eec990, 0xc00678aa50}, {0x3f0e4b0, 0xc005395240})
	/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/processor/abci.go:459 +0x103
code.vegaprotocol.io/vega/core/processor.(*App).SendTransactionResult.func1({0x3eec990, 0xc00678aa50}, {0x3f0e4b0, 0xc005395240})
	/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/processor/abci.go:511 +0x5c
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).DeliverTx(0xc000e00e70, {{0xc002e7c3c0, 0x1db, 0x1db}})
	/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/blockchain/abci/abci.go:140 +0x762
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).DeliverTx(0xc006fae420?, {{0xc002e7c3c0?, 0x20?, 0xc006fae440?}})
	/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/vega/commands/node/app_wrapper.go:37 +0x6c
github.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc00286a480, {{0xc002e7c3c0?, 0xeff524?, 0xc00286a480?}})
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/abci/client/local_client.go:93 +0x105
github.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc008499060?, {{0xc002e7c3c0?, 0x20?, 0xb?}})
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/proxy/app_conn.go:85 +0x26
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x3eeaaf0?, 0xc000f6ef50}, {0x3efe020, 0xc00288a990}, 0xc0034021e0, {0x3f0f158, 0xc001506048}, 0x33a1?)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:320 +0x6d9
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc001fbedb8, 0x7}}, {0xc0029d97e0, 0x19}, 0x1, 0x33a1, {{0xc00852e920, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc00151b880, 0x33a2)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1661 +0xafd
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc00151b880, 0x33a2)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1570 +0x2ff
github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1505 +0xaa
github.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc00151b880, 0x33a2, 0x0)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1543 +0xccf
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc00151b880, 0xc002fe41e0, {0xc00289ed20, 0x28})
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2165 +0x18dc
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc00151b880, 0xc002fe41e0, {0xc00289ed20?, 0xc001341c08?})
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x2c
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc00151b880, {{0x3ec93a0, 0xc005d82008}, {0xc00289ed20, 0x28}})
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x3ff
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc00151b880, 0x0)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x3f0
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0x12d
"} 
```

### Observed behaviour

node backup on n03.devnet1.vega.rocks in /home/vega/bk_2023_08_23_panic

### Expected behaviour

Not to panic

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

develop

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by karlem**
Close #9179

### CODE REVIEW

File: core/execution/common/liquidity_provision.go [hunk 1]
```diff
@@ -505,29 +505,35 @@ func (m *MarketLiquidity) AmendLiquidityProvision(
...
-	lp := m.liquidityEngine.LiquidityProvisionByPartyID(party)
-	if lp == nil && pendingAmendment == nil {
-		return fmt.Errorf("cannot edit liquidity provision from a non liquidity provider party (%v)", party)
+	pendingAmendment := m.liquidityEngine.PendingProvisionByPartyID(party)
+	currentProvision := m.liquidityEngine.LiquidityProvisionByPartyID(party)
+
+	provisionToCopy := currentProvision
+	if currentProvision == nil {
+		if pendingAmendment == nil {
+			return fmt.Errorf("cannot edit liquidity provision from a non liquidity provider party (%v)", party)
```
Comment (jeremyletang) [inline core/execution/common/liquidity_provision.go:518]: shouldn't we even panic here? that sounds impossible to happen or a bug if it would seeing the call on line 508?

File: core/execution/common/liquidity_provision.go [hunk 2]
```diff
@@ -546,8 +552,8 @@ func (m *MarketLiquidity) AmendLiquidityProvision(
 
 		proposedCommitmentVariation = pendingAmendment.CommitmentAmount.ToDecimal().Sub(lpa.CommitmentAmount.ToDecimal())
 	} else {
-		if lp != nil {
-			proposedCommitmentVariation = lp.CommitmentAmount.ToDecimal().Sub(lpa.CommitmentAmount.ToDecimal())
+		if currentProvision != nil {
```
Comment (jeremyletang) [inline core/execution/common/liquidity_provision.go:555]: for all those from here to line 590, did you expect to use currentProvision or provisionToCopy?

Comment (karlem) [reply core/execution/common/liquidity_provision.go:555]: Current provision mate.

File: core/execution/common/liquidity_provision.go (hunk 1 above)
Comment (karlem) [reply core/execution/common/liquidity_provision.go:518]: perhaps we should yeah

File: core/execution/common/liquidity_provision.go (hunk 2 above)
Comment (jeremyletang) [reply core/execution/common/liquidity_provision.go:558]: cool cool

**Review by jeremyletang — DISMISSED** [review]

**Review by jeremyletang — APPROVED** [review]
