### PR TITLE
fix: make id queries consitent

### LINKED ISSUE #5709: Querying by id should be consistent and functional across all top level models
# Problem encountered

* assets query errors on GQL if the asset id is not present
* proposal query errors on GQL if the asset id is not present

There are also some inconsistencies:
* asset should be queried through `id` not assetId to be consistent with markets, parties and proposals
* node id should be of type `ID` not `string`

# Observed behaviour
* assets query errors on GQL if the asset id is not present
* proposal query errors on GQL if the asset id is not present

# Expected behaviour

* assets query does not error on GQL if the asset id is not present and instead returns null
* proposals query does not error on GQL if the asset id is not present and instead returns null

```
query ($guess: ID!) {
  asset (assetId: $guess) {
    id
  }
  proposal (id: $guess) {
    id
  }
}
```

```
{
  "guess": "a42f27fff304646a096ad77236927db723f004fd4b23a2616e3cb0593ebf80a0"
}
```

```
{
  "errors": [
    {
      "message": "rpc error: code = NotFound desc = NotFound error",
      "path": [
        "asset"
      ]
    },
    {
      "message": "rpc error: code = Internal desc = Internal error",
      "path": [
        "proposal"
      ]
    }
  ],
  "data": null
}
```

### PR DESCRIPTION
**Pull request by AnExsomnis**
close #5709

### CODE REVIEW

File: datanode/api/trading_data_v2.go [hunk 1]
```diff
@@ -1418,11 +1418,11 @@ func (t *tradingDataServiceV2) ListWithdrawals(ctx context.Context, req *v2.List
 // -- Assets --.
 func (t *tradingDataServiceV2) GetAsset(ctx context.Context, req *v2.GetAssetRequest) (*v2.GetAssetResponse, error) {
 	defer metrics.StartAPIRequestAndTimeGRPC("GetAssetV2")()
-	if req == nil || req.AssetId == "" {
+	if req == nil || req.Id == "" {
```
Comment (pscott31) [inline datanode/api/trading_data_v2.go:1421]: Did you mean to leave this one in?

File: protos/sources/data-node/api/v1/trading_data.proto [hunk 2]
```diff
@@ -731,7 +731,7 @@ message AccountsSubscribeRequest {
   // Party identifier
```
Comment (pscott31) [inline protos/sources/data-node/api/v1/trading_data.proto:731]: These are sensible changes but I think perhaps we should leave them alone as this API is about to be deprecated anyway and this will probably break e.g. the trading bots. It's make the V2 API the perfect one and then people can change as they migrate

File: protos/sources/data-node/api/v2/trading_data.proto [hunk 3]
```diff
@@ -1169,7 +1169,7 @@ message OracleDataConnection {
 
 // -- Markets --
 message GetMarketRequest {
-    string market_id = 1;
+    string id = 1;
```
Comment (pscott31) [inline protos/sources/data-node/api/v2/trading_data.proto:1172]: Did you mean to leave this rename in?

File: protos/sources/data-node/api/v2/trading_data.proto [hunk 4]
```diff
@@ -1381,15 +1381,15 @@ message WithdrawalsConnection {
 
 // -- Assets --
 message GetAssetRequest {
-    string asset_id = 1;
+    string id = 1;
```
Comment (pscott31) [inline protos/sources/data-node/api/v2/trading_data.proto:1384]: ditto

File: protos/sources/data-node/api/v2/trading_data.proto [hunk 5]
```diff
@@ -1381,15 +1381,15 @@ message WithdrawalsConnection {
...
 }
 
 message GetAssetResponse {
     vega.Asset asset = 1;
 }
 
 message ListAssetsRequest {
-    optional string asset_id = 1;
+    optional string id = 1;
```
Comment (pscott31) [inline protos/sources/data-node/api/v2/trading_data.proto:1392]: ditto

File: protos/sources/data-node/grpc-rest-bindings.yml [hunk 6]
```diff
@@ -217,7 +217,7 @@ http:
     - selector: datanode.api.v2.TradingDataService.ListTrades
       get: "/api/v2/trades"
     - selector: datanode.api.v2.TradingDataService.GetMarket
-      get: "/api/v2/market/{market_id}"
+      get: "/api/v2/market/{id}"
```
Comment (pscott31) [inline protos/sources/data-node/grpc-rest-bindings.yml:220]: ditto

File: protos/sources/data-node/grpc-rest-bindings.yml [hunk 7]
```diff
@@ -239,7 +239,7 @@ http:
     - selector: datanode.api.v2.TradingDataService.ListWithdrawals
       get: "/api/v2/withdrawals"
     - selector: datanode.api.v2.TradingDataService.GetAsset
-      get: "/api/v2/asset/{asset_id}"
+      get: "/api/v2/asset/{id}"
```
Comment (pscott31) [inline protos/sources/data-node/grpc-rest-bindings.yml:242]: ditto

File: datanode/api/trading_data_v2.go (hunk 1 above)
Comment (AnExsomnis) [reply datanode/api/trading_data_v2.go:1421]: No,
One of the issue points was to make the objects able to be queried by ID, not by "objectId"; and specifically asset needed to become -> Asset { Id: ID } instead of Asset { AssetId: String }, etc

File: protos/sources/data-node/api/v2/trading_data.proto (hunk 3 above)
Comment (AnExsomnis) [reply protos/sources/data-node/api/v2/trading_data.proto:1172]: No, I meant to make it consistent with asset, node, proposal, party - in their own objects they are all queried by `Id`, not by `ObjectId`

File: protos/sources/data-node/api/v2/trading_data.proto (hunk 4 above)
Comment (AnExsomnis) [reply protos/sources/data-node/api/v2/trading_data.proto:1384]: Yes, this is the same as the reasoning in https://github.com/vegaprotocol/vega/pull/5895#discussion_r948796331
in the task it says:
`https://github.com/vegaprotocol/vega/pull/5895#discussion_r948796331`

File: protos/sources/data-node/api/v2/trading_data.proto (hunk 5 above)
Comment (AnExsomnis) [reply protos/sources/data-node/api/v2/trading_data.proto:1392]: Please see https://github.com/vegaprotocol/vega/pull/5895#discussion_r948798892

File: protos/sources/data-node/grpc-rest-bindings.yml (hunk 6 above)
Comment (AnExsomnis) [reply protos/sources/data-node/grpc-rest-bindings.yml:220]: Same as reasoning here https://github.com/vegaprotocol/vega/pull/5895#discussion_r948798892 - made the market query consistent

File: datanode/gateway/graphql/schema.graphql [hunk 8]
```diff
@@ -1906,7 +1902,7 @@ type Party {
   accounts(
     "Market ID - specify what market accounts for the party to return"
     marketId: ID
-    "Asset (ETH, DAI etc)"
+    "Asset symbol (ETH, DAI etc)"
```
Comment (pscott31) [inline datanode/gateway/graphql/schema.graphql:1905]: Is the schema fibbing here because in this query 'asset' is an object not a string...
{  parties {  accounts{    asset {      id    }   }  } }

File: datanode/gateway/graphql/schema.graphql [hunk 9]
```diff
@@ -1916,7 +1912,7 @@ type Party {
   accountsConnection(
     "Market ID - specify what market accounts for the party to return"
     marketId: ID
-    "Asset (ETH, DAI etc)"
+    "Asset symbol (ETH, DAI etc)"
```
Comment (pscott31) [inline datanode/gateway/graphql/schema.graphql:1915]: ditto

File: datanode/gateway/graphql/schema.graphql [hunk 10]
```diff
@@ -2019,7 +2015,7 @@ type Party {
 
   "Return individual reward information"
   rewards(
-    "An optional asset"
+    "An optional asset symbol"
```
Comment (pscott31) [inline datanode/gateway/graphql/schema.graphql:2018]: ditto

File: datanode/gateway/graphql/schema.graphql [hunk 11]
```diff
@@ -2030,15 +2026,15 @@ type Party {
...
+    "An asset symbol (optional)"
     asset: String
     "Cursor pagination information"
     pagination: Pagination
   ): RewardsConnection
 
   "Return net reward information"
   rewardSummaries(
-    "An asset (optional)"
+    "An asset symbol (optional)"
```
Comment (pscott31) [inline datanode/gateway/graphql/schema.graphql:2037]: ditto

File: datanode/gateway/graphql/schema.graphql [hunk 12]
```diff
@@ -2339,7 +2335,7 @@ type Erc20WithdrawalApproval {
 type Withdrawal {
   "The Vega internal ID of the withdrawal"
   id: ID!
-  "The PartyID (public key) initiating the withdrawal"
+  "The Party (public key) initiating the withdrawal"
```
Comment (pscott31) [inline datanode/gateway/graphql/schema.graphql:2338]: super minor but could remove (public key)

File: datanode/gateway/graphql/schema.graphql [hunk 13]
```diff
@@ -2383,7 +2379,7 @@ enum WithdrawalStatus {
 type Deposit {
   "The Vega internal ID of the deposit"
   id: ID!
-  "The PartyID initiating the deposit"
+  "The initiating the deposit"
```
Comment (pscott31) [inline datanode/gateway/graphql/schema.graphql:2382]: 'The party initiating the deposit' ?

File: datanode/gateway/graphql/schema.graphql (hunk 8 above)
Comment (pscott31) [reply datanode/gateway/graphql/schema.graphql:1905]: Oh I am being dumb - this is the query arg not the return type!

File: datanode/gateway/graphql/schema.graphql (hunk 9 above)
Comment (pscott31) [inline datanode/gateway/graphql/schema.graphql:1915]: ditto

File: datanode/gateway/graphql/schema.graphql [hunk 14]
```diff
@@ -2030,15 +2026,15 @@ type Party {
   ): [Reward] @deprecated(reason: "Use rewardsConnection instead")
 
   rewardsConnection(
-    "An asset (optional)"
+    "An asset symbol (optional)"
```
Comment (pscott31) [inline datanode/gateway/graphql/schema.graphql:2029]: ditto

File: datanode/gateway/graphql/schema.graphql (hunk 11 above)
Comment (pscott31) [inline datanode/gateway/graphql/schema.graphql:2037]: ditto

File: datanode/gateway/graphql/schema.graphql [hunk 15]
```diff
@@ -3491,7 +3486,7 @@ type RewardSummary {
     last: Int): [Reward] @deprecated(reason: "Use rewardsConnection instead")
   "List of individual reward payouts, ordered by epoch"
   rewardsConnection(
-    "An optional asset"
+    "An optional asset symbol"
```
Comment (pscott31) [inline datanode/gateway/graphql/schema.graphql:3489]: ditto

**Review by pscott31 — COMMENTED** [review]
Looks good apart from the confusion about whether asset symbols or IDs are being used..

File: datanode/gateway/graphql/schema.graphql (hunk 12 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/schema.graphql]: Addressed here https://github.com/vegaprotocol/vega/pull/5895/commits/793f57749039ae2385cf429e737f2973ec75a55d#diff-be016f833f94c6069e96beb4873414c55bdfb7af1924c9c1b90eb709304ff90eR2338
thanks!

File: datanode/gateway/graphql/schema.graphql (hunk 13 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/schema.graphql]: Addresssed here https://github.com/vegaprotocol/vega/pull/5895/commits/793f57749039ae2385cf429e737f2973ec75a55d#diff-be016f833f94c6069e96beb4873414c55bdfb7af1924c9c1b90eb709304ff90eR2382
Thanks!

File: datanode/gateway/graphql/schema.graphql (hunk 9 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/schema.graphql]: Please see https://github.com/vegaprotocol/vega/pull/5895#discussion_r949150257

File: datanode/gateway/graphql/schema.graphql (hunk 14 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/schema.graphql]: Please see https://github.com/vegaprotocol/vega/pull/5895#discussion_r949150257

File: datanode/gateway/graphql/schema.graphql (hunk 11 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/schema.graphql]: Please see https://github.com/vegaprotocol/vega/pull/5895#discussion_r949150257

File: datanode/gateway/graphql/schema.graphql (hunk 15 above)
Comment (AnExsomnis) [reply datanode/gateway/graphql/schema.graphql]: Please see https://github.com/vegaprotocol/vega/pull/5895#discussion_r949150257

**Review by pscott31 — APPROVED** [review]
Looks good to me, I guess it's just the front end who need to be OK with the changes as a couple are breaking :)

**Review by mattrussell36 — APPROVED** [review]
