### PR TITLE
Fix/transfers api bugs

### LINKED ISSUE #10683: [Bug]: GraphQL transfers API filter by status is broken
### Problem encountered

Specifying any `status` in the `transfersConnection` query returns an error

### Observed behaviour

```graphql
{
  transfersConnection(status: STATUS_PENDING) {
    edges {
      node {
        transfer {
          id
        }
      }
    }
  }
}
```

returns

```json 
{
  "errors": [
    {
      "message": "unmarshaller not implemented as this API is query only",
      "path": [
        "transfersConnection",
        "status"
      ]
    }
  ],
  "data": {
    "transfersConnection": null
  }
}
```

### Expected behaviour

Transfers

### Steps to reproduce

```bash
1. Open https://api.testnet.vega.rocks/graphql/#
2. With the query above
```

### Software version

0.74.x

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #10685: [Bug]: REST query list transfers has no default page size, returns too much data
### Problem encountered

https://docs.vega.xyz/testnet/api/rest/data-v2/trading-data-service-list-transfers - this endpoint should have a default page size (50?) so that it doesn't return too much data.

### Observed behaviour

```sh
curl -L -X GET 'https://api.n00.testnet.vega.rocks/api/v2/transfers?status=STATUS_PENDING'
```

```json
{"code":8,"message":"grpc: received message larger than max (25836259 vs. 20971520)","details":[]}
```

### Expected behaviour

I can see transfers

### Steps to reproduce

```bash
1. Curl `https://api.n00.testnet.vega.rocks/api/v2/transfers`
2. Observe slowness as it tries to query all the transfers
3. Observe an error
```

### Software version

0.74.x

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by guoguojin**
Closes #10683 
Closes #10685

### CODE REVIEW

File: datanode/entities/pagination.go [hunk 1]
```diff
@@ -25,7 +25,11 @@ import (
 )
 
 const (
-	DefaultPageSize int32 = 1000
+	// DefaultPageSize is the default number of records that will be returned if no paging constraints
+	// are provided in an API request that supports pagination.
+	// If we set this too large, we get errors relating to gRPC message size so for now set it to
+	// something small and if users want more, they should set the appropriate limit in their request.
+	DefaultPageSize int32 = 50
```
Comment (jeremyletang) [inline datanode/entities/pagination.go:32]: Can we confirm with frontend this isn't gonna break anything before merging?

Comment (guoguojin) [reply datanode/entities/pagination.go:32]: I've dropped a message in Slack to get some input from the FE team https://vegaprotocol.slack.com/archives/C8WS7M50E/p1708007031793479

Comment (guoguojin) [reply datanode/entities/pagination.go:32]: After discussions with the FE team, we are just going to reduce the page size for the transfers API for now and leave the default page size for other APIs.

Once the Palazzo release has gone out, we can start looking at reducing the default page size to something smaller as we will have more time to check for breaks.

**Review by jeremyletang — APPROVED** [review]
