### PR TITLE
fix: remove position from position engine when closed

### LINKED ISSUE #6849: Remove positions from position engine when party close positions
As of now we keep position with a 0 size and potential buy / sell when a position is closed. this needs fixed.

### PR DESCRIPTION
**Pull request by jeremyletang**
close #6849

### CODE REVIEW

**Comment by ze97286** [comment]
isn't this fixing the snapshot issue that @wwestgarth found?

**Comment by jeremyletang** [comment]
> isn't this fixing the snapshot issue that @wwestgarth found?

Nope @EVODelavega is on that one

**Comment by ze97286** [comment]
> > isn't this fixing the snapshot issue that @wwestgarth found?
> 
> Nope @EVODelavega is on that one

I don't know what @EVODelavega is fixing but it seems very relevant to the description [here](https://github.com/vegaprotocol/vega/issues/6831#issue-1449951013) - i.e. the position engine was keeping zero position while the settlement engine was removing them, which would cause the restored node to have them back in the settlement engine. May be other things in play but I think it may be relevant to what you're fixing here no?

**Comment by jeremyletang** [comment]
> > > isn't this fixing the snapshot issue that @wwestgarth found?
> > 
> > 
> > Nope @EVODelavega is on that one
> 
> I don't know what @EVODelavega is fixing but it seems very relevant to the description [here](https://github.com/vegaprotocol/vega/issues/6831#issue-1449951013) - i.e. the position engine was keeping zero position while the settlement engine was removing them, which would cause the restored node to have them back in the settlement engine. May be other things in play but I think it may be relevant to what you're fixing here no?

Alright, I see. So I think reading the ticket both our tickets are two side of a same coin. This branch is actually making sure that the positions in the position engine, which are being closed, are not staying in the position engine. Before that the position will stay with a size of zero and would be used during MTM and would send empty events. Elias PR (https://github.com/vegaprotocol/vega/pull/6890) Is actually changing the storage of the settlement engine which had been broken since the last changes in the MTM.

File: core/settlement/engine.go [hunk 1]
```diff
@@ -476,6 +476,13 @@ func (e *Engine) AddPosition(party string, evt events.MarketPosition) {
 	_ = e.getCurrentPosition(party, evt)
 }
 
+func (e *Engine) HasPosition(party string) bool {
+	_, okPos := e.pos[party]
+	_, okTrades := e.trades[party]
```
Comment (ze97286) [inline core/settlement/engine.go:481]: I don't understand the okTrades - this would return true in all cases you ever had a position and were not distressed, even if you don't hold it anymore. what is the purpose of it?

File: core/execution/market_test.go [hunk 2]
```diff
@@ -6412,6 +6412,7 @@ func Test3008And3007CancelLiquidityProvision(t *testing.T) {
 				found = append(found, evt.LedgerMovements()...)
 			}
 		}
+		// fmt.Printf("%#v\n", found[1].Entries[0].Type)
```
Comment (ze97286) [inline core/execution/market_test.go:6415]: might as well remove

File: core/settlement/engine.go (hunk 1 above)
Comment (jeremyletang) [reply core/settlement/engine.go:481]: well it's not always that there's a position AND trades during the MTM window. you could have a position (which in that case was registered with a potential position at the time) but 0 trades. but at the end of the window, the party might have cancelled their orders and no trades happened. At that point the position engine might have deleted the position as it's of size 0, and no orders are left in the book.

File: core/execution/market_test.go (hunk 2 above)
Comment (jeremyletang) [reply core/execution/market_test.go:6415]: correct.

File: core/execution/market.go [hunk 3]
```diff
@@ -1271,22 +1286,33 @@ func (m *Market) releaseExcessMargin(ctx context.Context, positions ...events.Ma
...
+		// do not remove them for now
+		if m.settlement.HasPosition(pos.Party()) {
+			continue
+		}
+
 		// now check if all buy/sell/size are 0
 		if pos.Buy() != 0 || pos.Sell() != 0 || pos.Size() != 0 || !pos.VWBuy().IsZero() || !pos.VWSell().IsZero() {
 			// position is not 0, nothing to release surely
-			return
+			continue
```
Comment (ze97286) [inline core/execution/market.go:1298]: good catch.

**Review by ze97286 — DISMISSED** [review]

**Review by EVODelavega — DISMISSED** [review]

**Review by ValentinTrinque — APPROVED** [review]

**Review by ze97286 — APPROVED** [review]
