### PR TITLE
fix: include block hash/height in stake linking

### LINKED ISSUE #5977: Stake REST API always returns blockheight and blockTIme as 0
Comparing core events content with REST API content for stake endpoint

We see that the event data contains a block height and time
```
{"id":"11120-3","block":"FE71FD361F8E27A96B9670A433D2F3FD021F1E46B76CBF496553FBE4D6216F7A","type":"BUS_EVENT_TYPE_STAKE_LINKING","stakeLinking":{"id":"778404ef8e3339123a26067053ea732e12df9d8c89366ec3d66064698d4ef948","type":"TYPE_LINK","ts":"1661338265","party":"2f2e15133c9582ae8665929954275f8fe1d56e30fbc6371d639003f5bd0b3c3c","amount":"1000000000000000001","status":"STATUS_ACCEPTED","finalizedAt":"1661338274986253000","txHash":"0xa3fd024b716a23127ca4ffb4b26cd08b3c0fd20707fa46054ce435c742b68128","blockHeight":"7655","blockTime":"1661338265","logIndex":"2","ethereumAddress":"0xEe7D375bcB50C26d52E1A4a472D8822A2A22d94F"},"version":1,"chainId":"test-chain-17he7g","txHash":"FE71FD361F8E27A96B9670A433D2F3FD021F1E46B76CBF496553FBE4D6216F7A"}
```

Whereas the equivalent REST API response (for same trx hash) does not

e.g. http://localhost:3029/parties/2f2e15133c9582ae8665929954275f8fe1d56e30fbc6371d639003f5bd0b3c3c/stake

```
{
  "currentStakeAvailable": "1000000000000000001",
  "stakeLinkings": [
    {
      "id": "778404ef8e3339123a26067053ea732e12df9d8c89366ec3d66064698d4ef948",
      "type": "TYPE_LINK",
      "ts": "1661338265",
      "party": "2f2e15133c9582ae8665929954275f8fe1d56e30fbc6371d639003f5bd0b3c3c",
      "amount": "1000000000000000001",
      "status": "STATUS_ACCEPTED",
      "finalizedAt": "1661338274986253000",
      "txHash": "0xa3fd024b716a23127ca4ffb4b26cd08b3c0fd20707fa46054ce435c742b68128",
      "blockHeight": "0",
      "blockTime": "0",
      "logIndex": "2",
      "ethereumAddress": "0xEe7D375bcB50C26d52E1A4a472D8822A2A22d94F"
    }
  ]
}%
```

Expected block height and time to match core event content for this stake linking trx.

### PR DESCRIPTION
**Pull request by ze97286**
Closes #5977

### CODE REVIEW

File: core/execution/engine.go [hunk 1]
```diff
@@ -318,9 +318,7 @@ func (e *Engine) submitOrRestoreMarket(ctx context.Context, marketConfig *types.
 
 // UpdateMarket will update an existing market configuration.
 func (e *Engine) UpdateMarket(ctx context.Context, marketConfig *types.Market) error {
-	if e.log.IsDebug() {
-		e.log.Debug("update market", logging.Market(*marketConfig))
-	}
+	e.log.Info("update market", logging.Market(*marketConfig))
```
Comment (ze97286) [inline core/execution/engine.go:321]: unrelated but nice to have

Comment (pscott31) [inline core/execution/engine.go:321]: Did you mean to leave this change in?

Comment (ze97286) [reply core/execution/engine.go:321]: https://github.com/vegaprotocol/vega/pull/6039#discussion_r960906752

**Review by jeremyletang — APPROVED** [review]

**Review by pscott31 — APPROVED** [review]
