### PR TITLE
fix: handle isolated margin amends properly and fix mishandled fees on failure

### LINKED ISSUE #10493: [Bug]: Panic in the core on 0.74.preview.6
### Problem encountered

The network stopped producting blocks in the slip and slide incentive

```
Error originating from there tho:
PANIC core.protocol.execution        future/market.go:3776        unable to submit order        {"error": "OrderError: Order Removal Failure"}
```

### Observed behaviour

network stopped producing blocks 

### Expected behaviour

network runs

### Software version

0.74.preview.6

### Relevant log output

     CONSENSUS FAILURE!!!        {"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 23058 [running]:\nruntime/debug.Stack()\n\t/home/daniel/.asdf/installs/golang/1.21.5/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:800 +0x46\npanic({0x5103820?, 0x830cb80?})\n\t/home/daniel/.asdf/installs/golang/1.21.5/go/src/runtime/panic.go:914 +0x21f\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).handleConfirmation(0xc0abbc8300, {0x612ca58, 0xc05d434570}, 0x0, 0x0)\n\t/home/daniel/www/vega/core/execution/future/market.go:2496 +0x45\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).orderCancelReplace.func1()\n\t/home/daniel/www/vega/core/execution/future/market.go:3701 +0x57\npanic({0x4ec2ce0?, 0xc05b0ea740?})\n\t/home/daniel/.asdf/installs/golang/1.21.5/go/src/runtime/panic.go:914 +0x21f\ngo.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc042447da0?})\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x54\ngo.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc01de45ad0, {0xc04d4a3500, 0x1, 0x1})\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec\ngo.uber.org/zap.(*Logger).Panic(0xc0abbc8300?, {0x595c7d3?, 0xc05d434570?}, {0xc04d4a3500, 0x1, 0x1})\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/go.uber.org/zap@v1.25.0/logger.go:258 +0x51\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).orderCancelReplace(0xc0abbc8300, {0x612ca58?, 0xc05d434570}, 0xc044257ad0, 0xc03131c9c0)\n\t/home/daniel/www/vega/core/execution/future/market.go:3776 +0xd1f\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).amendOrder(0xc0abbc8300, {0x612ca58, 0xc05d434570}, 0xc031301c20, {0xc03f972b80, 0x40})\n\t/home/daniel/www/vega/core/execution/future/market.go:3609 +0x1bb3\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).AmendOrderWithIDGenerator(0xc0abbc8300, {0x612ca58?, 0xc05d434570}, 0x40?, {0xc03f972b80, 0x40}, {0x60fc220?, 0xc03fd49d70?})\n\t/home/daniel/www/vega/core/execution/future/market.go:3321 +0x1b7\ncode.vegaprotocol.io/vega/core/execution.(*Engine).AmendOrder(0xc000b682c0, {0x612ca58, 0xc05d434570}, 0xc031301c20, {0xc03f972b80, 0x40}, {0x60fc220, 0xc03fd49d70})\n\t/home/daniel/www/vega/core/execution/engine.go:1104 +0x3a4\ncode.vegaprotocol.io/vega/core/processor.(*App).DeliverAmendOrder(0xc000f13180, {0x612ca58, 0xc05d434570}, {0x61596e0, 0xc03ac55740}, {0xc01ffa2640, 0x40})\n\t/home/daniel/www/vega/core/processor/abci.go:1760 +0x29b\ncode.vegaprotocol.io/vega/core/processor.NewApp.addDeterministicID.func25({0x612ca58, 0xc05d434570}, {0x61596e0, 0xc03ac55740})\n\t/home/daniel/www/vega/core/processor/abci.go:539 +0x5e\ncode.vegaprotocol.io/vega/core/processor.NewApp.(*App).SendTransactionResult.func26({0x612ca58, 0xc05d434570}, {0x61596e0?, 0xc03ac55740?})\n\t/home/daniel/www/vega/core/processor/abci.go:602 +0x5d\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc00065a480, {0xc001044558?, 0x2686d79?}, 0xc0312029c0)\n\t/home/daniel/www/vega/core/blockchain/abci/abci.go:173 +0x622\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0x4f3de20?, {0x612cb38?, 0x882b720?}, 0x7f8b03f2a878?)\n\t/home/daniel/www/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25\ngithub.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0xc02f4c34c0?, {0x612cb38?, 0x882b720?}, 0xc0?)\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/abci/client/local_client.go:185 +0xd0\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0xc054000ae0, {0x612cb38, 0x882b720}, 0x1?)\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:104 +0x16d\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc03d48fb10, 0x7}}, {0xc0aa34c900, 0x1c}, 0x1, 0x155eb19, {{0xc05adc1d60, ...}, ...}, ...}, ...)\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/state/execution.go:213 +0x622\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc055880a80, 0x155eb1a)\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1770 +0xb7d\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc055880a80, 0x155eb1a)\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1681 +0x2f6\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1616 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc055880a80, 0x155eb1a, 0x0)\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1654 +0xc5b\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc055880a80, 0xc030b6c340, {0xc023e76fc0, 0x28})\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2324 +0x1d4d\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc055880a80, 0xc030b6c340, {0xc023e76fc0?, 0xc001045c08?})\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2056 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc055880a80, {{0x6103240, 0xc0a9236c70}, {0xc023e76fc0, 0x28}})\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:928 +0x3ce\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc055880a80, 0x0)\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:835 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 1939\n\t/home/daniel/.asdf/installs/golang/1.21.5/packages/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:397 +0x10c\n"}

### PR DESCRIPTION
**Pull request by jeremyletang**
close https://github.com/vegaprotocol/vega/issues/10493

DO NOT MERGE - this is still not right.

### CODE REVIEW

File: core/risk/isolated_margin.go [hunk 1]
```diff
@@ -322,37 +328,72 @@ func getIsolatedMarginTransfersOnPositionChange(party, asset string, trades []*t
...
+				return []*types.Transfer{{
+					Owner: party,
+					Type:  tp,
+					Amount: &types.FinancialAmount{
+						Asset:  asset,
+						Amount: marginToAdd,
+					},
+					MinAmount: marginToAdd,
+				}}
 			} else {
```
Comment (EVODelavega) [inline core/risk/isolated_margin.go:348]: is this else still needed? Looks to me like the `if` condition above returns

File: core/risk/isolated_margin.go [hunk 2]
```diff
@@ -322,37 +328,72 @@ func getIsolatedMarginTransfersOnPositionChange(party, asset string, trades []*t
...
+						Owner: party,
+						Type:  types.TransferTypeIsolatedMarginLow,
+						Amount: &types.FinancialAmount{
+							Asset:  asset,
+							Amount: marginToAdd,
+						},
+						MinAmount: marginToAdd,
+					}}
+				} else {
+					generalTopUp := num.UintZero().Sub(marginToAdd, orderMarginBalance)
```
Comment (EVODelavega) [inline core/risk/isolated_margin.go:360]: same here, `if` returns, the `else` doesn't quite make sense

**Review by EVODelavega — APPROVED** [review]
