### PR TITLE
fix: Fix proposals GQL API filter

### LINKED ISSUE #6287: [data node] GraphQL: ProposalsConnection proposalType filter does not filter by proposal type
See #6122 - this is the same, but for the other filter option

```graphql
{
  proposalsConnection(proposalType:TYPE_NEW_MARKET) {
    edges {
      node {
        id
        datetime
        state
        rationale {
          title
        }
        terms {
          change {
            ... on NewMarket {
              metadata
            }
          }
        }
      }
    }
  }
}
```

Returns:
```json
{
  "data": {
    "proposalsConnection": {
      "edges": null
    }
  }
}
```

While removing proposalType returns:
```json

{
  "data": {
    "proposalsConnection": {
      "edges": [
        {
          "node": {
            "id": "c7b3fe4a1c055f6338753e18475fb35629d001a49ec470ab9c390aefbd2c8070",
            "datetime": "2022-09-23T06:06:45.132344Z",
            "state": "STATE_ENACTED",
            "rationale": {
              "title": "AAVEDAI market"
            },
            "terms": {
              "change": {
                "metadata": [
                  "formerly:2839D9B2329C9E70",
                  "base:AAVE",
                  "quote:DAI",
                  "class:fx/crypto",
                  "monthly",
                  "sector:defi"
                ]
              }
            }
          }
        },
        {

``` 

Item one should show up.

### PR DESCRIPTION
**Pull request by zale144**
Closes #6287

### CODE REVIEW

File: datanode/sqlstore/proposals.go [hunk 1]
```diff
@@ -266,7 +267,7 @@ func (ps *Proposals) Get(ctx context.Context,
 	}
 
 	if proposalType != nil {
-		conditions = append(conditions, fmt.Sprintf("terms ? %s", nextBindVar(&args, *proposalType)))
+		conditions = append(conditions, fmt.Sprintf("terms ? %s", nextBindVar(&args, proposalType.String())))
```
Comment (wwestgarth) [inline datanode/sqlstore/proposals.go:270]: Maybe theres already one that exists and I've just not see it, but can we have a test in `proposal_test.go` for filtering on proposal test?

**Review by wwestgarth — APPROVED** [review]
