### PR TITLE
Investigate panic with cumlativeVolumeAndPrice

### LINKED ISSUE #6406: panic: Failed to extract orders as not enough volume within price limits
Running RL training from https://github.com/vegaprotocol/vega-market-sim/commit/145fbb0c9bb1e9813dd6f018c13b8b01e56b2c29 with 
```
python ./vega_sim/reinforcement/run_rl_agent.py --rl-max-it 200
```

This is what we fail with:
```
panic: Failed to extract orders as not enough volume within price limits

goroutine 5117594 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x1400e69a540, {0x1400d553200, 0x2, 0x2})
        /Users/davidsiska/go/pkg/mod/go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x30c
go.uber.org/zap.(*Logger).Panic(0xe1dde?, {0x101b9fe27?, 0x0?}, {0x1400d553200, 0x2, 0x2})
        /Users/davidsiska/go/pkg/mod/go.uber.org/zap@v1.21.0/logger.go:230 +0x54
code.vegaprotocol.io/vega/core/matching.(*OrderBookSide).ExtractOrders(0x1400f686090, 0x140169dbfa0, 0x64, 0x0)
        /Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/matching/side.go:205 +0x600
code.vegaprotocol.io/vega/core/matching.(*OrderBook).GetIndicativeTrades(0x140113a6900)
```

The whole node error log:  [node.err.txt](https://github.com/vegaprotocol/vega/files/9708947/node.err.txt)

Last 20k lines from node output log: [node.out.tail-n20000.txt](https://github.com/vegaprotocol/vega/files/9708948/node.out.tail-n20000.txt)

### PR DESCRIPTION
**Pull request by jeremyletang**
fix: reset minPrice and maxPrice once the cumulative volume are built if recalculated
 
close #6406

### CODE REVIEW

File: core/matching/orderbook.go [hunk 1]
```diff
@@ -882,13 +867,21 @@ func (b *OrderBook) DeleteOrder(
...
+	// here we use specifically the order which was in the book, just in case
+	// the order passed in would be wrong
+	// TODO: refactor this better, we should never need to pass in more that IDs there
+	// because by using the order passed in remain and price, we could use
+	// values which have been amended previously... (e.g: amending an order which
+	// cancel the order if it expires it
 	if b.auction {
 		b.indicativePriceAndVolume.RemoveVolumeAtPrice(
-			order.Price, order.Remaining, order.Side)
+			dorder.Price, dorder.Remaining, dorder.Side)
```
Comment (EVODelavega) [inline core/matching/orderbook.go:884]: what is `dorder`?

**Review by ze97286 — DISMISSED** [review]

**Review by pscott31 — DISMISSED** [review]

**Review by EVODelavega — DISMISSED** [review]

**Review by EVODelavega — APPROVED** [review]
