### PR TITLE
Fix games stats view

### LINKED ISSUE #10532: Teams vs individual rewards seem to be misbehaving a bit
Rewards API shows this 

Which indicates the reward is associated to a TEAM

```
"node": {
"assetId": "8013bcd403e421ff01b99f0fee7747e3de15601acc9d085f9508f7b1ea8025bd",
"partyId": "e1402dc9f12fc80d9168d0ed40fc2aed9705fac9b75723a6212d5046b6ec4223",
"epoch": "12555",
"amount": "155056265",
"percentageOfTotal": "25.84271083333333",
"receivedAt": "1706801075841883000",
"marketId": "",
"rewardType": "ACCOUNT_TYPE_REWARD_RELATIVE_RETURN",
"lockedUntilEpoch": "12555",
"quantumAmount": "155",
"gameId": "9df138f2a12543061629c35548706466aac7185e5390bf4a58feaef5c7a079d9",
"teamId": "a0b6192896eb87f3d6c775249fa94c38ec650c489b937ba2fd205a52abea1058"
}
```

But the transfer is this ... which indicates it is for INDIVIDUALS who are PART OF teams (there is a difference).

```
'{
    "transfer": {
        "fromAccountType": "ACCOUNT_TYPE_GENERAL",
        "to": "0000000000000000000000000000000000000000000000000000000000000000",
        "toAccountType": "ACCOUNT_TYPE_REWARD_RELATIVE_RETURN",
        "asset": "8013bcd403e421ff01b99f0fee7747e3de15601acc9d085f9508f7b1ea8025bd",
        "amount": "600000000",
        "reference": "relative return",
        "recurring": {
            "startEpoch": 12511,
            "endEpoch": 12800,
            "factor": "1",
            "dispatchStrategy": {
                "assetForMetric": "8013bcd403e421ff01b99f0fee7747e3de15601acc9d085f9508f7b1ea8025bd",
                "metric": "DISPATCH_METRIC_RELATIVE_RETURN",
                "windowLength": "1",
                "distributionStrategy": "DISTRIBUTION_STRATEGY_PRO_RATA",
                "entityScope": "ENTITY_SCOPE_INDIVIDUALS",
                "individualScope": "INDIVIDUAL_SCOPE_IN_TEAM",
                "markets": ["5cef41a86135d84b50e257f0fce208e882a40d6fccbb40e330a9592a204616f1"]
            }
        }
    }
}'
```

As a result the teamStats leaderboards are regarding these as team rewards and they're counting towards the leaderboards when we do not think they should.

image

Thread with full details 

https://vegaprotocol.slack.com/archives/C8WS7M50E/p1706808986181879?thread_ts=1706790806.322399&cid=C8WS7M50E

The pertinent bit on scope

image

I dont know if this means rewards themselves are misbehaving or just the APIs btw.

### PR DESCRIPTION
**Pull request by karlem**
Close #10532

### CODE REVIEW

File: datanode/sqlstore/migrations/0076_teams_stats.sql [hunk 1]
```diff
@@ -1,80 +1,79 @@
...
-(
-  team_id              BYTEA             NOT NULL,
-  party_id             BYTEA             NOT NULL,
-  at_epoch             BIGINT            NOT NULL,
-  total_volume         NUMERIC(1000, 16) NOT NULL,
-  total_quantum_reward NUMERIC(1000, 16) NOT NULL,
-  games_played         JSONB             NOT NULL,
-  PRIMARY KEY (team_id, party_id, at_epoch)
+CREATE TABLE IF NOT EXISTS teams_stats (
+    team_id BYTEA NOT NULL, party_id BYTEA NOT NULL, at_epoch BIGINT NOT NULL, total_volume NUMERIC(1000, 16) NOT NULL, total_quantum_reward NUMERIC(1000, 16) NOT NULL, games_played JSONB NOT NULL, PRIMARY KEY (team_id, party_id, at_epoch)
```
Comment (jeremyletang) [inline datanode/sqlstore/migrations/0076_teams_stats.sql:3]: To be fair, that looked more readable as it was initialy.

Comment (karlem) [reply datanode/sqlstore/migrations/0076_teams_stats.sql:3]: Yeah, my IDE has done it.

Comment (karlem) [reply datanode/sqlstore/migrations/0076_teams_stats.sql:3]: I will fix

**Review by guoguojin — APPROVED** [review]
