### PR TITLE
fix: Handle cancellation of order on entering auction for party in is…

### LINKED ISSUE #10748: [Bug]: Crossed order book on runs against core with margin isolated enabled
### Problem encountered

Market-sim [PR](https://github.com/vegaprotocol/vega-market-sim/pull/616) introduces a check which queries the market depth API whilst a market is in continuous trading and asserts the greatest bid price is smaller than the smallest ask price.

The check is currently on scenarios including the fuzzing runs.

Local run failed with a crossed order book:
```
2024-02-23 18:08:25,815 - root - ERROR - Market dd37c4 in TRADING_MODE_CONTINUOUS but greatest bid > smallest ask (1520.47 > 1518.58)
```
[vega-sim-ag8ruz_l.zip](https://github.com/vegaprotocol/vega/files/14388760/vega-sim-ag8ruz_l.zip)

Note: CI run in progress, will hopefully fail with same error.
https://jenkins.vega.rocks/job/common/job/vega-market-sim-reinforcement/268/

### Observed behaviour

- Market depths API reports a crossed order book whilst the market remains in continuous trading

### Expected behaviour

- Market depths API should not report a crossed order book whilst the market remains in continuous trading

### Steps to reproduce

```bash
replay
```

### Software version

feature/enable-isolated-margin

### Failing test

vega-market-sim fuzz test

### Jenkins run

_No response_

### Configuration used

```shell
{
  "genesis_time": "2023-05-09T10:00:00.000000000Z",
  "chain_id": "CUSTOM",
  "initial_height": "0",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1"
    },
    "evidence": {
      "max_age_num_blocks": "100000",
      "max_age_duration": "172800000000000",
      "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": ["ed25519"]
    },
    "version": {}
  },
  "validators": [
    {
      "address": "7DFD3744A773C166B36F170E4F5EF3E998703F4E",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "2lPO6I0p5uCBZzeoA2+ECJ2+57LtLVMjXpxH5za9TvE="
      },
      "power": "10",
      "name": ""
    }
  ],
  "app_hash": "",
  "app_state": {
    "assets": {
      "0000000000000000000000000000000000000000000000000000000000000000": {
        "name": "VOTE",
        "symbol": "VOTE",
        "decimals": 5,
        "min_lp_stake": "1",
        "source": {
          "builtin_asset": {
            "max_faucet_amount_mint": "100000000000000000"
          }
        }
      }
    },
    "validators": {
      "6NemqXSfN4zfZvAQeIANflEFqQ98izX9C0KLI2dITSY=": {
        "id": "c2b0ab69fb1bd19862c04df401920ea62d3e0bce41a50148240f42017824d17a",
        "vega_pub_key": "dfcf0fa8d67cfa11b3a511e320f3c47807a5e0735cc06dd9c2bc00f7ccc67117",
        "vega_pub_key_index": 1,
        "ethereum_address": "0x9e5BEEC6E56B28cCbd02864840B0f1e0125e42Ce",
        "tm_pub_key": "6NemqXSfN4zfZvAQeIANflEFqQ98izX9C0KLI2dITSY=",
        "info_url": "",
        "country": "",
        "name": "",
        "avatar_url": ""
      }
    },
    "network": {
      "replay_attack_threshold": 150
    },
    "network_parameters": {
      "blockchains.ethereumConfig": "{\"network_id\": \"3\", \"chain_id\": \"3\", \"collateral_bridge_contract\": { \"address\": \"0xa6F1E140daC13002Dfd9789D6dBA59117c717D7a\" }, \"confirmations\": 50, \"staking_bridge_contract\": { \"address\": \"0xfce2CC92203A266a9C8e67461ae5067c78f67235\", \"deployment_block_height\": 11001702}, \"multisig_control_contract\": {\"address\": \"0xCF6d41235911184fe6F35D47207813bFF3B91601\", \"deployment_block_height\": 12710009 } }",
      "blockchains.ethereumRpcAndEvmCompatDataSourcesConfig": "{\"configs\": []}",
      "governance.proposal.asset.maxClose": "8760h0m0s",
      "governance.proposal.asset.maxEnact": "8760h0m0s",
      "governance.proposal.asset.minClose": "1s",
      "governance.proposal.asset.minEnact": "1s",
      "governance.proposal.asset.minProposerBalance": "1",
      "governance.proposal.asset.minVoterBalance": "1",
      "governance.proposal.asset.requiredMajority": "0.66",
      "governance.proposal.asset.requiredParticipation": "0.00001",
      "governance.proposal.freeform.maxClose": "8760h0m0s",
      "governance.proposal.freeform.minClose": "1s",
      "governance.proposal.freeform.minProposerBalance": "1",
      "governance.proposal.freeform.minVoterBalance": "1",
      "governance.proposal.freeform.requiredMajority": "0.66",
      "governance.proposal.freeform.requiredParticipation": "0.00001",
      "governance.proposal.market.maxClose": "8760h0m0s",
      "governance.proposal.market.maxEnact": "8760h0m0s",
      "governance.proposal.market.minClose": "1s",
      "governance.proposal.market.minEnact": "2s",
      "governance.proposal.market.minProposerBalance": "1",
      "governance.proposal.market.minVoterBalance": "1",
      "governance.proposal.market.requiredMajority": "0.66",
      "governance.proposal.market.requiredParticipation": "0.00001",
      "governance.proposal.updateAsset.maxClose": "720h",
      "governance.proposal.updateAsset.maxEnact": "720h",
      "governance.proposal.updateAsset.minClose": "1s",
      "governance.proposal.updateAsset.minEnact": "1s",
      "governance.proposal.updateAsset.minProposerBalance": "1",
      "governance.proposal.updateAsset.minVoterBalance": "1",
      "governance.proposal.updateAsset.requiredMajority": "0.66",
      "governance.proposal.updateAsset.requiredParticipation": "0.09",
      "governance.proposal.updateMarket.maxClose": "8760h0m0s",
      "governance.proposal.updateMarket.maxEnact": "8760h0m0s",
      "governance.proposal.updateMarket.minClose": "1s",
      "governance.proposal.updateMarket.minEnact": "1s",
      "governance.proposal.updateMarket.minProposerBalance": "1",
      "governance.proposal.updateMarket.minProposerEquityLikeShare": "0",
      "governance.proposal.updateMarket.minVoterBalance": "1",
      "governance.proposal.updateMarket.requiredMajority": "0.66",
      "governance.proposal.updateMarket.requiredMajorityLP": "0.66",
      "governance.proposal.updateMarket.requiredParticipation": "0.00001",
      "governance.proposal.updateMarket.requiredParticipationLP": "0",
      "governance.proposal.updateNetParam.maxClose": "8760h0m0s",
      "governance.proposal.updateNetParam.maxEnact": "8760h0m0s",
      "governance.proposal.updateNetParam.minClose": "1s",
      "governance.proposal.updateNetParam.minEnact": "1s",
      "governance.proposal.updateNetParam.minProposerBalance": "1",
      "governance.proposal.updateNetParam.minVoterBalance": "1",
      "governance.proposal.updateNetParam.requiredMajority": "0.5",
      "governance.proposal.updateNetParam.requiredParticipation": "0.00001",
      "governance.proposal.referralProgram.maxClose": "8760h0m0s",
      "governance.proposal.referralProgram.maxEnact": "8760h0m0s",
      "governance.proposal.referralProgram.minClose": "1s",
      "governance.proposal.referralProgram.minEnact": "1s",
      "governance.proposal.referralProgram.minProposerBalance": "1",
      "governance.proposal.referralProgram.minVoterBalance": "1",
      "governance.proposal.referralProgram.requiredMajority": "0.5",
      "governance.proposal.referralProgram.requiredParticipation": "0.00001",
      "governance.proposal.VolumeDiscountProgram.maxClose": "8760h0m0s",
      "governance.proposal.VolumeDiscountProgram.maxEnact": "8760h0m0s",
      "governance.proposal.VolumeDiscountProgram.minClose": "1s",
      "governance.proposal.VolumeDiscountProgram.minEnact": "1s",
      "governance.proposal.VolumeDiscountProgram.minProposerBalance": "1",
      "governance.proposal.VolumeDiscountProgram.minVoterBalance": "1",
      "governance.proposal.VolumeDiscountProgram.requiredMajority": "0.5",
      "governance.proposal.VolumeDiscountProgram.requiredParticipation": "0.00001",
      "governance.proposal.transfer.maxClose": "8760h0m0s",
      "governance.proposal.transfer.maxEnact": "8760h0m0s",
      "governance.proposal.transfer.minClose": "1s",
      "governance.proposal.transfer.minEnact": "1s",
      "governance.proposal.transfer.minProposerBalance": "1",
      "governance.proposal.transfer.minVoterBalance": "1",
      "governance.proposal.transfer.requiredMajority": "0.5",
      "governance.proposal.transfer.requiredParticipation": "0.00001",
      "limits.markets.maxPeggedOrders": "1500",
      "limits.markets.proposePerpetualEnabled": "1",
      "market.auction.maximumDuration": "168h",
      "market.auction.minimumDuration": "1s",
      "market.fee.factors.infrastructureFee": "0.0005",
      "market.fee.factors.makerFee": "0.0002",
      "market.liquidity.bondPenaltyParameter": "0.1",
      "market.liquidity.earlyExitPenalty": "0.1",
      "market.liquidity.maximumLiquidityFeeFactorLevel": "0.03",
      "market.liquidity.minimum.probabilityOfTrading.lpOrders": "1e-6",
      "market.liquidity.probabilityOfTrading.tau.scaling": "10.0",
      "market.liquidity.providersFeeCalculationTimeStep": "1s",
      "market.liquidity.sla.nonPerformanceBondPenaltyMax": "0.5",
      "market.liquidity.sla.nonPerformanceBondPenaltySlope": "2",
      "market.liquidity.stakeToCcyVolume": "1.0",
      "market.liquidity.targetstake.triggering.ratio": "0.25",
      "market.liquidityProvision.minLpStakeQuantumMultiple": "5000",
      "market.liquidityProvision.shapes.maxSize": "100",
      "market.margin.scalingFactors": "{\"search_level\": 1.1, \"initial_margin\": 1.5, \"collateral_release\": 1.7}",
      "market.monitor.price.defaultParameters": "{\"triggers\": [{\"auction_extension\": 300, \"horizon\": 43200, \"probability\": \"0.9999999\"}] }",
      "market.stake.target.scalingFactor": "0.0001",
      "market.stake.target.timeWindow": "1h",
      "market.value.windowLength": "2h0m0s",
      "network.checkpoint.timeElapsedBetweenCheckpoints": "5m",
      "network.floatingPointUpdates.delay": "5m",
      "network.markPriceUpdateMaximumFrequency": "5s",
      "network.transaction.defaultgas": "1",
      "network.transactions.maxgasperblock": "3000000",
      "network.transactions.minBlockCapacity": "32",
      "network.validators.ersatz.multipleOfTendermintValidators": "0",
      "network.validators.ersatz.rewardFactor": "0.85",
      "network.validators.incumbentBonus": "0.05",
      "network.validators.minimumEthereumEventsForNewValidator": "3",
      "network.validators.multisig.numberOfSigners": "13",
      "network.validators.tendermint.number": "13",
      "reward.asset": "0000000000000000000000000000000000000000000000000000000000000000",
      "reward.staking.delegation.competitionLevel": "1.3",
      "reward.staking.delegation.delegatorShare": "0.8",
      "reward.staking.delegation.maxPayoutPerEpoch": "9890000000000000000000",
      "reward.staking.delegation.maxPayoutPerParticipant": "700000000000000000000",
      "reward.staking.delegation.minimumValidatorStake": "3000000000000000000000",
      "reward.staking.delegation.minValidators": "5",
      "reward.staking.delegation.optimalStakeMultiplier": "3.0",
      "reward.staking.delegation.payoutDelay": "0h",
      "reward.staking.delegation.payoutFraction": "1.0",
      "rewards.marketCreationQuantumMultiple": "1",
      "snapshot.interval.length": "300",
      "spam.pow.difficulty": "15",
      "spam.pow.hashFunction": "sha3_24_rounds",
      "spam.pow.increaseDifficulty": "0",
      "spam.pow.numberOfPastBlocks": "100",
      "spam.pow.numberOfTxPerBlock": "1000",
      "spam.protection.delegation.min.tokens": "100000000000000000",
      "spam.protection.max.batchSize": "30",
      "spam.protection.max.delegations": "360",
      "spam.protection.max.proposals": "300",
      "spam.protection.max.votes": "300",
      "spam.protection.maxUserTransfersPerEpoch": "10000",
      "spam.protection.minimumWithdrawalQuantumMultiple": "10",
      "spam.protection.minMultisigUpdates": "100000000000000000000",
      "spam.protection.proposal.min.tokens": "2000000000000000000000",
      "spam.protection.voting.min.tokens": "1000000000000000000",
      "spam.protection.applyReferral.min.funds": "0",
      "transfer.fee.factor": "0.001",
      "transfer.minTransferQuantumMultiple": "0",
      "transfer.fee.maxQuantumAmount": "100",
      "transfer.feeDiscountMinimumTrackedAmount": "0.001",
      "transfer.feeDiscountDecayFraction": "0.5",
      "validator.performance.scaling.factor": "0",
      "validators.delegation.minAmount": "1",
      "validators.epoch.length": "2m",
      "validators.vote.required": "0.67",
      "referralProgram.maxReferralTiers": "10",
      "referralProgram.maxReferralRewardFactor": "1",
      "referralProgram.maxReferralDiscountFactor": "1",
      "referralProgram.maxPartyNotionalVolumeByQuantumPerEpoch": "10000",
      "referralProgram.minStakedVegaTokens": "0",
      "referralProgram.maxReferralRewardProportion": "1"
    },
    "network_limits": {
      "propose_market_enabled": true,
      "propose_asset_enabled": true,
      "bootstrap_block_count": 0
    },
    "checkpoint": {
      "load_hash": ""
    }
  }
}
```

### Relevant log output

```shell
2024-02-23 18:08:25,815 - root - ERROR - Market dd37c4 in TRADING_MODE_CONTINUOUS but greatest bid > smallest ask (1520.47 > 1518.58)
```

### LINKED ISSUE #10750: [Bug]: panic when trying to cancel an order for party in isolated margin when entering an auction
### Problem encountered

```
panic: failed to update order margin after order cancellation [recovered]
        panic: failed to update order margin after order cancellation

goroutine 186 [running]:
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1.1()
        /Users/zoharetzioni/Downloads/vega/cmd/vega/commands/node/node.go:160 +0x58
panic({0x106134c40?, 0x14009d99cb0?})
        /opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/panic.go:914 +0x218
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x80?, 0x2?, {0x2?, 0x0?, 0x0?})
        /Users/zoharetzioni/Downloads/gopath/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x78
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x1400e3fd450, {0x14009d7f780, 0x2, 0x2})
        /Users/zoharetzioni/Downloads/gopath/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x2c0
go.uber.org/zap.(*Logger).Panic(0x1400a827640?, {0x1057be458?, 0x1400a060f00?}, {0x14009d7f780, 0x2, 0x2})
        /Users/zoharetzioni/Downloads/gopath/pkg/mod/go.uber.org/zap@v1.25.0/logger.go:258 +0x54
code.vegaprotocol.io/vega/core/execution/future.(*Market).cancelOrder(0x14001a5b500, {0x106a7e2b8?, 0x14009dac8d0}, {0x1400a060ec0, 0x40}, {0x1400a827640, 0x40})
        /Users/zoharetzioni/Downloads/vega/core/execution/future/market.go:3308 +0x610
code.vegaprotocol.io/vega/core/execution/future.(*Market).enterAuction(0x14001a5b500, {0x106a7e2b8, 0x14009dac8d0})
        /Users/zoharetzioni/Downloads/vega/core/execution/future/market.go:1426 +0xe8
code.vegaprotocol.io/vega/core/execution/future.(*Market).checkPriceAndGetTrades(0x14001a5b500, {0x106a7e2b8, 0x14009dac8d0}, 0x14009da29c0)
        /Users/zoharetzioni/Downloads/vega/core/execution/future/market.go:2411 +0x1ac
code.vegaprotocol.io/vega/core/execution/future.(*Market).submitValidatedOrder(0x14001a5b500, {0x106a7e2b8?, 0x14009dac8d0}, 0x14009da29c0)
        /Users/zoharetzioni/Downloads/vega/core/execution/future/market.go:2273 +0x790
code.vegaprotocol.io/vega/core/execution/future.(*Market).submitOrder(0x14001a5b500, {0x106a7e2b8, 0x14009dac8d0}, 0x14009da29c0)
        /Users/zoharetzioni/Downloads/vega/core/execution/future/market.go:2185 +0x194
code.vegaprotocol.io/vega/core/execution/future.(*Market).SubmitOrderWithIDGeneratorAndOrderID(0x14001a5b500, {0x106a7e2b8?, 0x14009dac8d0}, 0x40?, {0x140092ae080, 0x40}, {0x106a4e100?, 0x14009da8438?}, {0x14009db2b40, 0x40}, ...)
        /Users/zoharetzioni/Downloads/vega/core/execution/future/market.go:2144 +0x3f8
code.vegaprotocol.io/vega/core/execution.(*Engine).SubmitOrder(0x14000cca840, {0x106a7e2b8, 0x14009dac8d0}, 0x14009db62a0, {0x140092ae080, 0x40}, {0x106a4e100, 0x14009da8438}, {0x14009db2b40, 0x40})
        /Users/zoharetzioni/Downloads/vega/core/execution/engine.go:1085 +0x380
code.vegaprotocol.io/vega/core/processor.(*App).DeliverSubmitOrder(0x14000ccce00, {0x106a7e2b8, 0x14009dac8d0}, {0x106aaa5e0, 0x140091f0f40}, {0x14009db2a80, 0x40})
        /Users/zoharetzioni/Downloads/vega/core/processor/abci.go:1696 +0x10c
code.vegaprotocol.io/vega/core/processor.NewApp.addDeterministicID.func17({0x106a7e2b8, 0x14009dac8d0}, {0x106aaa5e0, 0x140091f0f40})
        /Users/zoharetzioni/Downloads/vega/core/processor/abci.go:542 +0x64
code.vegaprotocol.io/vega/core/processor.NewApp.(*App).SendTransactionResult.func18({0x106a7e2b8, 0x14009dac8d0}, {0x106aaa5e0?, 0x140091f0f40?})
        /Users/zoharetzioni/Downloads/vega/core/processor/abci.go:605 +0x4c
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0x14000cbe3c0, {0x1068389c0?, 0x1?}, 0x1400895a480)
        /Users/zoharetzioni/Downloads/vega/core/blockchain/abci/abci.go:173 +0x490
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0x1400247e690?, {0x106a7e280?, 0x109086d80?}, 0x14008934900?)
        /Users/zoharetzioni/Downloads/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x30
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*Replayer).replayChain(0x140036727e0, 0x2329)
        /Users/zoharetzioni/Downloads/vega/core/blockchain/nullchain/replay.go:160 +0x534
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).StartChain(0x14000873200)
        /Users/zoharetzioni/Downloads/vega/core/blockchain/nullchain/nullchain.go:164 +0x500
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).StartServer(0x14000873200)
        /Users/zoharetzioni/Downloads/vega/core/blockchain/nullchain/server.go:72 +0x34c
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1()
        /Users/zoharetzioni/Downloads/vega/cmd/vega/commands/node/node.go:169 +0xd4
created by code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run in goroutine 1
        /Users/zoharetzioni/Downloads/vega/cmd/vega/commands/node/node.go:154 +0x5c4
(base) zoharetzioni@Ludwigs-MacBook-Pro vega % go test ./...
```

[vega-sim-8cy8l0fu] https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fvega-market-sim-reinforcement/detail/vega-market-sim-reinforcement/268/artifacts/

### Observed behaviour

Panic when order is cancelled for a party in isolated margin mode upon entering an auction. 

### Expected behaviour

A party is in isolated margin has a number of orders, one of which is getting cancelled when entering an auction. In auctions we don't use the order price when we calculated order margin but rather use the "auction price" (if greater than the order price) - this means that the order margin for the party's remaining orders may be much larger during the auction. After cancelling the order upon entering the auction we try to update the order margin for the party and discover that they have insufficient funds to cover for the required order margin. This is unfair and shouldn't be the case, instead we should release funds if possible, and if not possible, leave the account as is. When the auction ends, the party will either have enough order margins or will get cancelled then. Upon entering the auction we should either release funds or ignore the error for insufficient order margin. 

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

develop (with isolated margin enabled)

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #10752: [Bug]: Panic when amending an order in isolated margin
### Problem encountered

```
panic: cannot unregister order with potential buy + size change < 0

goroutine 418209 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc01b65b860?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc02c361e10, {0xc00b043980, 0x2, 0x2})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0x0?, {0x3d6a262?, 0x2?}, {0xc00b043980, 0x2, 0x2})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/logger.go:258 +0x51
code.vegaprotocol.io/vega/core/positions.(*MarketPosition).UpdateOnOrderChange(0xc00b846370, 0xc005a88cc0, 0xba060f8?, 0xc02c5e9420, 0x2d50, 0x0)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/positions/market_position.go:108 +0x207
code.vegaprotocol.io/vega/core/positions.(*MarketPosition).UnregisterOrder(0x345abc0?, 0xc005a88cf0?, 0xc02d83a440?)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/positions/market_position.go:98 +0x38
code.vegaprotocol.io/vega/core/positions.(*Engine).UnregisterOrder(0xc0057def80, {0x4454b98, 0xc00918a6c0}, 0xc00b0688f0)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/positions/engine.go:262 +0x236
code.vegaprotocol.io/vega/core/execution/future.(*Market).unregisterAndReject(0xc00199e000, {0x4454b98, 0xc00918a6c0}, 0xc00b0688f0, {0x44239c0?, 0x440d370?})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/future/market.go:1278 +0xa5
code.vegaprotocol.io/vega/core/execution/future.(*Market).handleIsolatedMarginInsufficientOrderMargin(0xc00199e000, {0x4454b98, 0xc00918a6c0}, {0xc004e5d3c0, 0x40})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/future/market.go:3373 +0x27d
code.vegaprotocol.io/vega/core/execution/future.(*Market).AmendOrderWithIDGenerator(0xc00199e000, {0x4454b98?, 0xc00918a6c0}, 0x40?, {0xc004e5d3c0, 0x40}, {0x4424ec0?, 0xc01e7a9980?})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/future/market.go:3406 +0x496
code.vegaprotocol.io/vega/core/execution.(*Engine).AmendOrder(0xc00095ab00, {0x4454b98, 0xc00918a6c0}, 0xc0208c3b60, {0xc004e5d3c0, 0x40}, {0x4424ec0, 0xc01e7a9980})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/engine.go:1110 +0x3a4
code.vegaprotocol.io/vega/core/processor.(*App).DeliverAmendOrder(0xc000d4d880, {0x4454b98, 0xc00918a6c0}, {0x4481400, 0xc00b162ec0}, {0xc006104f80, 0x40})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:1770 +0x29b
code.vegaprotocol.io/vega/core/processor.NewApp.addDeterministicID.func25({0x4454b98, 0xc00918a6c0}, {0x4481400, 0xc00b162ec0})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:542 +0x5e
code.vegaprotocol.io/vega/core/processor.NewApp.(*App).SendTransactionResult.func26({0x4454b98, 0xc00918a6c0}, {0x4481400?, 0xc00b162ec0?})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:605 +0x5d
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc0001faa80, {0xb8?, 0x392b820?}, 0xc0049f1d40)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/abci/abci.go:173 +0x622
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0xc00bc665a0?, {0x4454b60?, 0x6898a40?}, 0xc004cb8e68?)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).processBlock(0xc00081b9e0)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/nullchain.go:198 +0x4a4
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).ForwardTime(0xc00081b9e0, 0x77359400)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/nullchain.go:275 +0x1ce
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime.func1()
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/server.go:132 +0x25
created by code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime in goroutine 418175
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/server.go:131 +0x22f
```

### Observed behaviour

when an order is amended in place and fails isolated margin check there's a mismatch between what's in the order book and what's in the position engine (that's reverted upon failure) - therefore when trying to remove all orders we hit a mismatch between the position view of orders and the orderbook. 

### Expected behaviour

no panic when amending an order. 

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

develop

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### LINKED ISSUE #10753: [Bug]: Panic in amend order
### Problem encountered

```
panic: cannot amend order with remaining > potential sell

goroutine 1119006 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc01e6cd380?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc031f6c270, {0xc020a23980, 0x2, 0x2})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc01de30880?, {0x3d49873?, 0xc01ef66cc0?}, {0xc020a23980, 0x2, 0x2})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/logger.go:258 +0x51
code.vegaprotocol.io/vega/core/positions.(*MarketPosition).AmendOrder(0xc0093993b0, 0xc0045502a0, 0xc01e435c70, 0x40?)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/positions/market_position.go:174 +0x558
code.vegaprotocol.io/vega/core/positions.(*Engine).AmendOrder(0xc00436ca00, {0x44563f8, 0xc0292b2570}, 0xc01e435c70, 0xc0279c7ad0)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/positions/engine.go:277 +0x397
code.vegaprotocol.io/vega/core/execution/future.(*Market).amendOrder(0xc0018d3200, {0x44563f8, 0xc0292b2570}, 0xc020a40720, {0xc01dbdb380, 0x40})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/future/market.go:3680 +0x1389
code.vegaprotocol.io/vega/core/execution/future.(*Market).AmendOrderWithIDGenerator(0xc0018d3200, {0x44563f8?, 0xc0292b2570}, 0xc020a40720, {0xc01dbdb380, 0x40}, {0x4426720?, 0xc020a328d0?})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/future/market.go:3426 +0x1bf
code.vegaprotocol.io/vega/core/execution.(*Engine).AmendOrder(0xc000c9ab00, {0x44563f8, 0xc0292b2570}, 0xc020a40720, {0xc01dbdb380, 0x40}, {0x4426720, 0xc020a328d0})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/engine.go:1110 +0x3a4
code.vegaprotocol.io/vega/core/processor.(*App).DeliverAmendOrder(0xc000ca9500, {0x44563f8, 0xc0292b2570}, {0x4482c60, 0xc0212b0cc0}, {0xc03a26f200, 0x40})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:1770 +0x29b
code.vegaprotocol.io/vega/core/processor.NewApp.addDeterministicID.func25({0x44563f8, 0xc0292b2570}, {0x4482c60, 0xc0212b0cc0})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:542 +0x5e
code.vegaprotocol.io/vega/core/processor.NewApp.(*App).SendTransactionResult.func26({0x44563f8, 0xc0292b2570}, {0x4482c60?, 0xc0212b0cc0?})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:605 +0x5d
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc00057e180, {0xb8?, 0x392c840?}, 0xc01fc80000)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/abci/abci.go:173 +0x622
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0xc02d529ba8?, {0x44563c0?, 0x6899a60?}, 0xc000116e68?)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).processBlock(0xc0009865a0)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/nullchain.go:198 +0x4a4
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).ForwardTime(0xc0009865a0, 0x77359400)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/nullchain.go:275 +0x1ce
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime.func1()
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/server.go:132 +0x25
created by code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime in goroutine 1119004
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/server.go:131 +0x22f
```

### Observed behaviour

panic when trying to amend an order in the position engine. 

### Expected behaviour

no panic in amend order

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

develop

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ze97286**
…olated margin mode

Closes #10750 
close #10752  
close #10748 
close #10753

### CODE REVIEW

File: core/matching/orderbook.go [hunk 1]
```diff
@@ -631,6 +631,32 @@ func (b *OrderBook) CancelAllOrders(party string) ([]*types.OrderCancellationCon
 	return confs, err
 }
 
+func (b *OrderBook) CheckBook() bool {
+	if len(b.buy.levels) > 0 {
+		allPegged := true
+		for _, o := range b.buy.levels[len(b.buy.levels)-1].orders {
+			if o.PeggedOrder == nil || o.PeggedOrder.Reference != types.PeggedReferenceBestBid {
+				allPegged = false
```
Comment (wwestgarth) [inline core/matching/orderbook.go:639]: Could do with a `break` here so we can save some time and stop looking.

File: core/execution/future/market.go [hunk 2]
```diff
@@ -954,6 +954,10 @@ func (m *Market) PostRestore(ctx context.Context) error {
 func (m *Market) OnTick(ctx context.Context, t time.Time) bool {
 	defer m.onTxProcessed()
 
+	if !m.matching.CheckBook() {
```
Comment (wwestgarth) [inline core/execution/future/market.go:957]: Would it make more sense to do this on block-end before we commit the state?

Comment (ze97286) [reply core/execution/future/market.go:957]: I'm not sure if we should keep this tbh, but if we do, yeah we could.

File: core/matching/orderbook.go (hunk 1 above)
Comment (ze97286) [reply core/matching/orderbook.go:639]: sure

File: core/execution/future/market.go [hunk 3]
```diff
@@ -2202,6 +2206,9 @@ func (m *Market) submitOrder(ctx context.Context, order *types.Order) (*types.Or
 }
 
 func (m *Market) submitValidatedOrder(ctx context.Context, order *types.Order) (*types.OrderConfirmation, []*types.Order, error) {
+	if order.ID == "ad1da77f46b404933f08920756ed381edacebbf369954b2014b29708bdc4c1ae" && order.MarketID == "ce4688093178cd2a90c70e78a7897a61a58b0f542f900d95a66f2a52dc2483e1" {
```
[the remark this answers is not in the document]
Comment (ze97286) [reply core/execution/future/market.go:2209]: for my suffering.

File: core/execution/future/market.go [hunk 4]
```diff
@@ -2310,14 +2322,23 @@ func (m *Market) submitValidatedOrder(ctx context.Context, order *types.Order) (
...
+					m.log.Debug("Unable to check/add immediate trade margin for party",
+						logging.Order(*order), logging.Error(err))
+				}
+				_ = m.position.UnregisterOrder(ctx, order)
+				return nil, nil, common.ErrMarginCheckFailed
+			}
+		} else if aggressorFee != nil {
+			if err := m.collateral.PartyCanCoverFees(m.settlementAsset, m.mkt.ID, order.Party, aggressorFee); err != nil {
+				m.log.Error("insufficient funds to cover fees", logging.Order(order), logging.Error(err))
+				m.unregisterAndReject(ctx, order, err)
```
[the remark this answers is not in the document]
Comment (ze97286) [reply core/execution/future/market.go:2339]: ugh, that's a pain, it has to be updated in the database enum and gql

[the remark this answers is not in the document]
Comment (ze97286) [reply core/execution/future/market.go:2339]: actually no, it seems like there's already one

**Review by jeremyletang — APPROVED** [review]
