### PR TITLE
8642 snapshot successors

### LINKED ISSUE #8642: [Bug]: Snapshot soak failure: successor markets
### Problem encountered

The snapshot soak tests picked up a handful of failures while being run on a system-test branch thats adds tests for successor markets: https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsnapshot-soak-tests/detail/snapshot-soak-tests/7668/pipeline/

The restored node falls out of consensus at the next snapshot. The diff of the snapshots files look like:
```
wwestgarth@wwestgarth-macbook ~/work/vega -  (snapshot-dir-fix) $ diff good.json bad.json -C 10
*** good.json	2023-06-29 15:28:20.000000000 +0100
--- bad.json	2023-06-29 15:28:04.000000000 +0100
***************
*** 4707,4727 ****
                              "avg": "4880000000000000000000",
                              "window": "1"
                          },
                          "nextMarkToMarket": "1687963093142838712",
                          "lastTradedPrice": "976000000000000000000",
                          "parties": [
                              "0f921914f736dedc4ddaf4a6f90331ce62b4c40f00f0205a795aa6c194873ded",
                              "47af7ce14641838e677a73db1a42dedb239e2d5af8552382d20ecaeca6e0e6e1",
                              "fe8dbbcd8e38292b40defbb2811b6a369985469d27e47ddf73a759dfbbcc26ad"
                          ],
-                         "succeeded": true,
                          "stopOrders": {
                              "pricedStopOrders": {

                              },
                              "trailingStopOrders": {
                                  "lastSeenPrice": "976000000000000000000"
                              }
                          }
                      },
                      {
--- 4707,4726 ----
```

### Observed behaviour

Snapshots do not work.

### Expected behaviour

Snapshots work.

### Steps to reproduce

```bash
See https://github.com/vegaprotocol/vega/blob/develop/core/snapshot/README.md for tips on how to debug.
```

### Software version

a18238ec8abe3c3fcf1388a6c6522b40b4f5506b

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by EVODelavega**
Closes #8642

### CODE REVIEW

**Comment by wwestgarth** [comment]
I think @jgsbennett has a full-run on the go, but for a bit quicker feedback I ran the soak test locally over just the successor market system-tests:
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/80272/pipeline

and we're golden:
```
percentage of working snapshots: 100.0% (27/27)
```

**Review by wwestgarth — DISMISSED** [review]

**Review by candida-d — DISMISSED** [review]

File: core/execution/engine_snapshot.go [hunk 1]
```diff
@@ -160,6 +160,16 @@ func (e *Engine) serialise() (snapshot []byte, providers []types.StateProvider,
...
+	successors := make([]*types.Successors, 0, len(e.successors))
+	for pid, ids := range e.successors {
+		successors = append(successors, &types.Successors{
+			ParentMarket:     pid,
+			SuccessorMarkets: ids,
+		})
+	}
+	sort.SliceStable(successors, func(i, j int) bool {
+		return successors[i].ParentMarket > successors[j].ParentMarket
+	})
```
Comment (wwestgarth) [inline core/execution/engine_snapshot.go:172]: You're not putting `successors` in the payload anywhere.

**Review by wwestgarth — APPROVED** [review]

**Review by candida-d — APPROVED** [review]
