### PR TITLE
fix: ensure zero margin on perps

### LINKED ISSUE #9672: [Bug]: Party without nothing but orders is getting margin confiscated and closed out
### Problem encountered

A party that never traded, but had orders on the book sees their margin confiscated when they run out of margin

### Observed behaviour

see above

### Expected behaviour

The orders should be closed, reducing their required margin to zero, and the party should be removed from the market.

### Software version

develop

### PR DESCRIPTION
**Pull request by EVODelavega**
Closes #9672

### CODE REVIEW

**Review by jeremyletang — APPROVED** [review]

File: core/risk/engine_test.go [hunk 1]
```diff
@@ -639,8 +647,8 @@ func TestMarginWithNoOrdersOnBook(t *testing.T) {
 		margins := riskevt.MarginLevels()
 		require.Equal(t, tc.expectedMargin, margins.MaintenanceMargin.String())
 
-		marginRecalcualted := risk.CalculateMaintenanceMarginWithSlippageFactors(evt.size, tc.buyOrders, tc.sellOrders, num.DecimalFromInt64(markPrice), num.DecimalOne(), tc.linearSlippageFactor, tc.quadraticSlippageFactor, r.Long, r.Short, constantPerUnitPositionSize, tc.auction)
-		require.Equal(t, margins.MaintenanceMargin.Float64(), marginRecalcualted.RoundUp(0).InexactFloat64())
+		// marginRecalcualted := risk.CalculateMaintenanceMarginWithSlippageFactors(evt.size, tc.buyOrders, tc.sellOrders, num.DecimalFromInt64(markPrice), num.DecimalOne(), tc.linearSlippageFactor, tc.quadraticSlippageFactor, r.Long, r.Short, constantPerUnitPositionSize, tc.auction)
```
Comment (karlem) [inline core/risk/engine_test.go:650]: Nit: this can be removed

**Review by karlem — APPROVED** [review]
