### PR TITLE
fix: make new engine compatible with old snapshot

### LINKED ISSUE #9187: [Bug]: Snapshot compatibility is failing when loading the mainnet snapshot
### Problem encountered

We have the pipeline that tries to load the mainnet snapshot into the latest develop pipeline. Today it failed with the following error (see the logs)

### Observed behaviour

Panic after load mainnet snapshot into develop

### Expected behaviour

Snapshot should be loaded correctly

### Steps to reproduce

```bash
Run https://jenkins.ops.vega.xyz/job/common/job/system-tests-snapshot-compatibility job with `VEGA_VERSION=91462b5cfdaa0917862b4ca76a87c0cef5b1340e`
```

### Software version

91462b5cfdaa0917862b4ca76a87c0cef5b1340e (origin/develop)

### Failing test

_No response_

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-snapshot-compatibility/89

### Configuration used

_No response_

### Relevant log output

```shell
Logs from failed vega-mainnet-0011-nodeset-validators-0-validator job:
-------- vega-validator-0.stderr-2023-08-24T02:39:01Z.log:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2aac04b]

goroutine 1 [running]:
code.vegaprotocol.io/vega/core/liquidity/v2.NewEngine({{0x0}}, 0x7f0f609b9f18?, {0x7f0f30306888?, 0xc000520480}, {0x7f0f303068a8?, 0xc000d3b9e0}, {0x7f0f303068d0?, 0xc002791800}, {0x58780e0, 0xc0013449a0}, ...)
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/core/liquidity/v2/engine.go:176 +0x26b
code.vegaprotocol.io/vega/core/liquidity/v2.NewSnapshotEngine({{0x60?}}, 0xc0039c51e0?, {0x7f0f30306888?, 0xc000520480?}, {0x7f0f303068a8?, 0xc000d3b9e0?}, {0x7f0f303068d0?, 0xc002791800?}, {0x58780e0, 0xc0013449a0}, ...)
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/core/liquidity/v2/snapshot.go:454 +0x110
code.vegaprotocol.io/vega/core/execution/future.NewMarketFromSnapshot({0x58aa2f0, 0xc005192450}, 0xc0005377d0, 0xc00004e240, {{0xf0?}, 0x26?}, {{0x8d?}, 0x3?}, {{0xc0?}}, {{0x0}, ...}, ...)
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/core/execution/future/market_snapshot.go:128 +0xe25
code.vegaprotocol.io/vega/core/execution.(*Engine).restoreMarket(0xc0002f4500, {0x58aa2f0, 0xc005192450}, 0xc00004e240)
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/core/execution/engine_snapshot.go:190 +0x8a9
code.vegaprotocol.io/vega/core/execution.(*Engine).restoreMarketsStates(0xc0002f4500, {0x58aa2f0, 0xc005192450}, {0xc0039c5080, 0x4, 0x0?})
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/core/execution/engine_snapshot.go:239 +0x177
code.vegaprotocol.io/vega/core/execution.(*Engine).LoadState(0xc0002f4500, {0x58aa2f0, 0xc005192450}, 0xc0039c5060)
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/core/execution/engine_snapshot.go:351 +0x94
code.vegaprotocol.io/vega/core/snapshot.(*Engine).restoreStateFromSnapshot(0xc0016c5040, {0x58aa248, 0xc000550000}, {0xc0038c4000?, 0xc4?, 0x5cdf361?})
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/core/snapshot/engine.go:843 +0x7da
code.vegaprotocol.io/vega/core/snapshot.(*Engine).restoreStateFromTree(0xc0016c5040, {0x58aa248, 0xc000550000})
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/core/snapshot/engine.go:804 +0x13f
code.vegaprotocol.io/vega/core/snapshot.(*Engine).Start(0xc0016c5040, {0x58aa248, 0xc000550000})
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/core/snapshot/engine.go:198 +0xcc
code.vegaprotocol.io/vega/core/protocol.(*Protocol).Start(0xc000542000?, {0x58aa248?, 0xc000550000?})
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/core/protocol/protocol.go:152 +0x2e
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run(0xc000542000, 0xc000da7000, {0x58cc760?, 0xc00152b3f0}, {0xc000540000, 0x15}, {0x7ffd81e2af68, 0x62}, {0x0, 0x0}, ...)
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/cmd/vega/commands/node/node.go:140 +0x5c5
code.vegaprotocol.io/vega/cmd/vega/commands.(*StartCmd).Execute(0x7ae1c20, {0x4d155a0, 0x7ae1c20, 0x1a})
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/cmd/vega/commands/node.go:105 +0x894
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0012f8900, {0xc000128010, 0x7, 0x7})
	/jenkins/GOPATH/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x809
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/jenkins/GOPATH/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
code.vegaprotocol.io/vega/cmd/vega/commands.Main({0x58aa280, 0xc000122000})
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/cmd/vega/commands/root.go:88 +0x50b
main.main()
	/jenkins/workspace/common/system-tests-snapshot-compatibility/vega/cmd/vega/main.go:24 +0x27
```

### PR DESCRIPTION
**Pull request by karlem**
Close #9187

### CODE REVIEW

**Comment by ze97286** [comment]
as a general comment, I don't like that we're passing the epoch interface throughout when we already have an epochRestored callback, so the market is already aware of the epoch when it restores the liquidity engine and can inform it the same way.

**Comment by jeremyletang** [comment]
> as a general comment, I don't like that we're passing the epoch interface throughout when we already have an epochRestored callback, so the market is already aware of the epoch when it restores the liquidity engine and can inform it the same way.

Alright, we can change this. i believe. Let me look.

File: core/liquidity/v2/snapshot_v1.go [hunk 1]
```diff
@@ -0,0 +1,213 @@
...
+	case *types.PayloadLiquidityParameters:
+		return nil, nil
+
+	default:
+		return nil, types.ErrUnknownSnapshotType
+	}
+}
+
+func (e *snapshotV1) Stopped() bool {
+	return e.stopped
```
Comment (wwestgarth) [inline core/liquidity/v2/snapshot_v1.go:136]: Wonder whether this should always return `true` in the V1 case so that it'll get removed at the next snapshot? As far as I can see currently it'll still hang around as a provider and still be providing state etc etc. and I don't know if that will cause problems at any next snapshot restore that happens.

Comment (jeremyletang) [reply core/liquidity/v2/snapshot_v1.go:136]: Yea I wondered too. And it broke at first when I tried to do it. So instead made it return true until the market is removed, but with an empty state.

File: core/liquidity/v2/snapshot.go [hunk 2]
```diff
@@ -450,25 +483,38 @@ func NewSnapshotEngine(
 	positionFactor num.Decimal,
 	slaParams *types.LiquiditySLAParams,
 ) *SnapshotEngine {
+	if slaParams == nil {
+		slaParams = defaultLiquiditySLAParams()
```
Comment (karlem) [inline core/liquidity/v2/snapshot.go:487]: @jeremyletang  I wonder if we still need this since you have added the defaults into to actual market snapshot.

**Comment by jeremyletang** [comment]
For info, here is a successful protocol upgrade pipeline with the mainnet state: https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests-snapshot-compatibility/detail/system-tests-snapshot-compatibility/47/pipeline

File: core/epochtime/service.go [hunk 3]
```diff
@@ -175,6 +175,10 @@ func (s *Svc) Load(ctx context.Context, data []byte) error {
 	return nil
 }
 
+func (s *Svc) GetEpochStartTime() time.Time {
```
Comment (karlem) [inline core/epochtime/service.go:178]: I think we can remove this now?

Comment (jeremyletang) [reply core/epochtime/service.go:178]: absolutely.

Comment (jeremyletang) [reply core/epochtime/service.go:178]: will do.

Comment (jeremyletang) [reply core/epochtime/service.go]: done.

File: core/liquidity/v2/snapshot.go (hunk 2 above)
Comment (jeremyletang) [reply core/liquidity/v2/snapshot.go:487]: we'll keep as is for now.

**Review by jeremyletang — APPROVED** [review]
