### PR TITLE
fix: send market updated event when rejecting a market

### LINKED ISSUE #8623: [Bug]: A child market which is rejected if it attempts to enact before parent voting time ends reports incorrect state in data node
### Problem encountered

[SUCM-008](https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0081-SUCM-successor_markets.md#0081-SUCM-008)
I see that when the child is rejected, one data node API reports the market as rejected, but another still reports it as being pending/opening auction
```
(Pdb) get_market_data(market_id)
{'markPrice': '0', 'bestBidPrice': '0', 'bestOfferPrice': '0', 'bestStaticBidPrice': '0', 'bestStaticOfferPrice': '0', 'midPrice': '0', 'staticMidPrice': '0', 'market': '581a3b42945ee72702407679d7cae9d710d9fae792794e7b91a2d4a52035be43', 'timestamp': '1687962117247522000', 'auctionEnd': '1687962116000000000', 'auctionStart': '1687962115000000000', 'indicativePrice': '0', 'marketTradingMode': 'TRADING_MODE_OPENING_AUCTION', 'trigger': 'AUCTION_TRIGGER_OPENING', 'targetStake': '0', 'suppliedStake': '0', 'marketValueProxy': '0', 'marketState': 'STATE_PENDING', 'nextMarkToMarket': '-6795364578871345152', 'lastTradedPrice': '0', 'marketGrowth': '0', 'bestBidVolume': '0', 'bestOfferVolume': '0', 'bestStaticBidVolume': '0', 'bestStaticOfferVolume': '0', 'openInterest': '0', 'indicativeVolume': '0', 'extensionTrigger': 'AUCTION_TRIGGER_UNSPECIFIED', 'priceMonitoringBounds': [], 'liquidityProviderFeeShare': []}
(Pdb) get_market(market_id)
{'id': '581a3b42945ee72702407679d7cae9d710d9fae792794e7b91a2d4a52035be43', 'tradableInstrument': {'instrument': {'code': 'CRYPTO:VEGA CORE SYS TEST', 'name': 'Futures System-Tests Market', 'metadata': {'tags': ['asset_class:fx/crypto', 'product:futures']}, 'future': {'settlementAsset': '032b6da360f1629e800d3ea48d1770d77cf59c3009ddb4e88a746bc04e89f4a9', 'quoteName': 'USD', 'dataSourceSpecForSettlementData': {'id': 'b06648d983e392125690b5b134680ba26d8dedf389fb73e2dbe40a1317a0c33b', 'data': {'external': {'oracle': {'signers': [{'pubKey': {'key': '5983fd48b210d4db3e956cd6e8192a2335df4e67b12d5aa5965c3668d5352621'}}], 'filters': [{'key': {'name': 'oracle.test.settlement19A60', 'type': 'TYPE_INTEGER', 'numberDecimalPlaces': '5'}, 'conditions': [{'operator': 'OPERATOR_GREATER_THAN_OR_EQUAL', 'value': '0'}]}]}}}, 'createdAt': '0', 'updatedAt': '0', 'status': 'STATUS_UNSPECIFIED'}, 'dataSourceSpecForTradingTermination': {'id': '4ee204c9148289a104eaf1aab19c0e9b208c21bc46a5a21643d1e531835f802e', 'data': {'external': {'oracle': {'signers': [{'pubKey': {'key': '5983fd48b210d4db3e956cd6e8192a2335df4e67b12d5aa5965c3668d5352621'}}], 'filters': [{'key': {'name': 'oracle.test.termination04936', 'type': 'TYPE_BOOLEAN'}, 'conditions': [{'operator': 'OPERATOR_EQUALS', 'value': 'True'}]}]}}}, 'createdAt': '0', 'updatedAt': '0', 'status': 'STATUS_UNSPECIFIED'}, 'dataSourceSpecBinding': {'settlementDataProperty': 'oracle.test.settlement19A60', 'tradingTerminationProperty': 'oracle.test.termination04936'}}, 'id': ''}, 'marginCalculator': {'scalingFactors': {'searchLevel': 1.1, 'initialMargin': 1.2, 'collateralRelease': 1.4}}, 'logNormalRiskModel': {'riskAversionParameter': 0.001, 'tau': 0.00011407711613050422, 'params': {'r': 0.016, 'sigma': 1.5, 'mu': 0.0}}}, 'decimalPlaces': '5', 'fees': {'factors': {'makerFee': '0.004', 'infrastructureFee': '0.001', 'liquidityFee': '0'}}, 'openingAuction': {'duration': '1', 'volume': '0'}, 'priceMonitoringSettings': {'parameters': {'triggers': []}}, 'liquidityMonitoringParameters': {'targetStakeParameters': {'timeWindow': '10', 'scalingFactor': 5.0}, 'triggeringRatio': '0', 'auctionExtension': '1'}, 'tradingMode': 'TRADING_MODE_NO_TRADING', 'state': 'STATE_REJECTED', 'marketTimestamps': {'proposed': '1687962111571153900', 'pending': '1687962115000000000', 'open': '1687962116000000000', 'close': '0'}, 'positionDecimalPlaces': '5', 'lpPriceRange': '1', 'linearSlippageFactor': '0.01', 'quadraticSlippageFactor': '0', 'parentMarketId': '8dbde63ac1c079275b3e596ebfd46679a2c53395ae86c38704eec98084c2f308', 'insurancePoolFraction': '0.5'}
```

### Observed behaviour

One API reports market as still being pending / in opening auction.

### Expected behaviour

Both APIs report market as being rejected/closed.

### Steps to reproduce

```bash
1. Check out: jake_successor_market
2. pytest -k test_parent_of_successor_in_proposed_state
```

### Software version

418a7ffa1c575d4ee65a69a0881d3e1760472510

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by EVODelavega**
Closes #8623

### CODE REVIEW

**Review by ze97286 — DISMISSED** [review]

File: core/execution/engine.go [hunk 1]
```diff
@@ -250,6 +250,9 @@ func (e *Engine) RejectMarket(ctx context.Context, marketID string) error {
 		return err
 	}
 
+	// send market update event so market data and markets API are consistent.
```
[the remark this answers is not in the document]
Comment (EVODelavega) [reply core/execution/engine.go]: Copy-paste mistake, we were missing the market data event in this case, fixed that now

File: core/execution/engine.go [hunk 2]
```diff
@@ -250,6 +250,9 @@ func (e *Engine) RejectMarket(ctx context.Context, marketID string) error {
 		return err
 	}
 
+	// send market data event so market data and markets API are consistent.
+	e.broker.Send(events.NewMarketDataEvent(ctx, mkt.GetMarketData()))
```
Comment (wwestgarth) [inline core/execution/engine.go:254]: Why aren't we sending this in `mkt.Reject(ctx)` so that its alongside the other event thats sent? Doesn't make sense for it to be here in a different place.

Comment (EVODelavega) [reply core/execution/engine.go]: This event is sent because rejected successor markets get skipped in the `OnTick` calls, where all other markets send a market data event. Because that event isn't being sent, the data-node API's are a bit borked. This is sending the event for rejected markets, to complete the market data events from the OnTick loop in execution engine, so I figured it makes sense to keep it in execution engine. The market updated event being sent in the `mkt.Reject()` call is arguably messy, because the execution engine is where we send a bunch of these events (aka `publishNewMarketInfos()` etc...), but realistically, it'll always be a spread across both, to account for oracles (trading terminated and settled)

**Review by wwestgarth — APPROVED** [review]
