### PR TITLE
fix: A referrer cannot join another team

### LINKED ISSUE #9489: [Bug]: referrer assigned as a referee can apply referral code without wallet rejection
### Problem encountered

When a referrer is assigned as a referee and referral code is applied, wallet does not reject

### Observed behaviour

no rejection response from wallet

### Expected behaviour

rejection response from wallet

### Steps to reproduce

```bash
1. Run the system-test `test_reject_referral_code_for_party_referrer` on branch 0083-RFPR-029
2. Line 156 we assign the same referrer and referee
3. Line 161 we apply referral code at which point we expect a wallet rejection response
```

### Software version

dev branch

### Failing test

test_reject_referral_code_for_party_referrer

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/11815/

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Close #9489

### CODE REVIEW

File: core/processor/abci.go [hunk 1]
```diff
@@ -2261,16 +2261,14 @@ func (app *App) ApplyReferralCode(ctx context.Context, tx abci.Tx) error {
 	partyID := types.PartyID(tx.Party())
 	err := app.referralProgram.ApplyReferralCode(ctx, partyID, types.ReferralSetID(params.Id))
 
-	// it's OK to switch team if the party was already a referrer / referee
-	if err != nil &&
-		err.Error() != referral.ErrIsAlreadyAReferee(partyID).Error() &&
-		err.Error() != referral.ErrIsAlreadyAReferrer(partyID).Error() {
+	// It's OK to switch team if the party was already a referee.
+	if err != nil && err.Error() != referral.ErrIsAlreadyAReferrer(partyID).Error() {
 		return fmt.Errorf("could not apply the referral code: %w", err)
```
Comment (EVODelavega) [inline core/processor/abci.go:2266]: nit-pick: is there any value added by wrapping this error, really?

**Review by EVODelavega — APPROVED** [review]
