### PR TITLE
fix: set the snapshot creation timeout log default greater than reasonable snapshot creation time

### LINKED ISSUE #6751: Datanode started from dehistory NOT generating deterministic history segments
**Scenario:**

Started a new network using vegacapsule , and let the network run for some time to generate data / blocks.
Then start another datanode from the latest history segment and let it catch up.

Query for the list of history segments produced by the 2 nodes ( one original and another is the restored datanode)
The history segments retrieved and stored are correct in the restored node , however after some time the history segments produced by the restored node are NOT the same as the original datanode.

**List of history segments from the original node:**

```
Muthus-MBP:networkdata muthupandianvadivelu$ ./vega datanode dehistory show --home /Users/muthupandianvadivelu/muthu/vega/repos/networkdata/testnet/data/node2/
All Decentralized History Segments:

from_height:1  to_height:50  chain_id:"testnet"  history_segment_id:"QmSbjhKA5AN8phfmCF77HPEGZwu8shtUzEDKQpFRJLGFiJ"
from_height:51  to_height:100  chain_id:"testnet"  history_segment_id:"QmXZX5u9Y5gqVeDq3ux21yaYVHN41Hg8NDof9oS2uqFbLy"  previous_history_segment_id:"QmSbjhKA5AN8phfmCF77HPEGZwu8shtUzEDKQpFRJLGFiJ"
from_height:101  to_height:150  chain_id:"testnet"  history_segment_id:"QmPgs164gqRTJCdJmgpGcSp5zr46LYP2zVtyQbyHGcc35R"  previous_history_segment_id:"QmXZX5u9Y5gqVeDq3ux21yaYVHN41Hg8NDof9oS2uqFbLy"
from_height:151  to_height:200  chain_id:"testnet"  history_segment_id:"QmdQrif4PvYHinkoyr15NXMFQtRs66E2a19fA3n4gqJW5d"  previous_history_segment_id:"QmPgs164gqRTJCdJmgpGcSp5zr46LYP2zVtyQbyHGcc35R"
from_height:201  to_height:250  chain_id:"testnet"  history_segment_id:"QmXcpoQXsxe3ebQmEuqLyVf79jRPAhZPuEpWjXJM9XgBsY"  previous_history_segment_id:"QmdQrif4PvYHinkoyr15NXMFQtRs66E2a19fA3n4gqJW5d"
from_height:251  to_height:300  chain_id:"testnet"  history_segment_id:"QmWk1RuRZFiDLD6pNAVraez45YmPqq5zD8fFzQKczUND1K"  previous_history_segment_id:"QmXcpoQXsxe3ebQmEuqLyVf79jRPAhZPuEpWjXJM9XgBsY"
from_height:301  to_height:350  chain_id:"testnet"  history_segment_id:"QmNsce16m774eJiPssvbRtbgjC8grq84HbL4fq6GktsqgW"  previous_history_segment_id:"QmWk1RuRZFiDLD6pNAVraez45YmPqq5zD8fFzQKczUND1K"
from_height:351  to_height:400  chain_id:"testnet"  history_segment_id:"Qmb5MxfBfmi5Xzo7JR4P5trsTcUPVvFHgQx6n8BYaKy9Px"  previous_history_segment_id:"QmNsce16m774eJiPssvbRtbgjC8grq84HbL4fq6GktsqgW"
from_height:401  to_height:450  chain_id:"testnet"  history_segment_id:"QmWFomFuYSYFqBKDpAqTowm4x4yK8WG21RR1ijo3fQ4npH"  previous_history_segment_id:"Qmb5MxfBfmi5Xzo7JR4P5trsTcUPVvFHgQx6n8BYaKy9Px"
from_height:451  to_height:500  chain_id:"testnet"  history_segment_id:"QmeQku85yGBVfLPBL8LwaJ8ikNbSgzPRCVJFLnCTWhWvLg"  previous_history_segment_id:"QmWFomFuYSYFqBKDpAqTowm4x4yK8WG21RR1ijo3fQ4npH"
from_height:501  to_height:550  chain_id:"testnet"  history_segment_id:"QmVXVvNQX627eoNXVptu3U41MZ7b7RkfhQDdyYJuZ3i96i"  previous_history_segment_id:"QmeQku85yGBVfLPBL8LwaJ8ikNbSgzPRCVJFLnCTWhWvLg"
from_height:551  to_height:600  chain_id:"testnet"  history_segment_id:"QmYRtC6DiyTa1iDKnqh6ciKL9xTBgBjRFJgcuwXngsZuLp"  previous_history_segment_id:"QmVXVvNQX627eoNXVptu3U41MZ7b7RkfhQDdyYJuZ3i96i"
from_height:601  to_height:650  chain_id:"testnet"  history_segment_id:"QmREpMyaxLuQyutdjBZiLF4yjNFi7oYKzs358Kaf1rZPbv"  previous_history_segment_id:"QmYRtC6DiyTa1iDKnqh6ciKL9xTBgBjRFJgcuwXngsZuLp"
from_height:651  to_height:700  chain_id:"testnet"  history_segment_id:"QmNbyAQBEVmJZZ9LJopxpii6MnmZBWP4pwETxqVRexGvFS"  previous_history_segment_id:"QmREpMyaxLuQyutdjBZiLF4yjNFi7oYKzs358Kaf1rZPbv"
from_height:701  to_height:750  chain_id:"testnet"  history_segment_id:"Qmcewan6uqHp9ML7kSs6dXL3afasrvEqQKCjRsBQMyZTFe"  previous_history_segment_id:"QmNbyAQBEVmJZZ9LJopxpii6MnmZBWP4pwETxqVRexGvFS"
from_height:751  to_height:800  chain_id:"testnet"  history_segment_id:"QmapeuvBR791HdJKSfzkL8Gzrt29BmqsH9J9Wxjjhoy5P4"  previous_history_segment_id:"Qmcewan6uqHp9ML7kSs6dXL3afasrvEqQKCjRsBQMyZTFe"
from_height:801  to_height:850  chain_id:"testnet"  history_segment_id:"Qmc3oAqwGm9URd6rERCstkHMnTUVLURKwXun8TGDc4Hxcv"  previous_history_segment_id:"QmapeuvBR791HdJKSfzkL8Gzrt29BmqsH9J9Wxjjhoy5P4"
from_height:851  to_height:900  chain_id:"testnet"  history_segment_id:"QmYidD6jQ1r8yGm1wuX6YgEKNEZ6FBceukC9M769ojVkD6"  previous_history_segment_id:"Qmc3oAqwGm9URd6rERCstkHMnTUVLURKwXun8TGDc4Hxcv"
from_height:901  to_height:950  chain_id:"testnet"  history_segment_id:"QmdjqoNHRC4kEhaCokRPAu6CPoWTeeWXQaLhRczZDjpFjj"  previous_history_segment_id:"QmYidD6jQ1r8yGm1wuX6YgEKNEZ6FBceukC9M769ojVkD6"
from_height:951  to_height:1000  chain_id:"testnet"  history_segment_id:"QmUy5nV9s4xQUoxjnkVkdmp5L2QoiG7yAzzWdk5nkemniY"  previous_history_segment_id:"QmdjqoNHRC4kEhaCokRPAu6CPoWTeeWXQaLhRczZDjpFjj"
from_height:1001  to_height:1050  chain_id:"testnet"  history_segment_id:"QmRwxKD2dt5yyziSi4i5pGRV15mdfLGnmZtpBsztJMSQAE"  previous_history_segment_id:"QmUy5nV9s4xQUoxjnkVkdmp5L2QoiG7yAzzWdk5nkemniY"
from_height:1051  to_height:1100  chain_id:"testnet"  history_segment_id:"QmUSEnzeKVACaDeqwyJovC5aPtbVTqtJZhwvnf4uRmP7Ey"  previous_history_segment_id:"QmRwxKD2dt5yyziSi4i5pGRV15mdfLGnmZtpBsztJMSQAE"
from_height:1101  to_height:1150  chain_id:"testnet"  history_segment_id:"QmRqZsZNNFgvJhz643WmmthSJcL4dTsGt1W4P6fNW4m2Dc"  previous_history_segment_id:"QmUSEnzeKVACaDeqwyJovC5aPtbVTqtJZhwvnf4uRmP7Ey"
from_height:1151  to_height:1200  chain_id:"testnet"  history_segment_id:"QmZBQqAH14bvbiCzsjE1pURhGsAZLBS5NJdDKwRuug8wFG"  previous_history_segment_id:"QmRqZsZNNFgvJhz643WmmthSJcL4dTsGt1W4P6fNW4m2Dc"
from_height:1201  to_height:1250  chain_id:"testnet"  history_segment_id:"QmceSntj85zQ1noLjqw6vDX6eWP5HQrF9Dw4g2ELgMhPZR"  previous_history_segment_id:"QmZBQqAH14bvbiCzsjE1pURhGsAZLBS5NJdDKwRuug8wFG"
from_height:1251  to_height:1300  chain_id:"testnet"  history_segment_id:"QmPfQB4bzbB6jYkhsY2EBiSGok8bddRAWsSPCTsn2bYzAU"  previous_history_segment_id:"QmceSntj85zQ1noLjqw6vDX6eWP5HQrF9Dw4g2ELgMhPZR"
from_height:1301  to_height:1350  chain_id:"testnet"  history_segment_id:"QmZ59K7TYgDpEctTWUeen7kYJNPTBwfRxbKdzawneCVCbW"  previous_history_segment_id:"QmPfQB4bzbB6jYkhsY2EBiSGok8bddRAWsSPCTsn2bYzAU"
from_height:1351  to_height:1400  chain_id:"testnet"  history_segment_id:"Qmb7p3QwYQ7fmyubxU1LUUMdptWGUg8yHJpDCug5hjsQ7Z"  previous_history_segment_id:"QmZ59K7TYgDpEctTWUeen7kYJNPTBwfRxbKdzawneCVCbW"
from_height:1401  to_height:1450  chain_id:"testnet"  history_segment_id:"QmahfHiRDRN421RxDZKV4Ud1YiQypzQrheHmqUNbUNhp3w"  previous_history_segment_id:"Qmb7p3QwYQ7fmyubxU1LUUMdptWGUg8yHJpDCug5hjsQ7Z"
from_height:1451  to_height:1500  chain_id:"testnet"  history_segment_id:"QmbzMyXiMeCw3TdQZqnyRKBQmh7tEQWEGdX5XqfZz1V7pn"  previous_history_segment_id:"QmahfHiRDRN421RxDZKV4Ud1YiQypzQrheHmqUNbUNhp3w"
from_height:1501  to_height:1550  chain_id:"testnet"  history_segment_id:"QmPRB7ZtQtojCFH8t9tNNnVBn6fhMHyCezU43PjnZKYP34"  previous_history_segment_id:"QmbzMyXiMeCw3TdQZqnyRKBQmh7tEQWEGdX5XqfZz1V7pn"
from_height:1551  to_height:1600  chain_id:"testnet"  history_segment_id:"QmfUUKvTevkh24PBfVCPJLt7jhn3Y2nZ9HvYvdUc4z7EFR"  previous_history_segment_id:"QmPRB7ZtQtojCFH8t9tNNnVBn6fhMHyCezU43PjnZKYP34"
from_height:1601  to_height:1650  chain_id:"testnet"  history_segment_id:"QmVfwNBWFcXWLWweqiu2sDfFkfbGA2LocayezwkqAUFdHW"  previous_history_segment_id:"QmfUUKvTevkh24PBfVCPJLt7jhn3Y2nZ9HvYvdUc4z7EFR"
from_height:1651  to_height:1700  chain_id:"testnet"  history_segment_id:"Qmc3JfEBx1MoLv4ENmpeQKgURCTWNb77XjAudnTMEH4xM9"  previous_history_segment_id:"QmVfwNBWFcXWLWweqiu2sDfFkfbGA2LocayezwkqAUFdHW"
from_height:1701  to_height:1750  chain_id:"testnet"  history_segment_id:"QmbwdCseEDogdtkuMWtwpHcRcbwWd5YnrUxMq4zeAXehFq"  previous_history_segment_id:"Qmc3JfEBx1MoLv4ENmpeQKgURCTWNb77XjAudnTMEH4xM9"
from_height:1751  to_height:1800  chain_id:"testnet"  history_segment_id:"QmbZXP3EXhEAb6jeeo3hZshQFS6UoHCezkrxfjbkgh47ED"  previous_history_segment_id:"QmbwdCseEDogdtkuMWtwpHcRcbwWd5YnrUxMq4zeAXehFq"
from_height:1801  to_height:1850  chain_id:"testnet"  history_segment_id:"QmZB5YykN99X3xDLRSzzsELgoXmiz2a7CiyPDKfk3Xu8XA"  previous_history_segment_id:"QmbZXP3EXhEAb6jeeo3hZshQFS6UoHCezkrxfjbkgh47ED"
from_height:1851  to_height:1900  chain_id:"testnet"  history_segment_id:"QmaeoMtyNxqp7UV2HTrxPzYk3m9QrjafAdYX2t4e7g4549"  previous_history_segment_id:"QmZB5YykN99X3xDLRSzzsELgoXmiz2a7CiyPDKfk3Xu8XA"
from_height:1901  to_height:1950  chain_id:"testnet"  history_segment_id:"QmbAoWuAysFob1kXUzu9Y4gJxfCeMDMDzMheHtGwwdS25C"  previous_history_segment_id:"QmaeoMtyNxqp7UV2HTrxPzYk3m9QrjafAdYX2t4e7g4549"
from_height:1951  to_height:2000  chain_id:"testnet"  history_segment_id:"QmcGpCgbKRryoz7uovJVPGw7C265Sqxo8cXbt75GEhfqVA"  previous_history_segment_id:"QmbAoWuAysFob1kXUzu9Y4gJxfCeMDMDzMheHtGwwdS25C"
from_height:2001  to_height:2050  chain_id:"testnet"  history_segment_id:"Qmao6xYALESm25crNkkUgv3656K7HisYwnHTiy1DmTQM3B"  previous_history_segment_id:"QmcGpCgbKRryoz7uovJVPGw7C265Sqxo8cXbt75GEhfqVA"
from_height:2051  to_height:2100  chain_id:"testnet"  history_segment_id:"QmNfjmJikSUj9F9Zd6fSY138xPiUuXpQ2JMoff2g6FDmEP"  previous_history_segment_id:"Qmao6xYALESm25crNkkUgv3656K7HisYwnHTiy1DmTQM3B"
from_height:2101  to_height:2150  chain_id:"testnet"  history_segment_id:"QmYvtTWdS6D7brhHXUagB5y6Ef7Lv1wghfPdWx8Tfctw1v"  previous_history_segment_id:"QmNfjmJikSUj9F9Zd6fSY138xPiUuXpQ2JMoff2g6FDmEP"
from_height:2151  to_height:2200  chain_id:"testnet"  history_segment_id:"QmdM5QeySZeJyjyeJEjPYcPkfSwkiMyymsCQquphJhQ6c2"  previous_history_segment_id:"QmYvtTWdS6D7brhHXUagB5y6Ef7Lv1wghfPdWx8Tfctw1v"
from_height:2201  to_height:2250  chain_id:"testnet"  history_segment_id:"QmVzeiZyzn7G4ZybibxBQGJ8kQuxKzTLeoy7339n5Tvv38"  previous_history_segment_id:"QmdM5QeySZeJyjyeJEjPYcPkfSwkiMyymsCQquphJhQ6c2"
from_height:2251  to_height:2300  chain_id:"testnet"  history_segment_id:"QmXhfaegXcWbcpamrzW4qp97N9RJfqpjCPDv6kkqgzxG2o"  previous_history_segment_id:"QmVzeiZyzn7G4ZybibxBQGJ8kQuxKzTLeoy7339n5Tvv38"
from_height:2301  to_height:2350  chain_id:"testnet"  history_segment_id:"QmTVbmpwWNT48gY3oUtowfVAqNxxUMApw53iMik7qpPn1U"  previous_history_segment_id:"QmXhfaegXcWbcpamrzW4qp97N9RJfqpjCPDv6kkqgzxG2o"
from_height:2351  to_height:2400  chain_id:"testnet"  history_segment_id:"QmcDU29Ky7m7iTQUGzSkptwsCtpUU8dVgHtHmBxnnLgoy7"  previous_history_segment_id:"QmTVbmpwWNT48gY3oUtowfVAqNxxUMApw53iMik7qpPn1U"
from_height:2401  to_height:2450  chain_id:"testnet"  history_segment_id:"QmXFBQmuweEQBA4cXvjUbJKocQ2B5RMK8Ci2MkhcDkyDkw"  previous_history_segment_id:"QmcDU29Ky7m7iTQUGzSkptwsCtpUU8dVgHtHmBxnnLgoy7"
from_height:2451  to_height:2500  chain_id:"testnet"  history_segment_id:"QmRQLbZqrdW4dE5btAEujqqwMXbsiTUEuxFLeof5jNsFHh"  previous_history_segment_id:"QmXFBQmuweEQBA4cXvjUbJKocQ2B5RMK8Ci2MkhcDkyDkw"
from_height:2501  to_height:2550  chain_id:"testnet"  history_segment_id:"QmeAv5iZ7av8wjMGook1cr6YuGxFWyutVcKFaD4LwPeVem"  previous_history_segment_id:"QmRQLbZqrdW4dE5btAEujqqwMXbsiTUEuxFLeof5jNsFHh"
from_height:2551  to_height:2600  chain_id:"testnet"  history_segment_id:"QmTn1Bjwph3VXgtDR3pydZzXsJCqBv5CEa1aao9jfe2CYr"  previous_history_segment_id:"QmeAv5iZ7av8wjMGook1cr6YuGxFWyutVcKFaD4LwPeVem"
from_height:2601  to_height:2650  chain_id:"testnet"  history_segment_id:"QmP6nZ6hHodX3XeMc3QWjzJ9fkab97Jb6n3jUHBGtLgmDm"  previous_history_segment_id:"QmTn1Bjwph3VXgtDR3pydZzXsJCqBv5CEa1aao9jfe2CYr"
from_height:2651  to_height:2700  chain_id:"testnet"  history_segment_id:"QmSTWLLNqTvCasrQgHbuWxuVyqvZhZLfGzDPb1G7qoemrB"  previous_history_segment_id:"QmP6nZ6hHodX3XeMc3QWjzJ9fkab97Jb6n3jUHBGtLgmDm"
from_height:2701  to_height:2750  chain_id:"testnet"  history_segment_id:"QmeacjLnpTL3BjiqGNz6Wxvnvftvy82KP4faPKByFv6Vjc"  previous_history_segment_id:"QmSTWLLNqTvCasrQgHbuWxuVyqvZhZLfGzDPb1G7qoemrB"
from_height:2751  to_height:2800  chain_id:"testnet"  history_segment_id:"QmWQrhHzAPsNDFsHsnnC1TAJmcADA9uwRhRcRCyRptRAze"  previous_history_segment_id:"QmeacjLnpTL3BjiqGNz6Wxvnvftvy82KP4faPKByFv6Vjc"

Available contiguous decentralized history spans block 1 to 2800

Datanode currently has data from block height 1 to 2824
```

**List of segments from the restored node:**

```
Muthus-MBP:networkdata muthupandianvadivelu$ ./vega datanode dehistory show --home /Users/muthupandianvadivelu/muthu/vega/repos/networkdata/testnet/data/node3/
All Decentralized History Segments:

from_height:1951  to_height:2000  chain_id:"testnet"  history_segment_id:"QmcGpCgbKRryoz7uovJVPGw7C265Sqxo8cXbt75GEhfqVA"  previous_history_segment_id:"QmbAoWuAysFob1kXUzu9Y4gJxfCeMDMDzMheHtGwwdS25C"
from_height:2001  to_height:2050  chain_id:"testnet"  history_segment_id:"Qmao6xYALESm25crNkkUgv3656K7HisYwnHTiy1DmTQM3B"  previous_history_segment_id:"QmcGpCgbKRryoz7uovJVPGw7C265Sqxo8cXbt75GEhfqVA"
from_height:2051  to_height:2100  chain_id:"testnet"  history_segment_id:"QmNfjmJikSUj9F9Zd6fSY138xPiUuXpQ2JMoff2g6FDmEP"  previous_history_segment_id:"Qmao6xYALESm25crNkkUgv3656K7HisYwnHTiy1DmTQM3B"
from_height:2101  to_height:2150  chain_id:"testnet"  history_segment_id:"QmYvtTWdS6D7brhHXUagB5y6Ef7Lv1wghfPdWx8Tfctw1v"  previous_history_segment_id:"QmNfjmJikSUj9F9Zd6fSY138xPiUuXpQ2JMoff2g6FDmEP"
from_height:2151  to_height:2200  chain_id:"testnet"  history_segment_id:"QmdM5QeySZeJyjyeJEjPYcPkfSwkiMyymsCQquphJhQ6c2"  previous_history_segment_id:"QmYvtTWdS6D7brhHXUagB5y6Ef7Lv1wghfPdWx8Tfctw1v"
from_height:2251  to_height:2300  chain_id:"testnet"  history_segment_id:"QmWaC4ybbTTLQRt6f3hCWSS12m7SmwCwgJuG4NsmffiC7B"
from_height:2351  to_height:2400  chain_id:"testnet"  history_segment_id:"Qma5mfpTcEFrQUmoYaSVWfRM5L8eQSAf1QDyV1r68sNTwK"
from_height:2451  to_height:2500  chain_id:"testnet"  history_segment_id:"QmQuz6PYnLKa7b7E3MX5Pn7rk3QBrmCXpe7LRdduNL4sBf"
from_height:2551  to_height:2600  chain_id:"testnet"  history_segment_id:"QmVzPZAq4Q34tmj5Unt1zcRkwezmLzNqQh27hD6EQKmP5N"
from_height:2601  to_height:2650  chain_id:"testnet"  history_segment_id:"QmczDux1qeKMHT4jXtj5pwcxqujYEx6cQQLjPaFBLt9aRf"  previous_history_segment_id:"QmVzPZAq4Q34tmj5Unt1zcRkwezmLzNqQh27hD6EQKmP5N"
from_height:2651  to_height:2700  chain_id:"testnet"  history_segment_id:"QmfMm9XWXKHxtcFk6299kcmZavjnP9HJfX2wuggE4T7PZv"  previous_history_segment_id:"QmczDux1qeKMHT4jXtj5pwcxqujYEx6cQQLjPaFBLt9aRf"
from_height:2701  to_height:2750  chain_id:"testnet"  history_segment_id:"QmRznTnJWydNwki626LJKCk7KUCScT4BoZLHTfCnphXCgJ"  previous_history_segment_id:"QmfMm9XWXKHxtcFk6299kcmZavjnP9HJfX2wuggE4T7PZv"
from_height:2751  to_height:2800  chain_id:"testnet"  history_segment_id:"QmdUKzNEWDs4enVDuAqkoyJntwZnR4VK7d6YB1oPwrdBLK"  previous_history_segment_id:"QmRznTnJWydNwki626LJKCk7KUCScT4BoZLHTfCnphXCgJ"

Available contiguous decentralized history spans block 2551 to 2800

Datanode currently has data from block height 1951 to 2829
```

### PR DESCRIPTION
**Pull request by ettec**
closes #6751 

also should always panic on snapshot creation failure as subsequent snapshots will be incorrect as they will be unable to link to the previous snapshot.

### CODE REVIEW

File: datanode/dehistory/snapshot/service_create_snapshot.go [hunk 1]
```diff
@@ -88,9 +93,7 @@ func (b *Service) CreateSnapshot(ctx context.Context, chainID string, fromHeight
 		err = b.snapshotData(ctx, copyDataTx, dbMetaData, currentSnapshot, historySnapshot)
 		if err != nil {
 			b.log.Error("failed to snapshot data", logging.Error(err))
-			if b.config.PanicOnSnapshotCreationError {
-				panic(fmt.Sprintf("failed to snapshot data:%s", err))
-			}
+			panic(fmt.Sprintf("failed to snapshot data:%s", err))
```
Comment (jeremyletang) [inline datanode/dehistory/snapshot/service_create_snapshot.go:96]: Could we use b.log.Panic() instead of bare panic? also you can combine this with the log previous to the panic.

Comment (ettec) [reply datanode/dehistory/snapshot/service_create_snapshot.go:96]: actually, this was b.log.panic once, I changed it to this as when it panic'ed using that it did notlog the error, which was a shame

Comment (jeremyletang) [reply datanode/dehistory/snapshot/service_create_snapshot.go:96]: it does log the error when it panic, let's just use log.Panic really. it just log the error on the stdout and the stack trace on stderr, it's annoying I admit, but lets just do it with log.Panic as we do it like so everywhere

**Review by jeremyletang — APPROVED** [review]
