### PR TITLE
fix: fix distributed payout type

### LINKED ISSUE #7012: Ledger entries showing reward for maker fees paid as stake reward - Fairground
## Description

Ledger entries on Fairground console is indicating that` reward for maker fees paid`, filled that reward pool, is `stake reward`.
Trade on https://console.fairground.wtf/#/markets/e9ec6d5c46a7e7bcabf9ba7a893fa5a5eeeec08b731f06f7a6eb7bf0e605b829

## Steps to Reproduce

1. Go to https://console.fairground.wtf/#/markets/e9ec6d5c46a7e7bcabf9ba7a893fa5a5eeeec08b731f06f7a6eb7bf0e605b829
2. Get the asset and put at least one market trade
3. Wait until the epoch is over
4. Check portfolio ledger entries - https://console.fairground.wtf/#/portfolio
 

## Expected behavior

Should be indicated as reward from maker fees paid reward pool
Run the query below on https://api.n12.testnet.vega.xyz/graphql/
`query accountbalance {
  party(id: "476fc2843ba2d64aa1c73a1e1b7215843f581cf4d6c8f46587b12b37e27cc8fa") {
    accounts {
      type
      balance
      asset {
        id
        name
      }
    }
    rewards {
      rewardType
      receivedAt
      amount
      percentageOfTotal
      asset {
        name
      }
    }
  }
}`

Should give result similar to
`      "rewards": [
        {
          "rewardType": "ACCOUNT_TYPE_REWARD_MAKER_PAID_FEES",
          "receivedAt": "2022-11-29T11:47:14.183846Z",
          "amount": "136805029218921419896",
          "percentageOfTotal": "21.61552810051279",
          "asset": {
            "name": "TAKer"
          }
        }
      ]`

## Screenshots

Screenshot 2022-11-29 at 13 32 56
Screenshot 2022-11-29 at 13 19 46

- OS: macOS
- Browser Chrome
- Version v0.62.1 Fairground

### PR DESCRIPTION
**Pull request by AnExsomnis**
close: #7012

### CODE REVIEW

File: core/rewards/engine.go [hunk 1]
```diff
@@ -395,7 +395,7 @@ func (e *Engine) distributePayout(ctx context.Context, po *payout) {
 				Asset:  po.asset,
 				Amount: amt.Clone(),
 			},
-			Type:      types.TransferTypeRewardPayout,
+			Type:      proto.TransferType(po.rewardType),
```
Comment (jeremyletang) [inline core/rewards/engine.go:398]: That doesn't seem right.

Comment (AnExsomnis) [reply core/rewards/engine.go:398]: I did it because of this comment - https://github.com/vegaprotocol/vega/issues/7012#issuecomment-1334978981
I interpreted it wrong then. Should I only leave the transfer type naming change ?

Comment (AnExsomnis) [reply core/rewards/engine.go]: All right, reverted back this change; only the renaming stays according to what Zohar suggested

Comment (jeremyletang) [reply core/rewards/engine.go]: seems good now.

**Review by jeremyletang — DISMISSED** [review]

**Review by jeremyletang — APPROVED** [review]

**Review by candida-d — APPROVED** [review]

**Review by MadalinaRaicu — APPROVED** [review]
