### PR TITLE
fix: restore data-node snapshot tests

### LINKED ISSUE #6442: Re-enable data-node snapshot tests
Data-node snapshot tests were disable during the PR for BeginBlock and EndBlock message processing. The tests need to be re-enabled using a new event file with the corresponding event updates.

### PR DESCRIPTION
**Pull request by guoguojin**
Closes #6442

### CODE REVIEW

File: datanode/snapshot/service.go [hunk 1]
```diff
@@ -128,9 +128,9 @@ func (b *Service) Types() []events.Type {
 
 func GetFromHeight(toHeight int64, snapshotInterval int64) int64 {
 	fromHeight := int64(0)
-	if toHeight-snapshotInterval != 0 {
-		fromHeight = toHeight - (snapshotInterval - 1)
-	}
+	// if toHeight-snapshotInterval != 0 {
+	fromHeight = toHeight - (snapshotInterval - 1)
+	//}
```
Comment (pscott31) [inline datanode/snapshot/service.go:133]: Seems a bit odd to leave the commented code in - plus it makes the first line on the function redundant?

Comment (guoguojin) [reply datanode/snapshot/service.go:133]: Sorry, that should have been deleted.

**Review by pscott31 — APPROVED** [review]
