### PR TITLE
Fix performance issue in blockexplorer API

### LINKED ISSUE #8570: [Bug]: Basic Block Explorer database queries can be slow
### Problem encountered

With the Block Explorer UI, we've recently added a filter to the transaction list. Some queries this can produce are unreasonably slow:

```
LOG: duration: 264112.653 ms execute lrupsc_279_0: SELECT * FROM tx_results WHERE tx_results.cmd_type=$1 ORDER BY block_id desc, index desc LIMIT 25
```

```
tendermint_indexer_db=# explain SELECT * FROM tx_results WHERE tx_results.cmd_type='State Variable Proposal' ORDER BY block_id desc, index desc LIMIT 25
;
                                                         QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.56..59.18 rows=25 width=1123)
   ->  Index Scan Backward using tx_results_block_id_index_key on tx_results  (cost=0.56..2256056.38 rows=962226 width=1123)
         Filter: (cmd_type = 'State Variable Proposal'::text)
```

### Observed behaviour

Most queries work nice and quickly. Periodically though, some take a very long time. @pscott31 's digging suggests it's possible that for command types that are infrequent (`Oracle Data Submissions` have 0 results for instance).

### Expected behaviour

Note that there was a server in the load balancer that was taking a ridiculously long time to answer queries. A separate issue has been filed to set a timeout for queries. This issue is for working out why that query was slow.

### Steps to reproduce

```bash
curl 'https://be.vega.community/rest/transactions?limit=25&filters[cmd.type]=Submit%20Oracle%20Data' --globoff -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:114.0) Gecko/20100101 Firefox/114.0' -H 'Accept: */*' -H 'Accept-Language: en-GB,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: http://localhost:3000/' -H 'Origin: http://localhost:3000' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'TE: trailers'
```

### Software version

0.71.6

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Close #8570

### CODE REVIEW

File: blockexplorer/api/portal.go [hunk 1]
```diff
@@ -16,8 +16,9 @@ import (
 	"fmt"
 	"net"
 
-	"code.vegaprotocol.io/vega/logging"
 	"github.com/soheilhy/cmux"
+
```
Comment (EVODelavega) [inline blockexplorer/api/portal.go:20]: RMBL

File: blockexplorer/api/rest.go [hunk 2]
```diff
@@ -16,12 +16,13 @@ import (
 	"context"
 	"net/http"
 
+	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
+	"google.golang.org/grpc"
+	"google.golang.org/grpc/credentials/insecure"
+
```
Comment (EVODelavega) [inline blockexplorer/api/rest.go:22]: RMBL

File: blockexplorer/blockexplorer.go [hunk 3]
```diff
@@ -15,12 +15,11 @@ package blockexplorer
 import (
 	"context"
 	"fmt"
-	"net"
+
+	"golang.org/x/sync/errgroup"
```
Comment (EVODelavega) [inline blockexplorer/blockexplorer.go:20]: RMBL

**Review by jeremyletang — APPROVED** [review]
