### PR TITLE
fix: candle connection not returning candle data

### LINKED ISSUE #6248: v0.55 Candles issues
# Query:

```graphql
query {
  market(id:"1d7ddf67dac4924db03f5bf58571a7bcb1908d70c66580467717aabc5345b68a") {
   	id
    state
    candlesConnection(since:"2022-09-19T23:07:08.000Z", interval:INTERVAL_I1M) {
      edges {
        node {
          high
        }
      }
    }
  }
  statistics {
    chainId
    chainVersion
    appVersion
  }
}
```

# Result: https://api.n10.testnet.vega.xyz/graphql/
```json
{
  "errors": [
    {
      "message": "could not find candle for market 1d7ddf67dac4924db03f5bf58571a7bcb1908d70c66580467717aabc5345b68a and interval INTERVAL_I1M",
      "path": [
        "market",
        "candlesConnection"
      ]
    }
  ],
  "data": {
    "market": {
      "id": "1d7ddf67dac4924db03f5bf58571a7bcb1908d70c66580467717aabc5345b68a",
      "state": "STATE_ACTIVE",
      "candlesConnection": null
    },
    "statistics": {
      "chainId": "testnet-e90e67",
      "chainVersion": "0.34.21",
      "appVersion": "v0.55.0"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by guoguojin**
Closes #6248 

This was caused by a mishandling of the from and to dates being passed to the postgres query builder for the candles. The bad dates caused the query to always return no data.

### CODE REVIEW

File: datanode/api/trading_data_v2.go [hunk 1]
```diff
@@ -543,8 +543,16 @@ func (t *tradingDataServiceV2) ListCandleData(ctx context.Context, req *v2.ListC
 		return nil, errors.New("sql candle service not available")
 	}
 
-	from := vegatime.UnixNano(req.FromTimestamp)
-	to := vegatime.UnixNano(req.ToTimestamp)
+	var from, to *time.Time
+	if req.FromTimestamp != 0 {
+		fromTimestamp := vegatime.UnixNano(req.FromTimestamp)
+		from = &fromTimestamp
```
Comment (jeremyletang) [inline datanode/api/trading_data_v2.go:549]: Nitpick: use the ptr lib (lib/ptr)
```suggestion
		from = ptr.From(vegatime.UnixNano(req.FromTimestamp))
```

Comment (guoguojin) [reply datanode/api/trading_data_v2.go]: Thanks, I wasn't aware of that package/function. I've updated with this commit https://github.com/vegaprotocol/vega/pull/6267/commits/d7e76cc8032cd7103ffa7dc7a1bd6b267c2392e9

**Review by jeremyletang — APPROVED** [review]
