### PR TITLE
fix: fetch referral sets returns error

### LINKED ISSUE #9466: [Bug]: Error when trying to fetch referral sets and referees using REST and graphQL
### Problem encountered

Getting the below errors when trying to fetch referral sets and referee details using REST and graphQL.
Can confirm via events that the referral sets and referees have been created via events.

REST:

http://localhost:3028/api/v2/referral-sets/6845582b3815f714cad90d93d4f61d612e9748c347d2d9daa6391b96aea38c44/referees

{"code":5,"message":"Not Found","details":[]}

graphQL

```
query RefSets {
  referralSets {
    edges {
      node {
        id
        referrer
        stats {
          referees_stats {
            partyId
          }
        }
      }
    }
  }
}
```

Error:

```
{
  "errors": [
    {
      "message": "no rows in result set",
      "path": [
        "referralSets",
        "edges",
        0,
        "node",
        "stats"
      ],
      "extensions": {
        "code": 13,
        "type": "Internal"
      }
    }
  ],
  "data": {
    "referralSets": {
      "edges": [
        null
      ]
    }
  }
}
```

### Observed behaviour

As above.

### Expected behaviour

No errors

### Steps to reproduce

```bash
Run the below system test locally and execute the REST and graphQL queries manually.

System Test Name - test_create_referral_set_without_team
System Test Branch - develop
```

### Software version

vega - develop

### Failing test

n/a

### Jenkins run

n/a

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by guoguojin**
Closes #9466 

This was caused when there are no stats for the referral set, which might be possible if the query is made before the first set of statistics are published. I've made the data nullable so that it doesn't error.

### CODE REVIEW

File: version/version.go [hunk 1]
```diff
@@ -19,7 +19,7 @@ import (
 
 var (
 	cliVersionHash = ""
-	cliVersion     = "v0.72.1"
+	cliVersion     = "v99.99.0+dev"
```
Comment (jeremyletang) [inline version/version.go:22]: Why this?

Comment (guoguojin) [reply version/version.go:22]: Oh, that's a mistake I will fix it

**Review by candida-d — APPROVED** [review]
