### PR TITLE
fix: store current SLA parameters in the snapshot

### LINKED ISSUE #9447: [Bug]: Soak test failure in overnight run
### Problem encountered

On an overnight run, there was a soak test failure in the g-f set. There is nothing to go on to determine the cause because it fell out of consensus on a non-snapshot/checkpoint block, so we're flying blind here:
```
[2023-09-18T01:39:40.436Z] Replaying chain to help further diagnose...
[2023-09-18T01:39:40.436Z] calling vega unsafe_reset_all...
[2023-09-18T01:39:40.436Z] Finished: replay from height 0 has reached the end of the chain.
[2023-09-18T01:39:40.436Z] snapshot general failure restore block: 10032
[2023-09-18T01:39:40.436Z] panic: block.AppHash does not match AppHash after replay. Got B292D56F9579B01340A3DDF9ED462ABB11EF204A697D438B3C9249257D92D295, expected 2A1F7090786A9C68600CB2C9F4E7F77F3D558F394C23F819F434E06601B9E8E5.
[2023-09-18T01:39:40.436Z] 
[2023-09-18T01:39:40.436Z] Block: Block{
[2023-09-18T01:39:40.436Z]   Header{
[2023-09-18T01:39:40.436Z]     Version:        {11 1}
[2023-09-18T01:39:40.436Z]     ChainID:        testnet-001
[2023-09-18T01:39:40.436Z]     Height:         10036
[2023-09-18T01:39:40.436Z] 
[2023-09-18T01:39:40.436Z] snapshot general failure restore block: 9856
[2023-09-18T01:39:40.436Z] panic: block.AppHash does not match AppHash after replay. Got 861F50105289F33CB89EEC79300A972503BCF3593170C4F4C36DD0AB5BED4E37, expected 55D5486753C5C3CA497FAF3D8558CEE5CB4F59A3D7D2923F1188D2C61A68A1E7.
[2023-09-18T01:39:40.436Z] 
[2023-09-18T01:39:40.436Z] Block: Block{
[2023-09-18T01:39:40.436Z]   Header{
[2023-09-18T01:39:40.436Z]     Version:        {11 1}
[2023-09-18T01:39:40.436Z]     ChainID:        testnet-001
[2023-09-18T01:39:40.436Z]     Height:         9862
[2023-09-18T01:39:40.436Z] 
[2023-09-18T01:39:40.436Z] percentage of working snapshots: 99.65870307167235% (584/586)
[2023-09-18T01:39:40.436Z] block heights of failing snapshots
[2023-09-18T01:39:40.436Z] [10032, 9856]
[2023-09-18T01:39:40.436Z] 
```

### Observed behaviour

Snapshot failure.

### Expected behaviour

Snapshot works.

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

develop

### Failing test

_No response_

### Jenkins run

https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/10386/pipeline/582

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by wwestgarth**
closes #9447 

The problem was that we were not storing the _current_ SLA parameters in the snapshot and only the ones we should apply at the end of the epoch.

What this meant was that if, for example, the `commitment_min_fraction` was `0.1` but was then updated to `0.6` to be applied at the end of the epoch, any node restoring from the snapshot _before_ the end of the epoch would take the value of `0.6`.

We now store the current SLA parameter values directly in the liquidity engine snapshot so that we can restore to the correct value. This is for both the network wide parameters, and the per-market parameters.

test that caused the issue run, and soak test passes:
https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/11292/tests

### CODE REVIEW

**Review by candida-d — DISMISSED** [review]

File: core/liquidity/v2/snapshot.go [hunk 1]
```diff
@@ -110,6 +114,7 @@ func (e *snapshotV2) serialise(k string) ([]byte, error) {
 		buf []byte
 		err error
 	)
+	fmt.Println(e.paramsKey)
```
Comment (jeremyletang) [inline core/liquidity/v2/snapshot.go:117]: debug to remov here.

**Review by jeremyletang — DISMISSED** [review]

**Review by jeremyletang — APPROVED** [review]
