### PR TITLE
fix: ignore duplicate eth events due to re-org

### LINKED ISSUE #8630: [Bug]: Internal error for stake linkings API
### Problem encountered

Affected environments:

 - in the LNL pipeline.
- on the mainnet

#### Broken party 

The data-node returns the internal error for a single party_id: `fc11eb9935f013380d3880cd6eb2a3d92018acea08164c2b963b04001e92cc6b`

The query is:
```
query {
  party(id:"fc11eb9935f013380d3880cd6eb2a3d92018acea08164c2b963b04001e92cc6b") {
    stakingSummary{
      currentStakeAvailable
    }
  }
}
```

The other parties are fine like:

#### Existing party
```
query {
  party(id:"654ba5bbe6fdf20df104b7d8009ca5e0a3cdc69693a47f62bb24adb2f9158313") {
    stakingSummary{
      currentStakeAvailable
    }
  }
}
```

Returns: 

```
{
  "data": {
    "party": {
      "stakingSummary": {
        "currentStakeAvailable": "0"
      }
    }
  }
}
```

#### Non existing party

```
query {
  party(id:"654ba5bbe6fdf20df104b7d8f09ca5e0a3cdc69693a47f62bb24adb2f9158313") {
    stakingSummary{
      currentStakeAvailable
    }
  }
}
```

Returns

```
{
  "errors": [
    {
      "message": "failed to get party for ID",
      "path": [
        "party"
      ],
      "extensions": {
        "code": 5,
        "type": "NotFound"
      }
    }
  ],
  "data": {
    "party": null
  }
}
```

### Parties connection also returns internal error

The same error I am getting for the following query:

```
query {
  partiesConnection{
    edges{
      node{
        stakingSummary{
          currentStakeAvailable
        }
      }
    }
  }
}
```

I can see the error both on the https://api0.vega.community/graphql/ and on the local node when I have started the network with the checkpoint with develop branch of the vega

### Observed behaviour

Internal error response from the API

### Expected behaviour

Correct response returned

### Steps to reproduce

```bash
1. Go to api0.vega.community/graphql/
2. Execute above queries.
```

### Software version

develop, v0.71.6

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

```shell
Jun 28 20:43:28 api0.vega.community visor[2306107]: 2023-06-28T20:43:28.109Z        ERROR        datanode.start.persistentPre.connection-source        sqlstore/stake_linking.go:83        cannot calculate balance%!(EXTRA zapcore.Field={error 26 0  unlinked amount is greater than linked amount, potential missed events})
Jun 28 20:43:28 api0.vega.community visor[2306107]: 2023-06-28T20:43:28.285Z        ERROR        datanode.start.persistentPre.connection-source        sqlstore/stake_linking.go:83        cannot calculate balance%!(EXTRA zapcore.Field={error 26 0  unlinked amount is greater than linked amount, potential missed events})
```

### PR DESCRIPTION
**Pull request by ze97286**
Closes #8630

### CODE REVIEW

**Review by wwestgarth — DISMISSED** [review]

**Comment by wwestgarth** [comment]
Out of interest: was the protocol-upgrade involved at all, and was there a reason why it was finalised by core 2 weeks later?

File: core/staking/accounting_snapshot.go [hunk 1]
```diff
@@ -34,6 +34,9 @@ func (a *Accounting) serialiseStakingAccounts() ([]byte, error) {
 	accounts := make([]*types.StakingAccount, 0, len(a.hashableAccounts))
 	a.log.Debug("serialsing staking accounts", logging.Int("n", len(a.hashableAccounts)))
 	for _, acc := range a.hashableAccounts {
+		// dedup transactions with the same eth hash from different block heights and recalc the balance
```
Comment (wwestgarth) [inline core/staking/accounting_snapshot.go:37]: Whats the reasoning behind doing it at both serialisation and restoring?

**Review by wwestgarth — APPROVED** [review]

File: core/staking/accounting_snapshot.go (hunk 1 above)
Comment (ze97286) [reply core/staking/accounting_snapshot.go:37]: restoring is for fixing the existing in memory situation on the coming protocol upgrade. serialisation is for it to never be serialised in a bad state again.
