### PR TITLE
fix: improve grpc error when dehistory disabled

### LINKED ISSUE #6589: gRpc methods for dehistory should return meaningful when dehistoyr disabled
GRPC methods nil pointer erroring when decentralized history disabled, should check if the service is available and return a meaningful error if not

### PR DESCRIPTION
**Pull request by ettec**
closes #6589 GRPC methods nil pointer erroring when decentralized history disabled, should check if the service is available and return a meaningful error if not

### CODE REVIEW

File: datanode/api/trading_data_v2.go [hunk 1]
```diff
@@ -2861,6 +2868,9 @@ func (t *tradingDataServiceV2) ListAllDeHistorySegments(context.Context, *v2.Lis
 func (t *tradingDataServiceV2) FetchDeHistorySegment(ctx context.Context, req *v2.FetchDeHistorySegmentRequest) (*v2.FetchDeHistorySegmentResponse, error) {
 	defer metrics.StartAPIRequestAndTimeGRPC("FetchDeHistorySegment0'")()
 	segment, err := t.deHistoryService.FetchHistorySegment(ctx, req.HistorySegmentId)
+	if t.deHistoryService == nil {
```
Comment (wwestgarth) [inline datanode/api/trading_data_v2.go:2871]: I think this one needs to be a line higher, above `FetchHistorySegment()`?

Comment (ettec) [reply datanode/api/trading_data_v2.go:2871]: :)  thanks!

**Review by pscott31 — DISMISSED** [review]

**Review by guoguojin — DISMISSED** [review]

**Review by jeremyletang — DISMISSED** [review]

**Review by pscott31 — APPROVED** [review]

**Review by jeremyletang — APPROVED** [review]
