### PR TITLE
Positions potential size bug lookout

### LINKED ISSUE #6278: Crasher: panic: trade with a potential buy position < to the trade size
Caused by running RL training on vega-market-sim for a few hours (iteration 138). 

[vega.err.txt](https://github.com/vegaprotocol/vega/files/9628955/vega.err.txt)

I also have `vega.out` but it's 14 GB so I am not uploading it but here are the last 10000 lines: 
[vega.out.tail.10000.txt](https://github.com/vegaprotocol/vega/files/9629056/vega.out.tail.10000.txt)

Data node reported no errors.

[data_node.out.txt](https://github.com/vegaprotocol/vega/files/9628957/data_node.out.txt)

### PR DESCRIPTION
**Pull request by jeremyletang**
close #6278

### CODE REVIEW

File: core/execution/market.go [hunk 1]
```diff
@@ -2725,39 +2711,31 @@ func (m *Market) amendOrder(
...
+		return ret, nil, nil
 	}
 
 	if m.log.GetLevel() == logging.DebugLevel {
 		m.log.Debug("Order amendment not allowed", logging.Order(*existingOrder))
 	}
+
+	// for some reason, we got here without doing anything to the order,
+	// or we would have returned earlier.
+	// should we panic, as that doesn't seems right,
```
Comment (peterbarrow) [inline core/execution/market.go:2735]: I'd panic as we have no idea why we should be here

**Review by peterbarrow — DISMISSED** [review]

**Review by peterbarrow — DISMISSED** [review]

File: core/matching/side.go [hunk 2]
```diff
@@ -160,7 +160,7 @@ func (s *OrderBookSide) amendOrder(orderAmend *types.Order) (uint64, error) {
 		return 0, types.ErrOrderAmendFailure
 	}
 
-	if oldOrder.Size != orderAmend.Size &&
+	if oldOrder.Size < orderAmend.Size &&
 		oldOrder.Remaining < orderAmend.Size {
```
Comment (peterbarrow) [inline core/matching/side.go:164]: Does this line need to be here? I think if line 163 is true we are in trouble because we cannot update in place.

Comment (jeremyletang) [reply core/matching/side.go:164]: yea indeed, that's the point. If order the newOrder have an increased side, that's a bug. and should never happend.

**Review by peterbarrow — APPROVED** [review]
