### PR TITLE
fix: internal data source validations

### LINKED ISSUE #6801: [cli wallet] 0.62.1 Command line validation of new market proposal failing with valid market
# Description
With cli wallet 0.62.1 submitting to `fairground` (also 0.62.1) Submitting what **appears** to be a valid new market proposal with an internal oracle fails validation. @AnNiran recreated the JSON in a test as a go struct, and successfully passed it, which makes me think the unmarshalling might be incorrect?

# Expected output
Market proposal is submitted to a node.

# Actual output
```
✗ invalid request: proposal_submission.terms.change.new_market.changes.instrument.product.future.data_source_spec_binding.trading_termination_property (is mismatching), 
proposal_submission.terms.change.new_market.changes.instrument.product.future.data_source_spec_for_trading_termination.filters (is required),
proposal_submission.terms.change.new_market.changes.instrument.product.future.data_source_spec_for_trading_termination.signers (is required)
```

# To recreate
1. Visit https://deploy-preview-384--vega-docusaurus.netlify.app/testnet/tutorials/proposals/new-market-proposal#templates-and-submitting
2. Switch to the `token dAPP (JSON)` field - that is the JSON that we will be submitting in step 5
3. Switch to the `Command line / OSX tab`
4. Switch the pubkey and wallet name for a pubkey/wallet you actually have in a wallet. It does not need any funds at this point.
5. Copy & Paste the command
6. Errors!

# Notes
- The JSON sample / annotated JSON / command line in the documentation preview linked above are generated by a script @edd wrote, which uses the Swagger files as a basis for generating the samples. It's entirely possible there's a mistake in there and not the validation. However @AnNiran checked and thinks it looks valid, and successfully run an equivalent go test that passes.

## Wallet version check
```
❯ ./vegawallet version
Software version:
v0.62.1

Git hash:
c2681f660f38e9058554b5b366acb70d33b8c6e9

Network compatibility:
- devnet:
  Unable to determine this network version:
  no healthy node available for version check
- fairground:
  This network is running the version v0.62.1
  Compatible.
- mainnet1:
  This network is running the version v0.53.0
  Incompatible.
- stagnet3:
  This network is running the version v0.63.0+dev.1410cc69.modified
  Incompatible.
```

### PR DESCRIPTION
**Pull request by ze97286**
Closes #6801

### CODE REVIEW

File: commands/proposal_submission.go [hunk 1]
```diff
@@ -566,23 +566,29 @@ func checkDataSourceSpec(spec *vegapb.DataSourceDefinition, name string, parentP
...
+			return checkDataSourceSpecFilters(filters, name, parentProperty)
+		}
+		if len(signers) == 0 {
+			errs.AddForProperty(fmt.Sprintf("%s.%s.signers", parentProperty, name), ErrIsRequired)
+		}
+		for i, key := range signers {
+			signer := types.SignerFromProto(key)
+			if signer.IsEmpty() {
+				errs.AddForProperty(fmt.Sprintf("%s.%s.signers.%d", parentProperty, name, i), ErrIsNotValid)
+			}
```
Comment (AnExsomnis) [inline commands/proposal_submission.go:587]:
```suggestion
	switch spec.SourceType.(type) {
	case *vegapb.DataSourceDefinition_External:
	  // For now check only for oracle type for external data source. Add a check for Oracle type data later when other sources are added.
	  o := tp.External.GetOracle()
  
	  signers := o.Signers
	  if len(signers) == 0 {
		  errs.AddForProperty(fmt.Sprintf("%s.%s.external.oracle.signers", parentProperty, name), ErrIsRequired)
	  }
  
	  for i, key := range signers {
		  signer := types.SignerFromProto(key)
		  if signer.IsEmpty() {
			  errs.AddForProperty(fmt.Sprintf("%s.%s.external.oracle.signers.%d", parentProperty, name, i), ErrIsNotValid)
		  }
	  }
	  
	  filters := o.Filters
	  if isBuiltInSpec(filters) {
		  return checkDataSourceSpecFilters(filters, fmt.Sprintf("external.oracle.%s", name), parentProperty)
	  }
  
	  errs.Merge(checkDataSourceSpecFilters(filters, fmt.Sprintf("external.oracle.%s", name), parentProperty))
	  }
	}
	errs.Merge(checkDataSourceSpecFilters(filters, name, parentProperty))
		errs.Merge(checkDataSourceSpecFilters(filters, name, parentProperty))
	}
```

File: commands/proposal_submission.go [hunk 2]
```diff
@@ -572,19 +572,32 @@ func checkDataSourceSpec(spec *vegapb.DataSourceDefinition, name string, parentP
...
+	  if isBuiltInSpec(filters) {
+		  return checkDataSourceSpecFilters(filters, fmt.Sprintf("external.oracle.%s", name), parentProperty)
+	  }
+  
+	  errs.Merge(checkDataSourceSpecFilters(filters, fmt.Sprintf("external.oracle.%s", name), parentProperty))
+	  }
+	}
+	errs.Merge(checkDataSourceSpecFilters(filters, name, parentProperty))
+		errs.Merge(checkDataSourceSpecFilters(filters, name, parentProperty))
+	}
```
Comment (AnExsomnis) [inline commands/proposal_submission.go:600]:
```
errs.Merge(checkDataSourceSpecFilters(filters, name, parentProperty))
		errs.Merge(checkDataSourceSpecFilters(filters, name, parentProperty))
	}
```
This last merge should be deleted I think, because we do it inside the `if` and do not have access to filters anymore here

File: commands/proposal_submission.go [hunk 3]
```diff
@@ -566,23 +566,34 @@ func checkDataSourceSpec(spec *vegapb.DataSourceDefinition, name string, parentP
...
-	}
 
-	errs.Merge(checkDataSourceSpecFilters(filters, name, parentProperty))
+		filters := o.Filters
+		if isBuiltInSpec(filters) {
+			return checkDataSourceSpecFilters(filters, fmt.Sprintf("external.oracle.%s", name), parentProperty)
+		}
+
+		errs.Merge(checkDataSourceSpecFilters(filters, fmt.Sprintf("external.oracle.%s", name), parentProperty))
+	}
```
Comment (AnExsomnis) [inline commands/proposal_submission.go:596]: This is wrong, it should be ```fmt.Sprintf("%s.external.oracle", name)```
I posted it wrong, let me fix it.

Comment (ze97286) [reply commands/proposal_submission.go:596]: should it be %s.external.oracle? that would be e.g. `signers.external.oracle` vs `external.oracle.signers` as it is now.

Comment (ze97286) [reply commands/proposal_submission.go:596]: ah no, it's moving the dataspec backwards, no worries, I'll fix.

Comment (AnExsomnis) [reply commands/proposal_submission.go:596]: yes it should be data_spec_for_settlement_data.external.oracle.signers/filters

**Review by AnExsomnis — APPROVED** [review]
