### PR TITLE
fix: validation on governance proposals

### LINKED ISSUE #9788: [Feature]: Transfer account validation to account for network treasury
The validation in commands/transer_funds.go dates back to before the account type `NETWORK_TREASURY` existed. As a result, some of the transfers that are outlined in the spec may not pass the validation while they ought to.

The validation changes under this issue should be made to conform to the spec, accounting for the new account types that were introduced.

### PR DESCRIPTION
**Pull request by EVODelavega**
Closes #9788 

Based the validation on the spec: https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0028-GOVE-governance.md#permitted-source-and-destination-account-types

### CODE REVIEW

File: commands/proposal_submission.go [hunk 1]
```diff
@@ -494,48 +516,47 @@ func checkNewTransferChanges(change *protoTypes.ProposalTerms_NewTransfer) Error
...
-
-	// destination account type may be one of the following:
-	if _, ok := validDestinations[changes.DestinationType]; !ok {
-		return errs.FinalAddForProperty("proposal_submission.terms.change.new_transfer.changes.destination_type", ErrIsNotValid)
-	}
-
-	if changes.DestinationType == protoTypes.AccountType_ACCOUNT_TYPE_GENERAL && !IsVegaPublicKey(changes.Destination) {
+	// party accounts: check pubkey
+	if (dest == protoTypes.AccountType_ACCOUNT_TYPE_GENERAL ||
+		dest == protoTypes.AccountType_ACCOUNT_TYPE_BOND ||
```
Comment (ze97286) [inline commands/proposal_submission.go:535]: those 2 lines can go right?

File: commands/proposal_submission.go [hunk 2]
```diff
@@ -494,48 +516,47 @@ func checkNewTransferChanges(change *protoTypes.ProposalTerms_NewTransfer) Error
...
-		changes.DestinationType == protoTypes.AccountType_ACCOUNT_TYPE_GLOBAL_INSURANCE) &&
-		len(changes.Destination) > 0 {
-		return errs.FinalAddForProperty("proposal_submission.terms.change.new_transfer.changes.destination", ErrIsNotValid)
-	}
-
-	if changes.SourceType == changes.DestinationType && changes.Source == changes.Destination {
+	// global destination accounts == no source
+	if (dest == protoTypes.AccountType_ACCOUNT_TYPE_GENERAL ||
+		dest == protoTypes.AccountType_ACCOUNT_TYPE_INSURANCE ||
+		dest == protoTypes.AccountType_ACCOUNT_TYPE_BOND ||
```
Comment (ze97286) [inline commands/proposal_submission.go:557]: those 2 lines can go?

File: commands/proposal_submission.go [hunk 3]
```diff
@@ -494,48 +516,47 @@ func checkNewTransferChanges(change *protoTypes.ProposalTerms_NewTransfer) Error
...
-		changes.SourceType == protoTypes.AccountType_ACCOUNT_TYPE_NETWORK_TREASURY ||
-		changes.SourceType == protoTypes.AccountType_ACCOUNT_TYPE_GLOBAL_INSURANCE) &&
-		len(changes.Source) > 0 {
+	// insurance account type requires a source, other sources are global
+	if changes.SourceType == protoTypes.AccountType_ACCOUNT_TYPE_INSURANCE {
+		if len(changes.Source) == 0 {
+			return errs.FinalAddForProperty("proposal_submission.terms.change.new_transfer.changes.source", ErrIsNotValid)
+		}
+		// destination == source
+		if dest == changes.SourceType && changes.Source == changes.Destination {
```
Comment (ze97286) [inline commands/proposal_submission.go:547]: doesn't this apply to any source type?

Comment (EVODelavega) [reply commands/proposal_submission.go:547]: It does, but because of the map, I believe the only one where this check is actually required is market insurance pools

**Review by ze97286 — APPROVED** [review]
