### PR TITLE
fix: clear account ledger events divergence

### LINKED ISSUE #9350: [Bug]: Network history diverging in system tests full runs
### Problem encountered

Network history diverging in system tests full runs

https://jenkins.vega.rocks/job/common/job/system-tests-nightly/22/testReport/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_history_segments_are_deterministic/

### Observed behaviour

Network history diverging in system tests full runs

### Expected behaviour

Network history shouldn't diverge

### Steps to reproduce

```bash
Not too sure if its reproducible.

Happed as part of the system tests full run
```

### Software version

vega - develop

### Failing test

_No response_

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-nightly/22/testReport/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_history_segments_are_deterministic/

### Configuration used

_No response_

### Relevant log output

```shell
https://jenkins.vega.rocks/job/common/job/system-tests-nightly/22/testReport/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_history_segments_are_deterministic/
```

### PR DESCRIPTION
**Pull request by ettec**
closes #9350

### CODE REVIEW

**Review by AnExsomnis — DISMISSED** [review]

File: core/collateral/engine.go [hunk 1]
```diff
@@ -3026,8 +3026,15 @@ func (e *Engine) ClearInsurancepool(ctx context.Context, mktID, asset string, cl
 	}
 
 	// get all other market insurance accounts for the same asset
+	sortedAccKeys := make([]string, 0, len(e.accs))
+	for k := range e.accs {
+		sortedAccKeys = append(sortedAccKeys, k)
+	}
```
Comment (jeremyletang) [inline core/collateral/engine.go:3032]: Not a big deal at all, but could be written like so I guess

```suggestion
	sortedAccKeys := maps.Keys(e.accs)
```

**Review by jeremyletang — DISMISSED** [review]

File: core/collateral/engine.go (hunk 1 above)
Comment (jeremyletang) [reply core/collateral/engine.go]: Well this is going to need the import as well.

**Review by jeremyletang — APPROVED** [review]
