### PR TITLE
fix: reset failed attempts counter when it works, but no upgrade is p…

### LINKED ISSUE #11242: [Bug]: Visor reports invalid value for the attempts left
### Problem encountered

This is low priority I guess

When We start visor from network history it decreases the `attemptLeft` from 10 and at some point it becomes negative. It is confusing why the left attempts may be negative.

Another thing is that even if we hit 0 and negative value the node will be able to start

```
2024-05-04T23:23:39.459+0200    DEBUG   visor   visor/visor.go:175      Failed to get upgrade status from API   {"error": "failed to get protocol update status: request failed: Post \"http://unix/rpc\": dial unix /home/daniel/www/snapshot-testing/workdir/vega.sock: connect: connection refused"}
2024-05-04T23:23:39.459+0200    INFO    visor   visor/visor.go:179      Still waiting for vega to start...      {"attemptLeft": -47}
```

### Observed behaviour

1. Visor reports `"attemptLeft":` as negative
2. attempts left is not working
3. attempts left is by default 10 which is not enough.

### Expected behaviour

1. attempts left should be reported correctly
2. attempts left should work
3. attempts left should be bigger by default

### Steps to reproduce

```bash
1. Start a node from the network history
2. Use bigger number for the network history segments blocks
```

### Software version

v0.76.0

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by wwestgarth**
closes #11242

### CODE REVIEW

File: visor/visor.go [hunk 1]
```diff
@@ -176,12 +178,17 @@ func (v *Visor) Run(ctx context.Context) error {
...
+					if numOfRestarts == 0 {
+						attemptsLeft = maxNumberOfFirstConnectionRetries - numOfUpgradeStatusErrs
+					}
+					v.log.Info("Still waiting for vega to start...", logging.Int("attemptLeft", attemptsLeft))
 
 					break
 				}
 
 				if !upStatus.ReadyToUpgrade {
+					numOfUpgradeStatusErrs = 0
```
Comment (karlem) [inline visor/visor.go:191]: Not sure why do you reset it here?

File: visor/visor.go [hunk 2]
```diff
@@ -176,12 +178,17 @@ func (v *Visor) Run(ctx context.Context) error {
 
 					numOfUpgradeStatusErrs++
 
-					v.log.Info("Still waiting for vega to start...", logging.Int("attemptLeft", maxUpgradeStatusErrs-numOfUpgradeStatusErrs))
+					attemptsLeft := maxUpgradeStatusErrs - numOfUpgradeStatusErrs
+					if numOfRestarts == 0 {
```
Comment (karlem) [inline visor/visor.go:182]: This is a no show stopper but I would (since it's used in 2 places) store it in a variable called something like `isFirstStartup`. Just to make it very clear what we are looking for.

File: visor/visor.go (hunk 1 above)
Comment (wwestgarth) [reply visor/visor.go:191]: No reason other than it feels like that the counter should be for the number of times of times we can't get the upgrade status in a row?

Comment (karlem) [reply visor/visor.go:193]: Yes I guess that's fair.

**Review by jeremyletang — APPROVED** [review]

**Review by daniel1302 — APPROVED** [review]
