### PR TITLE
fix: expose proper value for graphql dispatch metrics

### LINKED ISSUE #10456: [API]: Make reward metric under games team entity use correct enum
# API Overview

The rewardMetric field is not typed correctly. It is a string when it should be an enum
```
fragment TeamGameFields on Game {
  id
  epoch
  numberOfParticipants
  entities {
    ... on TeamGameEntity {
        rewardMetric # This field is string
        ...
    }
  }
}

query {
  games(entityScope: ENTITY_SCOPE_TEAMS) {
    edges {
      node {
        ...TeamGameFields
      }
    }
  }
}
```

Screenshot 2024-01-19 at 18 31 35

### PR DESCRIPTION
**Pull request by jeremyletang**
close #10456.

### CODE REVIEW

File: datanode/entities/game.go [hunk 1]
```diff
@@ -21,8 +21,42 @@ import (
...
+
+func (m *DispatchMetric) DecodeText(_ *pgtype.ConnInfo, src []byte) error {
+	val, ok := vega.DispatchMetric_value[string(src)]
+	if !ok {
+		return fmt.Errorf("unknown dispatch metric: %s", src)
+	}
+
+	*m = DispatchMetric(val)
+	return nil
+}
```
Comment (guoguojin) [inline datanode/entities/game.go:58]: We normally keep the enums under datanode/entities/enum.go but this is not a deal breaker if you want to keep it here.

Comment (jeremyletang) [reply datanode/entities/game.go]: addressed

**Review by guoguojin — APPROVED** [review]

**Review by candida-d — APPROVED** [review]
