### PR TITLE
Prevent trailing stop orders from crashing when placed during opening auction

### LINKED ISSUE #10318: [Bug]: stop order in open auction causes panic
### Problem encountered

`2024-01-04T10:18:59.762Z	ERROR	tendermint	consensus/state.go:800	CONSENSUS FAILURE!!!	{"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 245 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/consensus/state.go:800 +0x46\npanic({0x5029380?, 0x8191b70?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f\ncode.vegaprotocol.io/vega/core/execution/stoporders.(*TrailingStopOrders).Insert(0xc000421d80, {0xc002eb7700, 0x40}, {0xc0057aeaa0?, 0x5600660?}, 0x2)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/stoporders/trailing_stop_orders.go:311 +0xc4\ncode.vegaprotocol.io/vega/core/execution/stoporders.(*Pool).Insert(0xc003af7a40, 0xc003e30d80)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/stoporders/stop_orders.go:229 +0x3de\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).poolStopOrders(0xc004e7e840, 0xc003e30d80, 0xc003e30cc0)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/future/market.go:1854 +0x3d\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).SubmitStopOrdersWithIDGeneratorAndOrderIDs(0xc004e7e840, {0x60290b0?, 0xc003e444e0}, 0xc0056abf30?, {0xc002eb6240, 0x40}, {0x5ff90e0?, 0xc004d8aa20}, 0xc004fd3470, 0xc004fd3480)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/future/market.go:1813 +0xcf0\ncode.vegaprotocol.io/vega/core/execution.(*Engine).SubmitStopOrders(0xc000911b80, {0x60290b0, 0xc003e444e0}, 0xc004fd3460, {0xc002eb6240, 0x40}, {0x5ff90e0, 0xc004d8aa20}, 0xc003e3fce0?, 0xc004fd3480)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/engine.go:986 +0x102\ncode.vegaprotocol.io/vega/core/processor.(*App).DeliverStopOrdersSubmission(0xc000916380, {0x60290b0, 0xc003e444e0}, {0x6055980, 0xc003ab9300}, {0xc002eb7640, 0x40})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:1618 +0x204\ncode.vegaprotocol.io/vega/core/processor.NewApp.addDeterministicID.func19({0x60290b0, 0xc003e444e0}, {0x6055980, 0xc003ab9300})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:526 +0x5e\ncode.vegaprotocol.io/vega/core/processor.NewApp.(*App).SendTransactionResult.func20({0x60290b0, 0xc003e444e0}, {0x6055980?, 0xc003ab9300?})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:589 +0x5d\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc00004fbc0, {0xc0056ac530?, 0x1c5b465?}, 0xc003e30a80)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/blockchain/abci/abci.go:172 +0x6b3\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0x4e675c0?, {0x6029190?, 0x86add40?}, 0x7fec8e08bf18?)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25\ngithub.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0xc0056ac5d0?, {0x6029190?, 0x86add40?}, 0xc0?)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/abci/client/local_client.go:185 +0xd0\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0xc001082150, {0x6029190, 0x86add40}, 0x1?)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/proxy/app_conn.go:104 +0x16d\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc00093af20, 0x6}}, {0xc00093af60, 0xb}, 0x1, 0xb2, {{0xc003f81a20, ...}, ...}, ...}, ...)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/state/execution.go:213 +0x622\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc0001bee00, 0xb3)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/consensus/state.go:1770 +0xb7d\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc0001bee00, 0xb3)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/consensus/state.go:1681 +0x2f6\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/consensus/state.go:1616 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc0001bee00, 0xb3, 0x0)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/consensus/state.go:1654 +0xc5b\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc0001bee00, 0xc003e28410, {0xc000dfddd0, 0x28})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/consensus/state.go:2323 +0x1d4d\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc0001bee00, 0xc003e28410, {0xc000dfddd0?, 0xc0056adc08?})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/consensus/state.go:2055 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc0001bee00, {{0x5fffee0, 0xc000cb1ca0}, {0xc000dfddd0, 0x28}})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/consensus/state.go:928 +0x3ce\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc0001bee00, 0x0)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/consensus/state.go:835 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 211\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.2/consensus/state.go:397 +0x10c\n"}`

### Observed behaviour

panic

### Expected behaviour

no panic

### Steps to reproduce

```bash
1. Submit stop order on a market in opening auction
```

### Software version

dev branch

### Failing test

test_stop_order_open_auction

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/35242/

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by peterbarrow**
Closes #10318

### CODE REVIEW

**Review by EVODelavega — DISMISSED** [review]

File: core/execution/engine.go [hunk 1]
```diff
@@ -983,6 +986,11 @@ func (e *Engine) SubmitStopOrders(
 	}
 
 	if mkt, ok := e.allMarkets[market]; ok {
+		// Stop orders are rejected if the market is in the opening auction
+		if mkt.IsOpeningAuction() {
+			return nil, ErrStopOrdersNotAcceptedDuringOpeningAuction
```
Comment (jeremyletang) [inline core/execution/engine.go:991]: Would it not be better to add a rejection reason in the enum, and reject it from inside the market like other rejections so an event is send and all that stuff?

Comment (peterbarrow) [reply core/execution/engine.go]: Is that better?

**Review by candida-d — DISMISSED** [review]

**Review by EVODelavega — APPROVED** [review]

**Review by gordsport — APPROVED** [review]
