### PR TITLE
Fix auction margins

### LINKED ISSUE #7894: Use slippage cap when market is in auction mode

### LINKED ISSUE #7895: Fix margin calculation during auction
Orders are included twice (once with mark price, once with vwap price) in margin calculation

### PR DESCRIPTION
**Pull request by witgaw**
* Apply slippage cap in auction (no orders on the book)
* Don't double count orders part of margin during auction (used to calculated with mark price once and then again with vwap, should only be vwap)

Closes https://github.com/vegaprotocol/vega/issues/7894 
Closes https://github.com/vegaprotocol/vega/issues/7895

### CODE REVIEW

File: core/risk/margins_calculation.go [hunk 1]
```diff
@@ -116,7 +116,7 @@ func (e *Engine) calculateMargins(m events.Margin, markPrice *num.Uint, rf types
 				err       error
 			)
 			if auction {
-				exitPrice = e.ob.GetIndicativePrice()
+				noExit = true
```
Comment (EVODelavega) [inline core/risk/margins_calculation.go:119]: I'm not sure about this. If we can get an accurate exit price during an auction, why would we not use it?

Comment (EVODelavega) [reply core/risk/margins_calculation.go:90]: Ah, that makes sense. Although, doing things this way, there might be an incongruity WRT opening auctions. IIRC, the margin requirements for orders during opening auctions were supposed to be based on the order price (if we don't have an indicative price - so until we have uncrossing orders on the book), and after that, the margin will be based on the indicative price.

I'll check the spec if that's mentioned anywhere, but if so, we might need to update that.

Comment (witgaw) [reply core/risk/margins_calculation.go:90]: It's always meant to be vwap for orders now in auctions, though that might be on the `cosmicelevator` spec branch.

**Review by EVODelavega — DISMISSED** [review]

**Review by davidsiska-vega — DISMISSED** [review]
Feature tests LGTM.

**Review by davidsiska-vega — APPROVED** [review]

**Review by jeremyletang — APPROVED** [review]
