### PR TITLE
fix: better error handling in ListEntities

### LINKED ISSUE #8225: `entities` endpoint returns unclear errors, odd data
# Problem encountered

# Observed behaviour
```graphql
{
  entities(txHash:"123") {
    proposals {
      id
    }
    votes {
      value
    } 
  }
}
```
First run:
```json
{
  "errors": [
    {
      "message": "failed to get ERC20 multisig signer removed events for tx hash",
      "path": [
        "entities"
      ],
      "extensions": {
        "code": 13,
        "type": "Internal"
      }
    }
  ],
  "data": null
}
```
Second run:
```json
{
  "errors": [
    {
      "message": "failed to get withdrawals for tx hash",
      "path": [
        "entities"
      ],
      "extensions": {
        "code": 13,
        "type": "Internal"
      }
    }
  ],
  "data": null
}
```
Actual error: There's no TX for that ID

```graphql
{
  entities(txHash:"6c2d2bd3665dad09b846fecb9bdc46c15a95527db34a7e956566a83cafc8d97d") {
  	proposals {
      id
    }  
  }
}
```
Returns:
```json
{
  "data": {
    "entities": {
      "proposals": null,
      "votes": null
    }
  }
}
```

but this did create a proposal:
Screenshot 2023-04-26 at 15 05 06

### PR DESCRIPTION
**Pull request by wwestgarth**
closes #8225 

Error handling has been improved and now returns `InvalidArgument` if you pass in a bad txHash:
Screenshot 2023-05-02 at 09 34 02

With regard to the claim that it doesn't find a proposal corresponding to a transaction with hash `6c2d2bd3665dad09b846fecb9bdc46c15a95527db34a7e956566a83cafc8d97d` it did for me on `stagnet3`:
Screenshot 2023-05-02 at 09 34 15

@edd can you try again? Maybe you were asking fairground by mistake?

### CODE REVIEW

File: datanode/api/errors.go [hunk 1]
```diff
@@ -285,7 +285,9 @@ var (
 	// MarginLevels...
 	ErrMarginLevelsGetByTxHash = errors.New("failed to get margin levels for tx hash")
 
-	ErrMissingEmptyTxHash = errors.New("missing or empty tx hash")
+	// TxHashes...
+	ErrMissingEmptyTxHash = newInvalidArgumentError("missing or empty tx hash")
+	ErrInvalidTxHash      = newInvalidArgumentError("not a valid tx hash")
 )
```
Comment (candida-d) [inline datanode/api/errors.go:291]: Thoughts on expanding these to say "transaction hash", rather than just tx?

**Comment by edd** [comment]
> @edd can you try again? Maybe you were asking fairground by mistake?

It's possible. If you're seeing useful results then either I was doing something wrong or it is magically fixed. Let's agree it's the latter.

**Review by karlem — DISMISSED** [review]

**Review by pscott31 — APPROVED** [review]

**Review by ValentinTrinque — APPROVED** [review]
