### PR TITLE
Remind the users to check their internet connection

### LINKED ISSUE #8341: [Bug]: Wallet CLI gives incorrect error when offline
### Problem encountered

When not connected to the internet, wallet gives misleading error:

image

### Observed behaviour

Error message talking about lack of healthy nodes and version compatbility.

### Expected behaviour

Preferably wallet should correctly identify that the machine is offline. Alternatively/additionally the possibility of being offline should be covered in the message.

### Steps to reproduce

```bash
1. Take computer offline
2. Do something with wallet like running the service
```

### Software version

0.71.4

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ValentinTrinque**
Close #8341

### CODE REVIEW

**Review by candida-d — CHANGES_REQUESTED** [review]

File: wallet/version/helpers.go [hunk 1]
```diff
@@ -23,7 +27,26 @@ func GetNetworkVersionThroughGRPC(hosts []string) (string, error) {
 		}
 		return version, nil
 	}
-	return "", ErrNoHealthyNodeAvailableForVersionCheck
+
+	// Before advising the users to check their network configuration, we
+	// ping vega.xyz to verify whether or not they are connected to the internet.
```
Comment (candida-d) [inline wallet/version/helpers.go:32]:
```suggestion
	// Before advising users to check their network configuration, the software
	// pings vega.xyz to verify whether or not they are connected to the internet.
```
Suggested rewording, open to other options to remove the word "we"

File: wallet/version/helpers.go [hunk 2]
```diff
@@ -23,7 +27,26 @@ func GetNetworkVersionThroughGRPC(hosts []string) (string, error) {
...
+	// This should help the user troubleshooting their setup.
```
Comment (candida-d) [inline wallet/version/helpers.go:33]:
```suggestion
	// This should help the user with troubleshooting their setup.
```

**Review by candida-d — DISMISSED** [review]

**Review by pscott31 — DISMISSED** [review]

**Review by AnExsomnis — APPROVED** [review]
