### PR TITLE
fix: ensure we hit leave auction trigger on mark-price calc, and hand…

### LINKED ISSUE #10858: [Bug]: Panic when preparing for the incentive
### Problem encountered

When preparing for the incentive using preview-4 of 0.75.0 a panic was observed

### Observed behaviour

panic

### Expected behaviour

no panic

### Steps to reproduce

1:  tried to setup trailing stop loss, twice
2: Tried to update market with the attached batch proposal, which has a lot of price auctions as you can see, but used it on the previous version, ran it several times for updates without issues.
Transaction Hash:
E2DC4434A1881F1A115A324FF421739954318177C7C6BD9EA62907FE23572304
Sent at:
Fri Mar 8 20:27:25 2024
3: Tried to vote on governance page but it did not work so tried using CLI - tx - 08433C996101080CD1128BF37258762AD217756D786854A783C880C6551F94BD
Key
69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f

### Software version

0.75.0-preview.4

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

```json
{
  "batchProposalSubmission": {
      "rationale": {
          "title": "Update market and parameter 3",
          "description": "market and parameter 3"
      },
      "terms": {
          "closingTimestamp": "1709929898",
      "changes": [
      {
          "enactmentTimestamp": "1709929898",
          "updateNetworkParameter": {
            "changes": {
              "key": "governance.proposal.asset.maxClose",
              "value": "719h"
            }
          }
        },
        {
          "enactmentTimestamp": "1709929898",
          "updateMarket": {
            "marketId": "6291cac44e47d8b89af0b6230296ea8024a30d7fa6630a4c1a1ce784df9e7c4f",
            "changes": {
              "instrument": {
                "name": "Solana - Auction Hunters",
                "code": "SOL/USD-AC",
                "perpetual": {
                  "quoteName": "USDT",
                  "marginFundingFactor": "0.9",
                  "interestRate": "0.1095",
                  "clampLowerBound": "-0.0005",
                  "clampUpperBound": "0.0005",
                  "dataSourceSpecForSettlementSchedule": {
                    "internal": {
                      "timeTrigger": {
                        "conditions": [
                          {
                            "operator": "OPERATOR_GREATER_THAN",
                            "value": "0"
                          }
                        ],
                        "triggers": [
                          {
                            "initial": "1709235362",
                            "every": "28800"
                          }
                        ]
                      }
                    }
                  },
                  "dataSourceSpecForSettlementData": {
                    "external": {
                      "ethOracle": {
                        "address": "0x719abd606155442c21b7d561426d42bd0e40a776",
                        "abi": "[{\"inputs\": [{\"internalType\": \"bytes32\", \"name\": \"id\", \"type\": \"bytes32\"}], \"name\": \"getPrice\", \"outputs\": [{\"internalType\": \"int256\", \"name\": \"\", \"type\": \"int256\" }], \"stateMutability\": \"view\", \"type\": \"function\"}]",
                        "method": "getPrice",
                        "args": [
                          "7w2Lb9os66QdoV1AldHaOSoNL47Qxse8D0z6yMKAtW0="
                        ],
                        "trigger": {
                          "timeTrigger": {
                            "initial": "1709235362",
                            "every": "60"
                          }
                        },
                        "requiredConfirmations": "3",
                        "filters": [
                          {
                            "key": {
                              "name": "sol.price",
                              "type": "TYPE_INTEGER",
                              "numberDecimalPlaces": "18"
                            },
                            "conditions": [
                              {
                                "operator": "OPERATOR_GREATER_THAN",
                                "value": "0"
                              }
                            ]
                          }
                        ],
                        "normalisers": [
                          {
                            "name": "sol.price",
                            "expression": "$[0]"
                          }
                        ],
                        "sourceChainId": "100"
                      }
                    }
                  },
                  "dataSourceSpecBinding": {
                    "settlementDataProperty": "sol.price",
                    "settlementScheduleProperty": "vegaprotocol.builtin.timetrigger"
                  },
                  "fundingRateScalingFactor": "1",
                  "fundingRateLowerBound": "-0.001",
                  "fundingRateUpperBound": "0.001",
                  "internalCompositePriceConfiguration": {
                    "decayWeight": "1",
                    "decayPower": "1",
                    "cashAmount": "50000000",
                    "sourceWeights": [
                      "0",
                      "0.999",
                      "0.001",
                      "0"
                    ],
                    "sourceStalenessTolerance": [
                      "1m0s",
                      "1m0s",
                      "10m0s",
                      "10m0s"
                    ],
                    "compositePriceType": "COMPOSITE_PRICE_TYPE_WEIGHTED",
                    "dataSourcesSpec": [
                      {
                        "external": {
                          "ethOracle": {
                            "address": "0x719abd606155442c21b7d561426d42bd0e40a776",
                            "abi": "[{\"inputs\": [{\"internalType\": \"bytes32\", \"name\": \"id\", \"type\": \"bytes32\"}], \"name\": \"getPrice\", \"outputs\": [{\"internalType\": \"int256\", \"name\": \"\", \"type\": \"int256\" }], \"stateMutability\": \"view\", \"type\": \"function\"}]",
                            "method": "getPrice",
                            "args": [
                              "7w2Lb9os66QdoV1AldHaOSoNL47Qxse8D0z6yMKAtW0="
                            ],
                            "trigger": {
                              "timeTrigger": {
                                "every": "60"
                              }
                            },
                            "requiredConfirmations": "3",
                            "filters": [
                              {
                                "key": {
                                  "name": "sol.price",
                                  "type": "TYPE_INTEGER",
                                  "numberDecimalPlaces": "18"
                                },
                                "conditions": [
                                  {
                                    "operator": "OPERATOR_GREATER_THAN",
                                    "value": "0"
                                  }
                                ]
                              }
                            ],
                            "normalisers": [
                              {
                                "name": "sol.price",
                                "expression": "$[0]"
                              }
                            ],
                            "sourceChainId": "100"
                          }
                        }
                      }
                    ],
                    "dataSourcesSpecBinding": [
                      {
                        "priceSourceProperty": "sol.price"
                      }
                    ]
                  }
                }
              },
              "metadata": [
                "base:SOL",
                "quote:USDT",
                "oracle:pyth",
                "oracleChain:gnosis",
                "class:fx/crypto",
                "perpetual",
                "sector:defi",
                "domain:https://solana.com/",
                "enactment:2024-02-04T15:00:00Z"
              ],
              "priceMonitoringParameters": {
                "triggers": [
                        {
                          "horizon": "30",
                          "probability": "0.99999",
                          "auctionExtension": "1"
                        },
                        {
                          "horizon": "30",
                          "probability": "0.99999",
                          "auctionExtension": "1"
                        },
                        {
                          "horizon": "30",
                          "probability": "0.99999",
                          "auctionExtension": "1"
                        },
                        {
                          "horizon": "30",
                          "probability": "0.99999",
                          "auctionExtension": "1"
                        },
                        {
                          "horizon": "30",
                          "probability": "0.99999",
                          "auctionExtension": "1"
                        },
                        {
                          "horizon": "30",
                          "probability": "0.99999",
                          "auctionExtension": "1"
                        },
                        {
                          "horizon": "30",
                          "probability": "0.99999",
                          "auctionExtension": "1"
                        },
                        {
                          "horizon": "30",
                          "probability": "0.99999",
                          "auctionExtension": "1"
                        },
                        {
                          "horizon": "30",
                          "probability": "0.99999",
                          "auctionExtension": "1"
                        },
                        {
                          "horizon": "120",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "120",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "120",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "120",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "120",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "200",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "200",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "200",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "200",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "200",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "400",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "400",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "400",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "400",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "400",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "400",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "500",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "500",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "500",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "500",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "500",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "500",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "500",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "620",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "620",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "620",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "620",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "620",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "620",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "750",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        },
                        {
                          "horizon": "800",
                          "probability": "0.9999999",
                          "auctionExtension": "5"
                        }
                      ]
              },
              "liquidityMonitoringParameters": {
                "targetStakeParameters": {
                  "timeWindow": "3600",
                  "scalingFactor": 0.05
                },
                "triggeringRatio": "",
                "auctionExtension": "0"
              },
              "logNormal": {
                "riskAversionParameter": 0.000001,
                "tau": 0.0000071,
                "params": {
                  "mu": 0,
                  "r": 0,
                  "sigma": 1.5
                }
              },
              "linearSlippageFactor": "0.001",
              "quadraticSlippageFactor": "",
              "liquiditySlaParameters": {
                "priceRange": "0.03",
                "commitmentMinTimeFraction": "0.75",
                "performanceHysteresisEpochs": "1",
                "slaCompetitionFactor": "0.8"
              },
              "liquidityFeeSettings": {
                "method": "METHOD_MARGINAL_COST"
              },
              "liquidationStrategy": {
                "disposalTimeStep": "1",
                "disposalFraction": "1",
                "fullDisposalSize": "1000000",
                "maxFractionConsumed": "0.1"
              },
              "markPriceConfiguration": {
                "decayWeight": "1",
                "decayPower": "1",
                "cashAmount": "0",
                "sourceWeights": [
                  "0",
                  "0",
                  "1",
                  "0"
                ],
                "sourceStalenessTolerance": [
                  "1m0s",
                  "1m0s",
                  "1m0s",
                  "1m0s"
                ],
                "compositePriceType": "COMPOSITE_PRICE_TYPE_WEIGHTED",
                "dataSourcesSpec": [
                  {
                    "external": {
                      "ethOracle": {
                        "address": "0x719abd606155442c21b7d561426d42bd0e40a776",
                        "abi": "[{\"inputs\": [{\"internalType\": \"bytes32\", \"name\": \"id\", \"type\": \"bytes32\"}], \"name\": \"getPrice\", \"outputs\": [{\"internalType\": \"int256\", \"name\": \"\", \"type\": \"int256\" }], \"stateMutability\": \"view\", \"type\": \"function\"}]",
                        "method": "getPrice",
                        "args": [
                          "7w2Lb9os66QdoV1AldHaOSoNL47Qxse8D0z6yMKAtW0="
                        ],
                        "trigger": {
                          "timeTrigger": {
                            "every": "60"
                          }
                        },
                        "requiredConfirmations": "3",
                        "filters": [
                          {
                            "key": {
                              "name": "sol.price",
                              "type": "TYPE_INTEGER",
                              "numberDecimalPlaces": "18"
                            },
                            "conditions": [
                              {
                                "operator": "OPERATOR_GREATER_THAN",
                                "value": "0"
                              }
                            ]
                          }
                        ],
                        "normalisers": [
                          {
                            "name": "sol.price",
                            "expression": "$[0]"
                          }
                        ],
                        "sourceChainId": "100"
                      }
                    }
                  }
                ],
                "dataSourcesSpecBinding": [
                  {
                    "priceSourceProperty": "sol.price"
                  }
                ]
              },
              "tickSize": "1"
            }
          }
        }
      ]
    }
  }
}
```

### Relevant log output

Mar 08 20:28:25 n01.testnet.vega.rocks visor[4148806]: 2024-03-08T20:28:25.402Z        ERROR        tendermint        consensus/state.go:800        CONSENSUS FAILURE!!!        {"err": "flags out of sync - double entry or double leave auction detected", "stack": "goroutine 589 [running]:
runtime/debug.Stack()
    /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:800 +0x46
panic({0x32fc2e0?, 0x442cfd0?})
    /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/panic.go:914 +0x21f
code.vegaprotocol.io/vega/core/products.(*auctionIntervals).update(...)
    /home/runner/work/vega/vega/core/products/perpetual.go:73
code.vegaprotocol.io/vega/core/products.(*Perpetual).UpdateAuctionState(0xc007caf930, {0x4466678, 0xc014624360}, 0x1)
    /home/runner/work/vega/vega/core/products/perpetual.go:587 +0x614
code.vegaprotocol.io/vega/core/markets.(*Instrument).UpdateAuctionState(...)
    /home/runner/work/vega/vega/core/markets/instrument.go:100
code.vegaprotocol.io/vega/core/execution/future.(*Market).enterAuction(0xc00426f800, {0x4466678, 0xc014624360})
    /home/runner/work/vega/vega/core/execution/future/market.go:1496 +0x569
code.vegaprotocol.io/vega/core/execution/future.(*Market).commandLiquidityAuction(0xc00426f800, {0x4466678, 0xc014624360})
    /home/runner/work/vega/vega/core/execution/future/market.go:4377 +0x85
code.vegaprotocol.io/vega/core/execution/future.(*Market).leaveAuction(0xc00426f800, {0x4466678?, 0xc014624360}, {0x1d034117?, 0xedd7d6be8?, 0x0?})
    /home/runner/work/vega/vega/core/execution/future/market.go:1677 +0x13c5
code.vegaprotocol.io/vega/core/execution/future.(*Market).checkAuction(0xc00426f800, {0x4466678?, 0xc014624360}, {0x546c54b?, 0xedd7d5e33?, 0x0?}, {0x4436900?, 0xc0145437b8})
    /home/runner/work/vega/vega/core/execution/future/auction.go:159 +0x1213
code.vegaprotocol.io/vega/core/execution/future.(*Market).OnTick(0xc00426f800, {0x4466678, 0xc014624360}, {0x40?, 0xc014674480?, 0x0?})
    /home/runner/work/vega/vega/core/execution/future/market.go:1033 +0x6af
code.vegaprotocol.io/vega/core/execution.(*Engine).OnTick(0xc0005c98c0, {0x4466678, 0xc014624360}, {0x1?, 0x4486560?, 0x0?})
    /home/runner/work/vega/vega/core/execution/engine.go:1324 +0x4f1
code.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)
    /home/runner/work/vega/vega/core/vegatime/service.go:107
code.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc000619280, {0x4466678, 0xc014624360}, {0x40?, 0xc01460c6c0?, 0x0?})
    /home/runner/work/vega/vega/core/vegatime/service.go:80 +0x263
code.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(0xc0009c0e00, 0x16b6240, {0xc014600280, 0x40}, {0x4580eb?, 0x28?, 0x0?}, {0xc014607500, 0x28}, {0xc01460c6c0, ...})
    /home/runner/work/vega/vega/core/processor/abci.go:1015 +0x956
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc0113ca180, {0xc000f0e558?, 0xd6aaf9?}, 0xc01457a9c0)
    /home/runner/work/vega/vega/core/blockchain/abci/abci.go:162 +0x449
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0x33623e0?, {0x4466758?, 0x68a8dc0?}, 0x7f07d2287a68?)
    /home/runner/work/vega/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25
github.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0xc00a6befe0?, {0x4466758?, 0x68a8dc0?}, 0xc0?)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/abci/client/local_client.go:185 +0xd0
github.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0xc00a6ca0d8, {0x4466758, 0x68a8dc0}, 0x1?)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:104 +0x16d
github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc00fdd62b8, 0x6}}, {0xc00fe08a60, 0x1c}, 0x1, 0x16b623f, {{0xc01389c540, ...}, ...}, ...}, ...)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/state/execution.go:213 +0x622
github.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc00ed9aa80, 0x16b6240)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1770 +0xb7d
github.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc00ed9aa80, 0x16b6240)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1681 +0x2f6
github.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1616 +0x9c
github.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc00ed9aa80, 0x16b6240, 0x0)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1654 +0xc5b
github.com/cometbft/cometbft/consensus.(*State).addVote(0xc00ed9aa80, 0xc014602000, {0xc01156e870, 0x28})
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2324 +0x1d4d
github.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc00ed9aa80, 0xc014602000, {0xc01156e870?, 0xc000f0fc08?})
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2056 +0x26
github.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc00ed9aa80, {{0x443db00, 0xc0138372d0}, {0xc01156e870, 0x28}})
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:928 +0x3ce
github.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc00ed9aa80, 0x0)
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:835 +0x3d1
created by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 440
    /home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:397 +0x10c
"}

### PR DESCRIPTION
**Pull request by wwestgarth**
close #10858 

The addition of the check that the mark price calculation can trigger a price auction was causing the book-keeping of enter/leaving auctions for perpetuals to become out of sync.

We now tell the perp that we are leaving when we call `as.Left()` and then update it again to entering an auction if the price-monitoring is triggered. The perpetual then just handles this zero length interval.

Another interesting thing is that the flow was a bit borked in `leaveAuction()` where price monitoring is triggered by the mark price calculation, we would never hit the call to `enterAuction()` after the call to `CalculateMarkPrice()` but would by luck start the auction by falling into `commandLiquidityAuction()`.

I've changed the check in `updateMarkPriceIfNotInAuction()` to properly return an `err` if we hit price-monitoring, hopefully this does not cause integration tests to fail.

### CODE REVIEW

File: core/products/perpetual.go [hunk 1]
```diff
@@ -74,7 +74,25 @@ func (a *auctionIntervals) update(t int64, enter bool) {
 	}
 
 	if enter {
-		a.auctionStart = t
+		if len(a.auctions) == 0 {
+			a.auctionStart = t
+			return
+		}
+
+		st, nd := a.auctions[len(a.auctions)-2], a.auctions[len(a.auctions)-1]
```
Comment (witgaw) [inline core/products/perpetual.go:82]: `start`, `end` would save a little bit of mental effort.

**Review by witgaw — DISMISSED** [review]
LGTM
