### PR TITLE
Fix rewards listing

### LINKED ISSUE #10299: [Bug]: The transfers list API isnt returning staking rewards
### Problem encountered

The transfer connection API returns a result for the global staking rewards up to epoch 752.  I can see this transfer on there which was funding the rewards up to that point. 

https://explorer.vega.xyz/txs/0x18BCAFC19C93CAD5C8DDC8DE4367005AAEF1393DD4A421FAF1BEE2FCDDE5CE20

But after that I cant see anything ... dont know if that relates to a code change or an account structure change or what.  Whatever the case ... this transfer has been running since then and does not appear in the query.

https://explorer.vega.xyz/txs/0x806C744FB448DFDDAFCF8068B637D842FCE6C723AE283AFBDB78938B9C98E275

### Observed behaviour

See above

### Expected behaviour

I would expect 

- All transfers appear in this query including
  - One off
  - Recurring
  - Any to / from account including network treasury
  - Any governance initiated transfer
- If using the isReward: true condition we must be able to see 
  - All recurring transfer to a reward pool 
  - Funded by any account including the network treasury
  - Including any started by governance initiated transfer

### Steps to reproduce

```bash
Run this query 


query listTransfer {
  transfersConnection{
    edges{
      node{
        transfer{
        id
        from
        fromAccountType
        to
        toAccountType
        asset{
          id
          symbol
        }
        amount
        reference
        status
        timestamp
        kind{
          ...on RecurringTransfer{
            startEpoch
            endEpoch
            dispatchStrategy{
              dispatchMetric
              dispatchMetricAssetId
              marketIdsInScope
              entityScope
              individualScope
              teamScope
              nTopPerformers
              stakingRequirement
              notionalTimeWeightedAveragePositionRequirement
              windowLength
              lockPeriod
              distributionStrategy
              rankTable{
                startRank
                shareRatio
              }
            }
          }
        }
        reason
      
      }
        fees {
          transferId
          amount
          epoch
        }
      }
    }
  }
}
```

It will not return what I am after
```


### Software version

73.10

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by karlem**
Close #10299

### CODE REVIEW

**Review by ze97286 — APPROVED** [review]

File: datanode/sqlstore/transfers.go [hunk 1]
```diff
@@ -308,9 +308,10 @@ func (t *Transfers) getRecurringTransfers(ctx context.Context, pagination entiti
 	whereStr, args := t.buildWhereClause(filters, where, args)
 
 	query := `WITH recurring_transfers AS (
-	SELECT *
-	FROM transfers_current
-	WHERE jsonb_typeof(dispatch_strategy) != 'null' AND transfer_type IN ($1, $2)
+		SELECT tc.* FROM transfers_current as tc
+		JOIN accounts as a on tc.from_account_id = a.id
+		WHERE transfer_type IN ($1, $2)
+		AND (a.type = 12 OR jsonb_typeof(tc.dispatch_strategy) != 'null')
```
Comment (karlem) [inline datanode/sqlstore/transfers.go:314]: @jeremyletang @JonRay15 I had to add `ACCOUNT_TYPE_GLOBAL_REWARD` explicitly here, because that transfer does not contain dispatch strategy. Is there any other transaction that is a reward that might be needed to be added here?

**Review by jeremyletang — APPROVED** [review]
