### PR TITLE
fix: Add validation to  to ensure the curves can be successfully gene…

### LINKED ISSUE #11442: [Bug]: division by zero in submitAMM
### Problem encountered

`Jul 11 23:54:54 n01.stagnet1.vega.rocks visor[827768]: 2024-07-11T23:54:54.665Z    ERROR    tendermint    consensus/state.go:801    CONSENSUS FAILURE!!!    {"err": "decimal division by 0", "stack": "goroutine 457 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/debug/stack.go:24 +0x5e\[ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()](http://ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2())\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/consensus/state.go:801 +0x46\npanic({0x35cad40?, 0x47761d0?})\n\t/opt/hostedtoolcache/go/1.21.12/x64/src/runtime/panic.go:914 +0x21f\[ngithub.com/shopspring/decimal.Decimal.QuoRem({0xc016c3f660](http://ngithub.com/shopspring/decimal.Decimal.QuoRem(%7B0xc016c3f660), 0xffffffe0}, {0xc016c3f680, 0xfffffff0}, 0x10)\n\t/home/runner/go/pkg/mod/github.com/vegaprotocol/decimal@v1.3.1-uint256/decimal.go:590 +0x2bc\[ngithub.com/shopspring/decimal.Decimal.DivRound({0xc016c3f660](http://ngithub.com/shopspring/decimal.Decimal.DivRound(%7B0xc016c3f660)?, 0xfffffff0?}, {0xc016c3f680?, 0xfffffff0?}, 0x10)\n\t/home/runner/go/pkg/mod/github.com/vegaprotocol/decimal@v1.3.1-uint256/decimal.go:632 +0x4d\[ngithub.com/shopspring/decimal.Decimal.Div(...)](http://ngithub.com/shopspring/decimal.Decimal.Div(...))\n\t/home/runner/go/pkg/mod/github.com/vegaprotocol/decimal@v1.3.1-uint256/decimal.go:577\[ncode.vegaprotocol.io/vega/core/execution/amm.generateCurve(0xc01f81dd40](http://ncode.vegaprotocol.io/vega/core/execution/amm.generateCurve(0xc01f81dd40), 0x1?, 0xc019b0a920, 0xc019b0a820, {0xc005e6e120?, 0x29c5790?}, {0xc002dd5ac0?, 0x0?}, {0xc005e6e1a0, 0xfffffffd}, ...)\n\t/home/runner/work/vega/vega/core/execution/amm/pool.go:387 +0x1b0\[ncode.vegaprotocol.io/vega/core/execution/amm.(*Pool).setCurves(0xc00651a4b0](http://ncode.vegaprotocol.io/vega/core/execution/amm.(*Pool).setCurves(0xc00651a4b0), 0xc0082d7a10, 0xc006940840, {0xc005e6e1a0?, 0x29c5910?})\n\t/home/runner/work/vega/vega/core/execution/amm/pool.go:449 +0x4b0\[ncode.vegaprotocol.io/vega/core/execution/amm.NewPool({0xc00bb7a640](http://ncode.vegaprotocol.io/vega/core/execution/amm.NewPool(%7B0xc00bb7a640), 0x40}, {0xc00bb7a6c0, 0x40}, {0xc0049cbdc0, 0x40}, 0xc010eb59a0, 0xc01f81dd40, {0x7f8a4c767e98, 0xc000cff100}, ...)\n\t/home/runner/work/vega/vega/core/execution/amm/pool.go:147 +0x345\[ncode.vegaprotocol.io/vega/core/execution/amm.(*Engine).Create(0xc0024d48c0](http://ncode.vegaprotocol.io/vega/core/execution/amm.(*Engine).Create(0xc0024d48c0), {0x47b1e98, 0xc026197d70}, 0xc010eb59a0, {0xc00bb7a580?, 0x10?}, 0xc000100400?, 0xc0115ac060?, {0xc005e6e1a0, 0xfffffffd})\n\t/home/runner/work/vega/vega/core/execution/amm/engine.go:655 +0x3c5\[ncode.vegaprotocol.io/vega/core/execution/future.(*Market).SubmitAMM(0xc00496d180](http://ncode.vegaprotocol.io/vega/core/execution/future.(*Market).SubmitAMM(0xc00496d180), {0x47b1e98, 0xc026197d70}, 0xc010eb59a0, {0xc00bb7a4c0?, 0xc010eb59a0?})\n\t/home/runner/work/vega/vega/core/execution/future/market.go:5454 +0x196\[ncode.vegaprotocol.io/vega/core/execution.(*Engine).SubmitAMM(0xc01154ca80](http://ncode.vegaprotocol.io/vega/core/execution.(*Engine).SubmitAMM(0xc01154ca80), {0x47b1e98, 0xc026197d70}, 0xc010eb59a0, {0xc00bb7a4c0, 0x40})\n\t/home/runner/work/vega/vega/core/execution/engine.go:264 +0x102\[ncode.vegaprotocol.io/vega/core/processor.(*App).DeliverSubmitAMM(0xc000687180](http://ncode.vegaprotocol.io/vega/core/processor.(*App).DeliverSubmitAMM(0xc000687180), {0x47b1e98, 0xc026197d70}, {0x47df230, 0xc0031e2dc0}, {0xc00bb7a4c0, 0x40})\n\t/home/runner/work/vega/vega/core/processor/abci.go:3045 +0x107\[ncode.vegaprotocol.io/vega/core/processor.NewApp.addDeterministicID.func27({0x47b1e98](http://ncode.vegaprotocol.io/vega/core/processor.NewApp.addDeterministicID.func27(%7B0x47b1e98), 0xc026197d70}, {0x47df230, 0xc0031e2dc0})\n\t/home/runner/work/vega/vega/core/processor/abci.go:582 +0x5e\[ncode.vegaprotocol.io/vega/core/processor.NewApp.(*App).SendTransactionResult.func28({0x47b1e98](http://ncode.vegaprotocol.io/vega/core/processor.NewApp.(*App).SendTransactionResult.func28(%7B0x47b1e98), 0xc026197d70}, {0x47df230?, 0xc0031e2dc0?})\n\t/home/runner/work/vega/vega/core/processor/abci.go:645 +0x5d\[ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc0113e4180](http://ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc0113e4180), {0xc0029c6428?, 0xd7b479?}, 0xc007612cc0)\n\t/home/runner/work/vega/vega/core/blockchain/abci/abci.go:179 +0x622\[ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0x3632e60](http://ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0x3632e60)?, {0x47b1f78?, 0x6d08c60?}, 0x7f8a9451e5b8?)\n\t/home/runner/work/vega/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25\[ngithub.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0xc008863e20](http://ngithub.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0xc008863e20)?, {0x47b1f78?, 0x6d08c60?}, 0xc0?)\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/abci/client/local_client.go:185 +0xd0\[ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0xc0084bc408](http://ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0xc0084bc408), {0x47b1f78, 0x6d08c60}, 0x1?)\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/proxy/app_conn.go:104 +0x16d\[ngithub.com/cometbft/cometbft/state.(*BlockExecutor).applyBlock(_](http://ngithub.com/cometbft/cometbft/state.(*BlockExecutor).applyBlock(_), {{{0xb, 0x1}, {0xc011519c80, 0x7}}, {0xc001df7480, 0x1a}, 0x1, 0xb99b69, {{0xc018777b00, ...}, ...}, ...}, ...)\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/state/execution.go:224 +0x577\[ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyVerifiedBlock(...)](http://ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyVerifiedBlock(...))\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/state/execution.go:202\[ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc005ed6700](http://ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc005ed6700), 0xb99b6a)\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/consensus/state.go:1772 +0xbba\[ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc005ed6700](http://ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc005ed6700), 0xb99b6a)\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/consensus/state.go:1682 +0x2f6\[ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()](http://ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1())\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/consensus/state.go:1617 +0x9c\[ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc005ed6700](http://ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc005ed6700), 0xb99b6a, 0x0)\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/consensus/state.go:1655 +0xc5b\[ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc005ed6700](http://ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc005ed6700), 0xc02041a0d0, {0xc00d2b37d0, 0x28})\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/consensus/state.go:2335 +0x1d4d\[ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc005ed6700](http://ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc005ed6700), 0xc02041a0d0, {0xc00d2b37d0?, 0xc0029c7c08?})\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/consensus/state.go:2067 +0x26\[ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc005ed6700](http://ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc005ed6700), {{0x4788ac0, 0xc0175b27f8}, {0xc00d2b37d0, 0x28}})\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/consensus/state.go:929 +0x3ce\[ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc005ed6700](http://ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc005ed6700), 0x0)\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/consensus/state.go:836 +0x3d1\ncreated by [github.com/cometbft/cometbft/consensus.(*State).OnStart](http://github.com/cometbft/cometbft/consensus.(*State).OnStart) in goroutine 370\n\t/home/runner/go/pkg/mod/github.com/cometbft/cometbft@v0.38.8/consensus/state.go:398 +0x10c\n"}`

### Observed behaviour

the problem is that when the curves are generated the lower and upper bound is equal. this in turn is caused by the fact that:
market decimals = 7
asset decimals = 6
price factor = 0.1
so given the amm params are:
submit_amm:{market_id:"550ef1aefe9de32e04701c4a30f049016e9cc223cf2de37bbdfda59e3b5e1c44" commitment_amount:"10000000000000" slippage_tolerance:"0.5" concentrated_liquidity_parameters:
{upper_bound:"97" lower_bound:"80" base:"88" leverage_at_upper_bound:"20.0" leverage_at_lower_bound:"20.0"} proposed_fee:"0.0001"} 
so:
base, _ := num.UintFromDecimal(p.Parameters.Base.ToDecimal().Mul(p.priceFactor))
lowerBound, _ := num.UintFromDecimal(p.Parameters.LowerBound.ToDecimal().Mul(p.priceFactor))
base = int(80*0.1) = 8
lowerBound = int(88*0.1) = 8
then we have:
term2 := sqrt(high).Sub(sqrt(low))
lu := term1.Div(term2)
term2 is going to be 0 which will cause the division by 0

### Expected behaviour

no division by zero.

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

develop

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ze97286**
…rated

Closes #11442

### CODE REVIEW

File: core/execution/future/market.go [hunk 1]
```diff
@@ -5451,6 +5468,10 @@ func (m *Market) SubmitAMM(ctx context.Context, submit *types.SubmitAMM, determi
 
 	// create the AMM curves but do not confirm it with the engine
 	var order *types.Order
+	if err := VerifyAMMBounds(submit.Parameters.Base, submit.Parameters.LowerBound, submit.Parameters.UpperBound, m.priceFactor); err != nil {
```
Comment (wwestgarth) [inline core/execution/future/market.go:5471]: can you through the same check in `AmendAMM()` too?

Comment (ze97286) [reply core/execution/future/market.go:5471]: added

**Review by jeremyletang — APPROVED** [review]
