### PR TITLE
calculate auciton closing time based on vote close

### LINKED ISSUE #8451: Invalid auction duration calculation on new proposal
The opening auction duration is incorrectly calculated for new market proposal.

It is at the moment the time between proposal submission and enactment.
It should be from the closing time of the proposal and until the enactmenet of  the proposal.

### PR DESCRIPTION
**Pull request by EVODelavega**
Quick fix closing 

close #8451

### CODE REVIEW

File: core/execution/engine.go [hunk 1]
```diff
@@ -369,8 +369,8 @@ func (e *Engine) IsEligibleForProposerBonus(marketID string, value *num.Uint) bo
 }
 
 // SubmitMarket submits a new market configuration to the network.
-func (e *Engine) SubmitMarket(ctx context.Context, marketConfig *types.Market, proposer string) error {
-	return e.submitOrRestoreMarket(ctx, marketConfig, proposer, true)
+func (e *Engine) SubmitMarket(ctx context.Context, marketConfig *types.Market, proposer string, oos time.Time) error {
```
Comment (zale144) [inline core/execution/engine.go:372]: `oos` is opening auction start? Shouldn't it be `oas` then? Or maybe something more obvious like `auctionStart` or whatever?

**Review by zale144 — DISMISSED** [review]

**Review by jeremyletang — APPROVED** [review]
