### PR TITLE
Remove nested transactions, connection source can't handle them

### LINKED ISSUE #11136: [Bug]: Data node's market cache can get out of sync with DB values
### Problem encountered

When running the test `test_liquidity_fee_settings_spots[Average-0.2-Margin_cost-0.1]` a lot of times we sometimes see a failure where the data returned from the `GetMarket()` endpoint does not show updated values:
https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/54847/tests

What the test is doing is submitting a new LP to the market which should update the markets liquidity-fee, and then keeps pinging the `GetMarket()` endpoint untill it sees an update.

Now the sqlstore has a in-memory cached aimed at reducing the load on the DB during market queries:
https://github.com/vegaprotocol/vega/blob/develop/datanode/sqlstore/markets.go#L175-L183

This cache gets cleared after when the block-scoped transaction commits the new values to the DB:
https://github.com/vegaprotocol/vega/blob/develop/datanode/sqlstore/markets.go#L147-L156

By adding more logs what I can see is the following happening:
- A update market event is upserting into the DB
- in the `AfterCommit()` hook we clear the market cache
- _very quickly_ a `GetMarket()` call is made
- it queries the DB for the market and gets the **old values for the market**(!?)
- the old values are added to the cache
- querying the DB again returns the new values, but the cache now storing the old values

Logs for this can be found here:
https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/54847/artifact/testnet/logs/testnet-nodeset-full-2-full/data-node-2.stdout-2024-04-16T15%3A30%3A04Z.log

The important section is here:
```
[Query before the update event is recieved, cache is 0.03 for fee, DB has 0.3]
2024-04-16T15:50:27.170Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:186	GetById pre-lock	{"tid": 78, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38"}
2024-04-16T15:50:27.171Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:189	GetById in-lock	{"tid": 78, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38"}
2024-04-16T15:50:27.171Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:193	GetById pulling from postgres	{"tid": 78, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38"}
2024-04-16T15:50:27.172Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:203	GetById value from DB	{"tid": 78, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.3"}
2024-04-16T15:50:27.172Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:204	GetById returning cached market	{"tid": 78, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.3"}

[The upsert of the new market data with fee 0.2]
2024-04-16T15:50:27.340Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:140	Upsert	{"tid": 483, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}
2024-04-16T15:50:27.341Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:150	Upsert complete	{"tid": 483, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}
2024-04-16T15:50:27.341Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:140	Upsert	{"tid": 721, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}
2024-04-16T15:50:27.342Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:150	Upsert complete	{"tid": 721, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}

[The after commit hook clearing the cache]
2024-04-16T15:50:27.343Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:153	AfterCommit waiting for lock	{"tid": 483, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}
2024-04-16T15:50:27.343Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:157	AfterCommit in lock	{"tid": 483, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}
2024-04-16T15:50:27.344Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:160	AfterCommit cache entry removed	{"tid": 483, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}
2024-04-16T15:50:27.344Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:153	AfterCommit waiting for lock	{"tid": 721, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}
2024-04-16T15:50:27.344Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:157	AfterCommit in lock	{"tid": 721, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}
2024-04-16T15:50:27.344Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:160	AfterCommit cache entry removed	{"tid": 721, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}

[The next GetMarket query populating the cache with the old value of 0.03]
2024-04-16T15:50:27.375Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:186	GetById pre-lock	{"tid": 706, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38"}
2024-04-16T15:50:27.375Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:189	GetById in-lock	{"tid": 706, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38"}
2024-04-16T15:50:27.375Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:193	GetById pulling from postgres	{"tid": 706, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38"}
2024-04-16T15:50:27.376Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:209	GetById populating cache	{"tid": 706, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.3"}

[The next GetMarket query with the old value of 0.03 in the cache, but the correct value of 0.02 in the DB]
2024-04-16T15:50:27.580Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:186	GetById pre-lock	{"tid": 678, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38"}
2024-04-16T15:50:27.580Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:189	GetById in-lock	{"tid": 678, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38"}
2024-04-16T15:50:27.580Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:193	GetById pulling from postgres	{"tid": 678, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38"}
2024-04-16T15:50:27.581Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:203	GetById value from DB	{"tid": 678, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.2"}
2024-04-16T15:50:27.581Z	INFO	datanode.start.persistentPre.connection-source	sqlstore/markets.go:204	GetById returning cached market	{"tid": 678, "mid": "74e286cfbe8c89820cad0734ac54895eb3d49c6b2c9f1688e04f472fe011cf38", "fee": "0.3"}
```

 The concern here is that there cache is never refreshed until the market is updated again, so it could remain stale for a long time.

### Observed behaviour

Market cache in the data-node can become out of sync with the market data in the DB.

### Expected behaviour

Market cache in the data-node is in sync with the data in the data-base

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

develop

### Failing test

_No response_

### Jenkins run

_No response_

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by EVODelavega**
Closes #11136

### CODE REVIEW

File: datanode/service/market.go [hunk 1]
```diff
@@ -55,8 +55,8 @@ func (m *Markets) Upsert(ctx context.Context, market *entities.Market) error {
 		return err
 	}
 	m.cacheLock.Lock()
-	if market.State == entities.MarketStateSettled || market.State == entities.MarketStateRejected {
-		// a settled or rejected market can be safely removed from this map.
+	if market.State == entities.MarketStateSettled || market.State == entities.MarketStateRejected || market.State == entities.MarketStateCancelled {
```
Comment (EVODelavega) [inline datanode/service/market.go:58]: @ze97286 This seems to be specific to spot markets, I can't really see why cancelled shouldn't be included here, so I added it, but would be good to get confirmation.

Comment (ze97286) [reply datanode/service/market.go:58]: I think that's fine

**Review by wwestgarth — APPROVED** [review]
