### PR TITLE
fix: do not pay referal discount if set is not eligible

### LINKED ISSUE #9775: [Bug]: referral program taker fee discounts on trade event where referrer below min stake
### Problem encountered

referee taker fee discount showing on trade when referrer has no stake

> If a referrer removes sufficient stake to not meet the required tokens, the referral set should not be eligible for the following referral benefits:
>         - the referrer should not be rewarded for any referee taker fees (0083-RFPR-018).
>         - all referees should not receive any discount on their taker fees (0083-RFPR-019).

### Observed behaviour

taker fee discount showing on `BUS_EVENT_TYPE_TRADE`

`{"id":"331-19","block":"F99A9664639E9818AD68F816805485F5D1CD6F603F52BF3AB936CF64186FB354","type":"BUS_EVENT_TYPE_TRADE","trade":{"id":"e4b28f5ecb65cac7b09a38be1d29bd32a66fd7411516aa3f047ac6ecfebcaed4","marketId":"bcd520534a681052235c1dd44c2d266a70accf4a8b680e753e8d1ac5dd3e25c6","price":"100000000","size":"5000000","buyer":"14cfcc3571fa6425f4dc0b6112595d6e6f13cd390c7028c9799eaa9c805368e1","seller":"a8fe5ebc9d8aa68de87e37bac20f38d85297de1ab421456fcd35727ad0c1dcc6","aggressor":"SIDE_SELL","buyOrder":"1c467375309cd6080aef927cb80878bba1cf6f2ffa08b31ce34b331de1753d03","sellOrder":"41162b6f29c5dbde7ffe0d81f6e68bf1f673f70111d6ed7c678a5778578e291f","timestamp":"1697192450878512569","type":"TYPE_DEFAULT","buyerFee":{"makerFee":"0","infrastructureFee":"0","liquidityFee":"0","makerFeeVolumeDiscount":"0","infrastructureFeeVolumeDiscount":"0","liquidityFeeVolumeDiscount":"0","makerFeeReferrerDiscount":"0","infrastructureFeeReferrerDiscount":"0","liquidityFeeReferrerDiscount":"0"},"sellerFee":{"makerFee":"199600000000000000000","infrastructureFee":"49900000000000000000","liquidityFee":"14970000000000000000000","makerFeeVolumeDiscount":"0","infrastructureFeeVolumeDiscount":"0","liquidityFeeVolumeDiscount":"0","makerFeeReferrerDiscount":"400000000000000000","infrastructureFeeReferrerDiscount":"100000000000000000","liquidityFeeReferrerDiscount":"30000000000000000000"}},"version":1,"chainId":"testnet-001","txHash":"9A0736165C01FBF8E6FDC911D887EC64977FAE7EC537B5779CF918AE15D22369"}`

### Expected behaviour

i would expect the `BUS_EVENT_TYPE_TRADE` to show taker fee discounts of 0

### Steps to reproduce

```bash
1. run system-test `test_referral_set_referrer_bug`
```

### Software version

dev branch

### Failing test

test_referral_set_referrer_bug

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/23171/

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jeremyletang**
close #9775

### CODE REVIEW

File: core/referral/engine.go [hunk 1]
```diff
@@ -558,6 +558,10 @@ func (e *Engine) computeFactorsByReferee(ctx context.Context, epoch uint64, take
 		e.factorsByReferee[party] = refereeStats
 		setStats.RefereesStats[party] = refereeStats
 
+		if e.isSetEligible(setID) != nil {
```
Comment (ze97286) [inline core/referral/engine.go:561]: why go all the way to here rather than do this in line 537 for example?

Comment (jeremyletang) [reply core/referral/engine.go:561]: Because I wanted these:
```
 558        e.factorsByReferee[party] = refereeStats
 559        setStats.RefereesStats[party] = refereeStats
```
To be set with set.

Comment (ze97286) [reply core/referral/engine.go:561]: but why? they'll just be 0 won't they?

Comment (jeremyletang) [reply core/referral/engine.go:561]: yes, but we will want the taker volume stats to be stored accross the epoch and sent to the datanode.

Comment (jeremyletang) [reply core/referral/engine.go:561]: basically we still want the refereeStats to be updated.

**Review by EVODelavega — APPROVED** [review]

**Review by ze97286 — APPROVED** [review]
