### PR TITLE
10155 next closeout

### LINKED ISSUE #10155: [Feature]: Add next network closeout time to market data
0012-POSR-015: It is possible to check the time of the next liquidation trade attempt in any market via the API.

To do this, we should add the a `nextCloseout` field to market data

### LINKED ISSUE #10168: [Bug] null pointer crasher when running market sim
A new one:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1057a8124]

goroutine 38279 [running]:
code.vegaprotocol.io/vega/core/collateral.(*Engine).getTransferRequest(0x1400031a700, 0x0, 0x14006f65400, 0x14006f65310, 0x1400afd6f00)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/collateral/engine.go:2660 +0x34
code.vegaprotocol.io/vega/core/collateral.(*Engine).mtmOrFundingSettlement(0x1400031a700, {0x10839adb8, 0x140029df380}, {0x14001ed0c40, 0x40}, {0x140044c1600, 0x6, 0x2c}, {0x14001ed0840, 0x40}, ...)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/collateral/engine.go:1526 +0x2688
code.vegaprotocol.io/vega/core/collateral.(*Engine).MarkToMarket(0x14004756ce0?, {0x10839adb8?, 0x140029df380?}, {0x14001ed0c40?, 0x6?}, {0x140044c1600?, 0x1400472d700?, 0x20?}, {0x14001ed0840?, 0x14004731b00?})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/collateral/engine.go:1315 +0x38
code.vegaprotocol.io/vega/core/execution/future.(*Market).collateralAndRisk(0x1400069eb00, {0x10839adb8, 0x140029df380}, {0x140044c1600, 0x6, 0x2c})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/execution/future/market.go:2631 +0x15c
code.vegaprotocol.io/vega/core/execution/future.(*Market).confirmMTM(0x1400069eb00, {0x10839adb8, 0x140029df380}, 0x0)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/execution/future/market.go:2302 +0x2c8
code.vegaprotocol.io/vega/core/execution/future.(*Market).checkNetwork(0x1400069eb00, {0x10839adb8, 0x140029df380}, {0x1400d46e640?, 0x14004746b38?, 0x0?})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/execution/future/liquidation.go:90 +0x38c
code.vegaprotocol.io/vega/core/execution/future.(*Market).OnTick(0x1400069eb00, {0x10839adb8, 0x140029df380}, {0x40?, 0x0?, 0x0?})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/execution/future/market.go:894 +0x2a0
code.vegaprotocol.io/vega/core/execution.(*Engine).OnTick(0x14000354580, {0x10839adb8, 0x140029df380}, {0x1?, 0x1083b54f0?, 0x0?})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/execution/engine.go:1307 +0x398
code.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/vegatime/service.go:107
code.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0x140002a0500, {0x10839adb8, 0x140029df380}, {0x40?, 0x10a4e5518?, 0x0?})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/vegatime/service.go:80 +0x26c
code.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(0x14000c7d880, 0xc94, {0x1400d46e440, 0x40}, {0x1400d46e440?, 0x0?, 0x0?}, {0x0, 0x0}, {0x10a4e5518?, ...})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/processor/abci.go:963 +0x794
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0x1400020a000, {0x108185c80?, 0x1?}, 0x14003495ec0)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/blockchain/abci/abci.go:162 +0x330
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0x1400c3fd680?, {0x10839ad48?, 0x14000190010?}, 0x14001d66e58?)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x30
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).processBlock(0x140002c8120)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/blockchain/nullchain/nullchain.go:198 +0x448
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).ForwardTime(0x140002c8120, 0x77359400)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/blockchain/nullchain/nullchain.go:275 +0x198
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime.func1()
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/blockchain/nullchain/server.go:132 +0x2c
created by code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/blockchain/nullchain/server.go:131 +0x1ec
```
[replay.zip](https://github.com/vegaprotocol/vega/files/13451314/replay.zip)

### LINKED ISSUE #10175: [Bug]: Panic - "err": "There's less MTM wins than losses, even accounting for decimals"
### Problem encountered

panic in system-test nightly run

### Observed behaviour

`2023-11-25T02:38:12.196Z	ERROR	tendermint	consensus/state.go:800	CONSENSUS FAILURE!!!	{"err": "There's less MTM wins than losses, even accounting for decimals", "stack": "goroutine 250 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:800 +0x4c\npanic({0x4c6c600, 0xc004a69a00})\n\t/usr/local/go/src/runtime/panic.go:884 +0x213\ngo.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc003ba2e00?})\n\t/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65\ngo.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc003445860, {0xc00548cd00, 0x2, 0x2})\n\t/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec\ngo.uber.org/zap.(*Logger).Panic(0xc003cf2760?, {0x5734ab6?, 0xc003cf28a0?}, {0xc00548cd00, 0x2, 0x2})\n\t/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59\ncode.vegaprotocol.io/vega/core/settlement.(*Engine).SettleMTM(0xc004241a00, {0x5df99f0, 0xc00470fbf0}, 0xc0057889a0, {0xc004d7be00, 0x6, 0x7f881c0afb78?})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/settlement/engine.go:387 +0x18aa\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).confirmMTM(0xc0028ba580, {0x5df99f0, 0xc00470fbf0}, 0x0)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/future/market.go:2290 +0x207\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).BlockEnd(0xc0028ba580, {0x5df99f0?, 0xc00470fbf0?})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/future/market.go:968 +0x48e\ncode.vegaprotocol.io/vega/core/execution.(*Engine).BlockEnd(0xc000143080?, {0x5df99f0, 0xc00470fbf0})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/engine.go:1479 +0x46\ncode.vegaprotocol.io/vega/core/processor.(*App).OnEndBlock(0xc000276700, 0x7f881c0aa4f8?)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:924 +0x7c2\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc000f1bc80, {0x7f8848411d28?, 0x30?}, 0xc00127b2c0)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/blockchain/abci/abci.go:183 +0x966\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0xc00158c548?, {0x5df9980?, 0xc00007e148?}, 0x5075d80?)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x2b\ngithub.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0x5de6430?, {0x5df9980?, 0xc00007e148?}, 0xc00127b2c0?)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/abci/client/local_client.go:185 +0xdb\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0xc0004a36b0, {0x5df9980, 0xc00007e148}, 0x6?)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/proxy/app_conn.go:104 +0x102\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc000d46eb0, 0x6}}, {0xc000d46ec0, 0xb}, 0x1, 0x240f, {{0xc004b85c80, ...}, ...}, ...}, ...)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/state/execution.go:215 +0x686\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc00056ea80, 0x2410)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:1770 +0xb9d\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc00056ea80, 0x2410)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:1681 +0x2ff\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:1616 +0xaa\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc00056ea80, 0x2410, 0x1)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:1654 +0xccf\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc00056ea80, 0xc0040f7450, {0xc0005d20f0, 0x28})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:2323 +0x1cff\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc00056ea80, 0xc0040f7450, {0xc0005d20f0?, 0xc00158dc08?})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:2055 +0x2c\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc00056ea80, {{0x5dd0f20, 0xc005b2a048}, {0xc0005d20f0, 0x28}})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:928 +0x3ff\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc00056ea80, 0x0)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:835 +0x3f0\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.0/consensus/state.go:397 +0x12d\n"}`

### Expected behaviour

no panic

### Steps to reproduce

```bash
1. system-test nightly run on Saturday reported the issue but did not occur on Sunday/Monday so not sure of the cause
```

### Software version

dev branch

### Failing test

_No response_

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-nightly/111/

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by EVODelavega**
Closes #10155 

close https://github.com/vegaprotocol/vega/issues/10168

close https://github.com/vegaprotocol/vega/issues/10175

### CODE REVIEW

**Review by candida-d — DISMISSED** [review]

**Review by peterbarrow — APPROVED** [review]

File: core/execution/future/liquidation.go [hunk 1]
```diff
@@ -78,16 +78,15 @@ func (m *Market) checkNetwork(ctx context.Context, now time.Time) error {
 	}
 	// Now that the fees have been taken care of, get the current last traded price:
 	lastTraded := m.getLastTradedPrice()
+	tradeType := types.TradeTypeNetworkCloseOutGood
 	// now handle the confirmation like you would any other order/trade confirmation
-	m.handleConfirmation(ctx, conf)
+	m.handleConfirmation(ctx, conf, &tradeType)
```
Comment (ze97286) [inline core/execution/future/liquidation.go:83]: a bit nitpick: you could have handleConfirmation take TradeType and pass by default TradeTypeDefault rather than passing a pointer and nil

Comment (EVODelavega) [reply core/execution/future/liquidation.go:83]: It's been a while, but I decided to pass a pointer here because I found it a bit clunky to pass the unspecified trade type value to this call in all the places where this function is being called. To my eye, having the other callers pass in `nil` communicates that the argument is not applicable, whereas passing in some other value could suggest that  `handleConfirmation(ctx, conf, <for trades of this type>)` or something like that. I also feel a bit conflicted about values being passed around that, depending on the specific value result in different behaviour (ie unspecified == ignore, `TradeTypeNetworkCloseoutGood` == set the trade type accordingly, values other than those two == ??

Because of that, I just thought either nil -> ignore, not nil -> set the trade type made more sense

**Review by ze97286 — APPROVED** [review]
