### PR TITLE
fix: set market ID generator when doing perps funding settlement

### LINKED ISSUE #9086: [Perps]: CONSENSUS FAILURE - invalid memory address or nil pointer dereference
When deploying a perps market to devenet and enabling trading the network panicked wit the following logs:"

`
Aug 15 15:23:46 n01.devnet1.vega.rocks visor[443288]: 2023-08-15T15:23:46.307Z        ERROR        tendermint        consensus/state.go:732        CONSENSUS FAILURE!!!        {"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 472 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x4c\npanic({0x3098c40, 0x5bdf350})\n\t/usr/local/go/src/runtime/panic.go:884 +0x213\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).resolveClosedOutParties(0xc000d7d680, {0x3edc740, 0xc0065fe7e0}, {0xc003366240?, 0x2, 0x2})\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/future/market.go:2299 +0x1e71\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).handleRiskEvts(0xc000d7d680, {0x3edc740, 0xc0065fe7e0}, {0xc0065fea50?, 0x3?, 0xc0068d81c0?})\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/future/market.go:2104 +0x570\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).settlementDataPerp(0xc000d7d680, {0x3edc740, 0xc0065fe7e0}, 0xc0036ec648)\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/future/market.go:3791 +0x75c\ncode.vegaprotocol.io/vega/core/products.(*Perpetual).handleSettlementCue(0xc0006601c0, {0x3edc740, 0xc0065fe7e0}, 0x177b97d4beefca00)\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/products/perpetual.go:365 +0x502\ncode.vegaprotocol.io/vega/core/products.(*Perpetual).receiveSettlementCue(0xc0006601c0, {0x3edc740, 0xc0065fe7e0}, {{0x0, 0x0, 0x0}, 0xc0065fe810, 0x0})\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/products/perpetual.go:308 +0x127\ncode.vegaprotocol.io/vega/core/datasource/spec.(*Engine).BroadcastData(0xc000db4e10, {0x3edc740, 0xc0065fe7e0}, {{0x0, 0x0, 0x0}, 0xc0065fe810, 0x0})\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/datasource/spec/engine.go:132 +0x7f3\ncode.vegaprotocol.io/vega/core/datasource/spec.(*Builtin).OnTick(0xc00061a190, {0x3edc740, 0xc0065fe7e0}, {0x1?, 0x3ef6678?, 0x0?})\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/datasource/spec/builtin.go:53 +0x285\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/vegatime/service.go:104\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc000db8c80, {0x3edc740, 0xc0065fe7e0}, {0x40?, 0x2f3a040?, 0x0?})\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/vegatime/service.go:77 +0x24f\ncode.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(_, {{0xc006e649c0, 0x20, 0x20}, {{0xb, 0x1}, {0xc0057c10e0, 0x19}, 0x2a2c, {0x1c4c5646, ...}, ...}, ...})\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/processor/abci.go:797 +0x747\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).BeginBlock(_, {{0xc006e649c0, 0x20, 0x20}, {{0xb, 0x1}, {0xc0057c10e0, 0x19}, 0x2a2c, {0x1c4c5646, ...}, ...}, ...})\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/blockchain/abci/abci.go:46 +0x75\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).BeginBlock(_, {{0xc006e649c0, 0x20, 0x20}, {{0xb, 0x1}, {0xc0057c10e0, 0x19}, 0x2a2c, {0x1c4c5646, ...}, ...}, ...})\n\t/jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/vega/commands/node/app_wrapper.go:64 +0x55\ngithub.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc006e649c0, 0x20, 0x20}, {{0xb, 0x1}, {0xc0057c10e0, 0x19}, 0x2a2c, {0x1c4c5646, ...}, ...}, ...})\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/abci/client/local_client.go:280 +0x118\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc006e649c0, 0x20, 0x20}, {{0xb, 0x1}, {0xc0057c10e0, 0x19}, 0x2a2c, {0x1c4c5646, ...}, ...}, ...})\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/proxy/app_conn.go:81 +0x55\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x3eda910?, 0xc000131fc8}, {0x3eedd60, 0xc000def620}, 0xc005054d20, {0x3efedf0, 0xc000305728}, 0x2a2b?)\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:307 +0x51d\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc002c53f90, 0x7}}, {0xc002c902c0, 0x19}, 0x1, 0x2a2b, {{0xc00528c080, ...}, ...}, ...}, ...)\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:140 +0x171\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc0029fbc00, 0x2a2c)\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1661 +0xafd\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc0029fbc00, 0x2a2c)\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1570 +0x2ff\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1505 +0xaa\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc0029fbc00, 0x2a2c, 0x0)\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1543 +0xccf\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc0029fbc00, 0xc0034672c0, {0xc004b25c80, 0x28})\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2165 +0x18dc\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc0029fbc00, 0xc0034672c0, {0xc004b25c80?, 0xc001ba3c08?})\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0029fbc00, {{0x3eb9440, 0xc0058f2d90}, {0xc004b25c80, 0x28}})\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x3ff\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc0029fbc00, 0x0)\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x3f0\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0x12d\n"}`

### PR DESCRIPTION
**Pull request by wwestgarth**
closes #9086 

Trying to close out parties (I'm guessing because of the wild funding rate being calculated due to the decimal point differences) and we weren't initialising an id generator.

### CODE REVIEW

**Review by jeremyletang — APPROVED** [review]

File: core/execution/future/market.go [hunk 1]
```diff
@@ -3750,6 +3750,13 @@ func (m *Market) settlementData(ctx context.Context, settlementData *num.Numeric
 func (m *Market) settlementDataPerp(ctx context.Context, settlementData *num.Numeric) {
 	m.mu.Lock()
 	defer m.mu.Unlock()
+
+	_, blockHash := vegacontext.TraceIDFromContext(ctx)
```
Comment (jeremyletang) [inline core/execution/future/market.go:3754]: would be good actually to add the market ID in here just in case too.
