### PR TITLE
fix: initialise sla parameter in checkpoint

### LINKED ISSUE #9341: [Bug]: Mainnet checkpoint cannot be loaded into current vega version
### Problem encountered

There is a panic when we want to start current vega with a mainnet checkpoint.

The checkpoint is here: https://jenkins.vega.rocks/job/common/job/system-tests-lnl-mainnet/21/artifact/system-tests/tests/LNL/checkpoint-resume.json

### Observed behaviour

Panic after checkpoint load

### Expected behaviour

Network should start normally

### Steps to reproduce

```bash
1. Download any mainnet checkpoint
2. Load into core
3. Try to start node
```

### Software version

develop

### Failing test

lnl-pipeline

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-lnl-mainnet/21

### Configuration used

```shell
Please see capsule.hcl for reference: https://jenkins.vega.rocks/job/common/job/system-tests-lnl-mainnet/21/artifact/testnet/
```

### Relevant log output

```shell
2023-09-08T15:24:53.078Z	PANIC	core.protocol.governance	governance/checkpoint.go:108	Failed to convert proposal into market	{"error": "liquidity provision SLA must be provided, PROPOSAL_ERROR_INVALID_SLA_PARAMS"}


More logs is here: https://jenkins.vega.rocks/job/common/job/system-tests-lnl-mainnet/21/artifact/testnet/logs/vega-mainnet-nodeset-full-13-full/visor-13-with-vega-data-node.stdout-2023-09-08T15%3A24%3A32Z.log
```

### PR DESCRIPTION
**Pull request by jeremyletang**
close #9341

### CODE REVIEW

**Review by AnExsomnis — DISMISSED** [review]

File: core/governance/checkpoint.go [hunk 1]
```diff
@@ -103,6 +104,15 @@ func (e *Engine) Load(ctx context.Context, data []byte) error {
 			}
 			enct.current = prop.Terms.EnactmentTimestamp
 
+			if prop.NewMarket().Changes.LiquiditySLAParameters == nil {
+				prop.NewMarket().Changes.LiquiditySLAParameters = &types.LiquiditySLAParams{
```
Comment (ze97286) [inline core/governance/checkpoint.go:108]: don't you want to reuse the default set you already have somewhere else?

Comment (jeremyletang) [reply core/governance/checkpoint.go:108]: well, it's the same ones, it's just that when loading a snapshot this is done at another time than when loading a checkpoint.

Comment (ze97286) [reply core/governance/checkpoint.go:108]: what I mean is define once this: 

```
migrationSLAParams = &types.LiquiditySLAParams{
			PriceRange:                  num.MustDecimalFromString("0.05"),
			CommitmentMinTimeFraction:   num.MustDecimalFromString("0.95"),
			PerformanceHysteresisEpochs: 1,
			SlaCompetitionFactor:        num.MustDecimalFromString("0.90"),
		}

and use in both places

prop.NewMarket().Changes.LiquiditySLAParameters = migrationSLAParams
...
mkt.LiquiditySLAParams = migrationSLAParams
```

**Review by ze97286 — DISMISSED** [review]

**Review by EVODelavega — APPROVED** [review]
