### PR TITLE
fix: net params sent on a closed channel

### LINKED ISSUE #9882: Do not send to channel when close in coreapi
We try to send data to a closed  channel. We are missing the fuse box in front of the send process.

```
panic: send on closed channel 
goroutine 229 [running]: 
code.vegaprotocol.io/vega/core/coreapi/services.(*NetParams).Push(0xc001829600, {0xc002eff4f0?, 0x1, 0x0?}) 
        /home/runner/work/vega/vega/core/coreapi/services/netparams.go:74 +0x125 
code.vegaprotocol.io/vega/core/broker.(*Broker).startSending.func1(0xc00481f4a0, 0x1a) 
        /home/runner/work/vega/vega/core/broker/broker.go:227 +0x5fb 
created by code.vegaprotocol.io/vega/core/broker.(*Broker).startSending 
        /home/runner/work/vega/vega/core/broker/broker.go:201 +0x5cf
```

## Solution

We should:
1. have a wait.group waiting in front of the close([a.ch](http://a.ch/))
2. verification of the closed state, in front of the consume() function

## Testing

According to @wwestgarth , it's liekly this code path is hit when we have an unknown netparams in the genesis file. That should help with testing.

### PR DESCRIPTION
**Pull request by guoguojin**
Closes #9882

### CODE REVIEW

**Review by peterbarrow — DISMISSED** [review]

File: core/coreapi/services/netparams.go [hunk 1]
```diff
@@ -49,13 +50,28 @@ func NewNetParams(ctx context.Context) (netParams *NetParams) {
...
 
 func (a *NetParams) consume() {
-	defer func() { close(a.ch) }()
+	defer func() {
+		// clear the channel before we close it
+		// can't use a WaitGroup as suggested because if we get to this point
+		// if the Push is still in progress and the queue is full, we'll
+		// end up in a situation where we're waiting for the queue to empty, but
+		// no consumer.
+		for range a.ch {
```
Comment (karlem) [inline core/coreapi/services/netparams.go:59]: Question, could you not use buffered channel instead?

Comment (guoguojin) [reply core/coreapi/services/netparams.go:59]: I'm pretty sure the channel is already buffered.

**Review by ValentinTrinque — APPROVED** [review]
