### PR TITLE
fix: fee calculation in governance auction

### LINKED ISSUE #10669: [Bug]: panic on spot market suspend via governance
### Problem encountered

with open orders on a spot market, suspend it via governance to get a panic

`2024-02-14T15:03:21.706Z	ERROR	tendermint	consensus/state.go:800	CONSENSUS FAILURE!!!	{"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 260 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:800 +0x46\npanic({0x517caa0?, 0x83b4b80?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f\ncode.vegaprotocol.io/vega/core/execution/spot.(*Market).calculateFees(0xc011c83680, {0xc00f11f980, 0x40}, 0xa, 0xc0133acde0, 0x1)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/spot/market.go:2802 +0x18d\ncode.vegaprotocol.io/vega/core/execution/spot.(*Market).processFeesTransfersOnEnterAuction(0xc011c83680, {0x61c2328, 0xc00f8e0150})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/spot/market.go:2619 +0x5f5\ncode.vegaprotocol.io/vega/core/execution/spot.(*Market).enterAuction(0xc011c83680, {0x61c2328, 0xc00f8e0150})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/spot/market.go:847 +0x4c5\ncode.vegaprotocol.io/vega/core/execution/spot.(*Market).UpdateMarketState(0xc011c83680, {0x61c2328, 0xc00f8e0150}, 0xc00f0b01e0)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/spot/market.go:490 +0x505\ncode.vegaprotocol.io/vega/core/execution.(*Engine).UpdateMarketState(0xc0005fdb80?, {0x61c2328, 0xc00f8e0150}, 0xc00f0b01e0)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/engine.go:612 +0x63\ncode.vegaprotocol.io/vega/core/processor.(*App).enactMarketStateUpdate(0xc000f23180, {0x61c2328, 0xc00f8e0150}, 0xc00db098c0)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:2413 +0x356\ncode.vegaprotocol.io/vega/core/processor.(*App).onTick(0xc000f23180, {0x61c2328, 0xc00f8e0150}, {0x1?, 0xc01242d4d0?, 0x0?})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:2260 +0xeae\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/vegatime/service.go:107\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc001910600, {0x61c2328, 0xc00f8e0150}, {0x40?, 0x88d4360?, 0x0?})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/vegatime/service.go:80 +0x263\ncode.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(0xc000f23180, 0xfe, {0xc012a3e6c0, 0x40}, {0x1d0fbab?, 0x28?, 0x0?}, {0xc00f8da330, 0x28}, {0x88d4360, ...})\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:1015 +0x956\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc0009c0fc0, {0xc00d30e530?, 0x1cc5465?}, 0xc00f8d0d80)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/core/blockchain/abci/abci.go:162 +0x449\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0x4fb5600?, {0x61c2408?, 0x88d4360?}, 0x7f122e1ca3c8?)\n\t/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25\ngithub.com/cometbft/cometbft/abci/client.(*localClient).FinalizeBlock(0xc00d30e5d0?, {0x61c2408?, 0x88d4360?}, 0xc0?)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/abci/client/local_client.go:185 +0xd0\ngithub.com/cometbft/cometbft/proxy.(*appConnConsensus).FinalizeBlock(0xc000a13440, {0x61c2408, 0x88d4360}, 0x1?)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:104 +0x16d\ngithub.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc00c86c440, 0x6}}, {0xc00c86c450, 0xb}, 0x1, 0xfd, {{0xc00fa24a80, ...}, ...}, ...}, ...)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/state/execution.go:213 +0x622\ngithub.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc00c87a380, 0xfe)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1770 +0xb7d\ngithub.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc00c87a380, 0xfe)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1681 +0x2f6\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit.func1()\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1616 +0x9c\ngithub.com/cometbft/cometbft/consensus.(*State).enterCommit(0xc00c87a380, 0xfe, 0x0)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:1654 +0xc5b\ngithub.com/cometbft/cometbft/consensus.(*State).addVote(0xc00c87a380, 0xc00e9c5380, {0xc00c859800, 0x28})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2324 +0x1d4d\ngithub.com/cometbft/cometbft/consensus.(*State).tryAddVote(0xc00c87a380, 0xc00e9c5380, {0xc00c859800?, 0xc00d30fc08?})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:2056 +0x26\ngithub.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc00c87a380, {{0x61986e0, 0xc012f345c8}, {0xc00c859800, 0x28}})\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:928 +0x3ce\ngithub.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc00c87a380, 0x0)\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:835 +0x3d1\ncreated by github.com/cometbft/cometbft/consensus.(*State).OnStart in goroutine 181\n\t/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/state.go:397 +0x10c\n"}`

### Observed behaviour

panic

### Expected behaviour

no panic

### Steps to reproduce

```bash
1. run the test on ST branch `term-spot-via-governance`
```

### Software version

dev branch

### Failing test

test_terminate_spot_market

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/44066/testReport/junit/tests.governance/test_spot_market_gov/test_terminate_spot_market/

### Configuration used

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ze97286**
Closes #10669 

https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/44292/pipeline/

### CODE REVIEW

File: core/execution/spot/market.go [hunk 1]
```diff
@@ -2601,6 +2601,7 @@ func (m *Market) getLastTradedPrice() *num.Uint {
 // processFeesTransfersOnEnterAuction handles the transfer from general account to holding account of fees to cover the trades that can take place
 // during auction. This is necessary as during auction the fees are split between the participating parties of a trade rather than paid by the aggressor.
 func (m *Market) processFeesTransfersOnEnterAuction(ctx context.Context) {
+	println("processFeesTransfersOnEnterAuction")
```
Comment (EVODelavega) [inline core/execution/spot/market.go:2604]: rm debug

**Review by jeremyletang — APPROVED** [review]
